### ISSUE TITLE
MSBuild on macOS is running out of memory

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#1014]
Something in the way we are using MSBuild, some recent change to our projects or targets, or some recent change to .NET Core 2.1 is causing MSBuild to die with out-of-memory failures. It's consistently reproducing on our CI machines.

**Comment by natemcmaster** [comment]
Captured sample before the crash:
[dotnet-sample.txt](https://github.com/aspnet/Universe/files/1862165/dotnet-sample.txt)

**Comment by natemcmaster** [comment]
[dotnet-sample2.txt](https://github.com/aspnet/Universe/files/1862217/dotnet-sample2.txt)

**Comment by natemcmaster** [comment]
Status update: I have not been able to figure out what is going wrong yet. Could be something in MSBuild's nodeReuse refactoring, a bug in the JIT, or something else. I have a memory dump but know way to inspect what's in it. I'm currently considering other options. If we did #922, we wouldn't need the expensive analysis in AnalyzeBuildGraph task (which is currently the source of this issue). Unless I can get traction on debugging MSBuild for macOS, I may pursue that instead

@ryanbrandenburg @Eilon

**Comment by natemcmaster** [comment]
Turns out it's a lot of work to setup a machine to debug a macOS dump. https://github.com/dotnet/coreclr/issues/12301 you have to recompile libcoreclr yourself. The memory dump I have was gathered using a different libcoreclr, so the dump I have is useless unless we run MSBuild on a custom private of coreclr.

Let's just workaround this by hard-coding for now (#1028) and readdress this when we get to #922.

**Comment by Eilon** [comment]
No plans to continue the investigation here. Will evaluate https://github.com/aspnet/Universe/issues/922 instead.
