### ISSUE TITLE
Ship dotnet-aspnet-codegenerator once signing issue with CLI shim is resolved

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#1027]
This was pulled from preview2 because the executable generated on install is not signed.

Changes required:
 - Revert https://github.com/aspnet/Universe/pull/1022
 - We may need to bundle and sign our own executable shim in the dotnet-aspnet-codegenerator package. Still waiting on a design from @wli3 et. al.

FYI @muratg @prafullbhosale @Eilon - tentatively putting this issue in the rc1 milestone

**Comment by Eilon** [comment]
Makes sense, thanks.

**Comment by Eilon** [comment]
Blocked until the tool can ship its own shim, which we would be able to sign.

**Comment by natemcmaster** [comment]
We have an initial design for this now. It looks like we are unblocked on this now and should probably assign someone to work on this soon.

**Comment by natemcmaster** [comment]
Part of the details are still internal. I'll add you to the email thread.

**Comment by muratg** [comment]
Hi @seancpeters, I was told you're the new scaffolding owner!  Could you please take a look into this?

You'll need to send a shiproom approval this week. Next week will be escrow. 

cc @vijayrkn

**Comment by muratg** [comment]
Reminder: ask mode ends today.

**Comment by prafullbhosale** [comment]
Fixed by: https://github.com/aspnet/Scaffolding/pull/7

**Comment by vijayrkn** [comment]
@prafullbhosale wrong link?

**Comment by prafullbhosale** [comment]
Updated.

**Comment by natemcmaster** [comment]
Can you send a PR to Universe then to revert https://github.com/aspnet/Universe/commit/fbdb3c558f04a056732a87a2e1864786603ac201 on the release/2.1 branch?

**Comment by prafullbhosale** [comment]
Done.
