### ISSUE TITLE
Run Universe build as part of PR verification builds

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#1056]
For every PR opened on individual repo run a Universe build that includes changes from aforementioned pull request.

Would allow us to find artifact.props/external-dependencies.props/cross repo breaking changes before they hit aspnetci and block `Update Universe`.

Possible addition: For branches that start with `feature/` also try to check out other submodules to the same feature branch.

**Comment by Eilon** [comment]
The "Possible addition" sounds like a great idea.

**Comment by natemcmaster** [comment]
This will happen as a part of merging repos, which is tracked in other issues.
