### ISSUE TITLE
Crossgen the linux-arm shared runtime

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#1061]
Currently, the linux-arm shared runtime is not preoptimized via crossgen. This was not added in the first round because

- we currently lack the infrastructure to run crossgen via CI
- did not have time to validate a crossgen version works correctly
- the value of crossgen perf for linux-arm as not clear (we have a hunch, but did not do any perf tests)

**Comment by Eilon** [comment]
@DamianEdwards - we're putting this in the 2.2.0 release because we don't feel it's critical for 2.1.0 RTM. It's "just" an optimization and it is a huge cost to get crossgen working in the short time remaining.

**Comment by sdmaclea** [comment]
FWIW crosscomponent crossgen has been added to the runtime packages.

for arm32 it is a x86_arm package, so this can currently be run on x86 to crossgen for arm32.  @echesakovMSFT was working on getting crossgen support for x64_arm as well.  

x64_arm64 crosscomponent crossgen is included in the linux-arm64 runtime.  cli is using this to crossgen in the master branch (for 2.2).

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspNetCore#3652
