### ISSUE TITLE
Update to IdentityModel latest 5.2.x

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#1098]
We want to stay up to date with latest changes in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

**Comment by natemcmaster** [comment]
It looks like we're still compiling against 5.2.0. @brentschmaltz I noticed this version is unlisted on nuget.org. Is there a reason? Should we update to the latest 5.2.x release?

**Comment by brentschmaltz** [comment]
@natemcmaster 5.2.4 is our current release

**Comment by natemcmaster** [comment]
Ok. We'll do this in 2.2 preview2

**Comment by brentschmaltz** [comment]
ok

**Comment by natemcmaster** [comment]
Re-opening so we can track this work.

**Comment by Eilon** [comment]
@HaoK - is this sorta the same as https://github.com/aspnet/Security/issues/1843?

**Comment by HaoK** [comment]
Yeah I'll dupe 1843 against this

**Comment by brentschmaltz** [comment]
@HaoK we set the version to 5.3.0 (we have a breaking change in JsonWebToken). Nothing you use yet.
POR is to publish today (9/19)

**Comment by HaoK** [comment]
Fixed via https://github.com/aspnet/Universe/pull/1482

Updated to 5.3 and the AD package to 3.19.8
