### ISSUE TITLE
Determine the right version of Roslyn to reference in analyzer packages

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#1103]
I tried opening an application referencing `2.1.0-rc1-26420-08` in VS 15.6.6 and I get errors saying they could not load `Microsoft.CodeAnalysis`:

`Warning	CS8032	An instance of analyzer Microsoft.AspNetCore.Mvc.Analyzers.AvoidHtmlPartialAnalyzer cannot be created from \.nuget\packages\microsoft.aspnetcore.mvc.analyzers\2.1.0-rc1-30639\analyzers\dotnet\cs\Microsoft.AspNetCore.Mvc.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.`

We should figure out if this version of Roslyn is going to make in to VS or if we need to reference an older version of Roslyn in our analyzers.

**Comment by pranavkm** [comment]
@jaredpar we currently reference MicrosoftCodeAnalysis 2.8.0-beta3 in our analyzers simply because it's the version used across our repos. Should we downgrade this to an earlier version of Roslyn that's already shipped?

**Comment by jaredpar** [comment]
If you need to open your solution in 15.6 then you need to be targeting the 2.7 version of Roslyn. The 2.8 versions will ship with 15.7.

**Comment by pranavkm** [comment]
Checked with @DamianEdwards and we require VS 15.7 for 2.1.0. Nothing to do here. Thanks for your response @jaredpar
