### ISSUE TITLE
Update to release versions of Microsoft.Azure.Services.AppAuthentication 

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#1108]
We need to update to stable version before RTM.

**Comment by DamianEdwards** [comment]
Why is this in rc1?

**Comment by pakrym** [comment]
`Microsoft.Extensions.Configuration.AzureKeyVault` depends on it and ships in 2.1

**Comment by DamianEdwards** [comment]
Ok. Are we shipping that for RC1?

**Comment by pakrym** [comment]
Yes

**Comment by pakrym** [comment]
Talked to @DamianEdwards in person, we'll track it for RTM

**Comment by muratg** [comment]
This is done.
