### ISSUE TITLE
Run CodeAnalysis \ Fxcop as part of the build

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#111]
We need to figure out how to run FxCop as part of the build. `FxCopCmd` requires knowing the full closure of references to run - this is problematic in our build.

**Comment by muratg** [comment]
Aren't we doing this already now? @pranavkm @Eilon

**Comment by davidfowl** [comment]
No, we are not.

**Comment by pranavkm** [comment]
What do other teams (CoreFx \ Roslyn) etc do here?
