### ISSUE TITLE
Upgrade to netcoreapp2.2

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#1120]
Latest builds of the .NET Core runtime require us to update our TFM.

Things to investigate:

 - does VS tooling work with the new TFM yet?
 - does the SDK work on the new TFM?
 - is there anything that needs to stay on 2.1?
 - what does our test matrix look like now? We currently test netcoreapp2.0 and 2.1. Do we need to add a 3rd netcoreapp version to that?

**Comment by ryanbrandenburg** [comment]
1. As far as I can tell.
2. As far as I can tell.
3. We aren't moving any product projects, but mostly all test projects moved to 2.2.
4. For every repo except EF our test matrix should now be "net461;netcoreapp22"

**Comment by natemcmaster** [comment]
I'm still seeing a fair amount of 'netcoreapp2.1' code. I see 243 usages in aspnet/Universe (dev). From what I can tell, many of these are things that still need to update...but I didn't look closely at all 243 instances.

**Comment by ryanbrandenburg** [comment]
I believe I've addressed all this one.
