### ISSUE TITLE
Reduce size of the nuget fallback folder

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#1124]
The NuGet fallback folder for 2.1 is a whopping 1.01 GB once expanded on disk. This includes lots of packages that should be unnecessary to *execute* a .NET Core 2.1 application, but are still required to *restore* a .NET Core 2.1 application.

This includes:
 - multiple copies of the same package (Newtonsoft.Json 9, 10, and 11)
 - multiple versions of NETStandard.Library (1.6.0, 1.6.1, and 2.0.3)
 - a bunch of runtime.native.* specific packages. In theory, these should only be consumed when users are producing a self-contained app, but this is out of scope for the offline cache
 - 670 MB of .xml docs
 - 147 MB of .nupkg files (why are they needed -- the contents of the .nupkg have already been unzipped)

Result:

 - bloated Docker images
 - longer first-run experience required to expand all these files
 - wasted disk space on CI machines (xml docs are typically only used by IDEs)

## More details

A peek inside. Here are the packages that consume the most disk space:

<img src="https://user-images.githubusercontent.com/2696087/39387258-7b511e36-4a2d-11e8-9233-478ecbd331c8.png" width="500" />

Also, here is a breakdown of the files inside:

<img src="https://user-images.githubusercontent.com/2696087/39387271-8bbaca74-4a2d-11e8-9bbb-a4a79cf845fa.png" width="350" />

Here are all the runtime.* specific nupkgs inside

<img src="https://user-images.githubusercontent.com/2696087/39387309-c0825f56-4a2d-11e8-8cf7-f978953a50f5.png" width="400" />

**Comment by natemcmaster** [comment]
cc @DamianEdwards @JunTaoLuo @weshaggard - you're already aware of this issue, but figured we could use this to keep track of ongoing investigation on this issue.

**Comment by natemcmaster** [comment]
Related issues

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/925
https://github.com/dotnet/roslyn/issues/26299
https://github.com/NuGet/Home/issues/6516

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspNetCore#3650
