### ISSUE TITLE
sake documentation

### ISSUE THREAD

**Issue by desdesdes** [aspnet/Universe#113]
I am looking a how to setup a cross platform build system vNext projects. I see sake is used for all aspnet repo's. I cannot seem to find any documentations on it. The nuget server tells me the project site is http://loudej.github.io/sake, but that site is empty. I looked at https://github.com/sakeproject/sake but the latest release there is alpha-7. I cannot seem to find any documentation on how to write shade files. Can you point me to some documentation or a starting point.

Regards,
Bart

**Comment by jeffogata** [comment]
I have started documenting what I've learned about Sake here:  http://sake-docs.readthedocs.org/en/latest/index.html

This is still a work in progress, but hopefully will help anyone curious about working with Sake.

**Comment by Eilon** [comment]
The plan is to move away from Sake, so closing this.
