### ISSUE TITLE
Include the Microsoft.AspNetCore.Mvc.Testing package in the LZMA

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#1147]
Not a mainline scenario but we could consider adding this into the fallback archive.

**Comment by natemcmaster** [comment]
My vote is to not include this. We don't put xunit in the offline cache either.

Thoughts @DamianEdwards @livarcocc ?

**Comment by natemcmaster** [comment]
Microsoft.AspNetCore.Mvc.Testing isn't part of the main metapackages anymore so it's not necessary to include in the LZMA.

In the past, we've recognized that we do not cover all in-box scenarios with the offline cache. Test projects are currently not a scenario we cover with the offline cache. IMO unless we're willing to add xunit, MSTest, and VSTest packages to the cache, I don't see much value in adding Microsoft.AspNetCore.Mvc.Testing

**Comment by javiercn** [comment]
@Eilon @JunTaoLuo @natemcmaster This is not dependent on xUnit at all and is part of the product that we ship to our customers. Users should be able to create functional tests for their app without network connection, in the same way they can create an MVC app.

**Comment by natemcmaster** [comment]
> Users should be able to create functional tests for their app without network connection, 

This means we need to include xunig, MSTest, and/or VSTest packages in the cache too, right?

**Comment by livarcocc** [comment]
I don't believe this will be a scenario we will support offline actually. Even for 3.0, I don't believe the test framework will be part of the targeting packs that we intend to add to the SDK. At least, I heard nothing towards this so far.

**Comment by javiercn** [comment]
I'll let @DamianEdwards @danroth27 etc chip in. I'm good with whatever. Is TestHost not part of the LZMA?

**Comment by Eilon** [comment]
If there's no testing framework on the box then I don't see a need to add a package to the LZMA that in practice no one will be able to use.

**Comment by JunTaoLuo** [comment]
I would vote not including this in the LZMA as well.

**Comment by Eilon** [comment]
OK so closing this for now. If we change our minds, we can do it later.
