### ISSUE TITLE
Remove un-needed instances of MicrosoftNETCoreApp21PackageVersion etc

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Universe#1153]
When moving to netcoreapp2.2 we started out trying to remove any instances of `MicrosoftNETCoreApp21PackageVersion` and `MicrosoftNETCoreApp20PackageVersion` that weren't needed anymore, but doing the logic for that across 50 repos was bogging down the rest of the work, and they weren't hurting anything, so we stopped trying to enforce that.

This item tracks the work of going back and removing that kind of unused thing, including `DotNetCoreRuntime` , `RuntimeFrameworkVersion` and more.

**Comment by ryanbrandenburg** [comment]
We can also move any benchmarks projects except those in EF and aspnet/Benchmarks to netcoreapp2.2 and remove any 2.0 or 2.1 stuff that frees up.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspNetCore#3649
