### ISSUE TITLE
Replace all escaped msbuild code with CDATA

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Universe#1166]
In some places we have xml string inside of PropertyGroups, currently we store that data as a normal escaped string (`&lt;MyPropertyGroup&gt;`). This is super hard to read, edit and understand. @natemcmaster recently discovered CDATA, which can show this data in a much more useful view:

https://github.com/aspnet/BuildTools/blob/3d2175ced2de3110d649c72703373cd76f98db92/test/KoreBuild.FunctionalTests/GenerateTestProps.targets#L4-L17

Lets find all the instances where we have XML strings in our code and turn them into CDATA for understand-ability.

Super low priority so I've sent it to the backlog.

**Comment by natemcmaster** [comment]
Closing as low priority. As you're working on code, feel free to replace XML with CDATA strings instead, but we don't plan to spend time searching our code for places where we should use CDATA instead.
