### ISSUE TITLE
Update Web API Client version reference by Microsoft.AspNetCore.App to the latest version

### ISSUE THREAD

**Issue by danroth27** [aspnet/Universe#1170]
Current dependency is on 5.2.4.

Expected dependency is 5.2.6.

**Comment by mkArtakMSFT** [comment]
@JunTaoLuo, is this done already? Should it be closed now?

**Comment by natemcmaster** [comment]
John is OOF. Yes, this was done in https://github.com/aspnet/Universe/pull/1176
