### ISSUE TITLE
Run test projects in a better order

### ISSUE THREAD

**Issue by bricelam** [aspnet/Universe#119]
Right now, the test projects are run alphabetically by project name.

A better order would be: Unit first, Functional last, topologically sorted by product dependencies.

For example:
- EntityFramework.Tests
- EntityFramework.SqlServer.Tests
- EntityFramework.FunctionalTests
- EntityFramework.SqlServer.FunctionalTests

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
