### ISSUE TITLE
Pin LZMA shared framework versions for 2.2

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#1235]
For every release where we still build the LZMA, we need to pin the version of the NETCore.App and AspNetCore.App we use when we generate the LZMA to the implicit versions set by the SDKs. By default, in every non-rtm build we set this to the latest ingested runtimes but we need to make sure this is done when we release the first 2.2.1 patch.
cc @natemcmaster

**Comment by natemcmaster** [comment]
Can we do this before RTM? Seems like we often forget these things, even if we have issues. IMO it would be good to code the behavior we expect ahead of time.

**Comment by JunTaoLuo** [comment]
We have to define the pinned versions somewhere and we can't really infer them to always be Major.Minor.0 since we have situations like we have for 2.1.1 and 2.1.3 where we reset our baseline implicit versions. But maybe we can make these changes a little more obvious:

1. Add the pinned versions (e.g. `LZMAMicrosoftAspNetCoreAppAll22PackageVersion`) to `versions.props` and set them to 2.2.0 (for now). We will need to update these as necessary but putting them in the `versions.props` file may increase visibility.
2. Update the LZMA generation step to choose between `LZMAMicrosoftAspNetCoreAppAll22PackageVersion` and `PackageVersion` based on the `PrereleaseVersionLabel` property. This way, for prerelease builds, we will continue to use the latest bundled versions of the dotnet and aspnet shared frameworks. Once we switch to rtm releases, it will use the pinned versions instead.

**Comment by JunTaoLuo** [comment]
Actually I don't think using `PrereleaseVersionLabel` will work since the first time we build 2.2.0-rtm, we still need to use the latest bundled versions of the shared frameworks. I guess we need another flag that differentiates between pre-release builds and patch builds.

**Comment by natemcmaster** [comment]
I believe this is resolved with c1fb4479a36f6049b897c52e5eae94468b9d1fba. The LZMA generation shouldn't lift higher than 2.2.0 and includes correctly pre-release versions of 2.2.0.
