### ISSUE TITLE
Our .gitattributes is incomplete

### ISSUE THREAD

**Issue by bricelam** [aspnet/Universe#124]
The `.gitattrubtes` file under `build-template/` goes to a lot of lengths to list individual file patterns, but it is incomplete. For example, it doesn't list `*.json`, `*.kproj`, `*.cshtml`, or `*.config`. This leads to inconsistent eol characters in these files.

Ideally, the file should contain one line:

```
* text=auto
```

With this, git will (99.999% of the time) just do "the right thing".

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.

**Comment by bricelam** [comment]
Here is the file @dougbu and I decided on:
```
*     text=auto   # Auto-detect text vs binary
*.cs  diff=csharp # Better context in unified diffs
*.sh  eol=lf      # Force \n on shell scripts
*.sln eol=crlf    # Force \r\n on solution files (may not be necessary)
```

**Comment by dougbu** [comment]
👍 Would be great if we can preserve the comments. Looks like whole-line ones work (similar to `.gitignore` files) but EOL comments don't.

**Comment by dougbu** [comment]
No, we haven't done an across-the-Universe update to simplify `.gitattributes`. The issue hasn't been triaged and isn't assigned to anyone.

**Comment by Eilon** [comment]
This doesn't seem like it's a problem anymore. I can't recall seeing this problem from any contributors.
