### ISSUE TITLE
Add a package dependency from Microsoft.AspNetCore.{App,All} => NETCore.App

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#1256]
Part of implementing https://github.com/aspnet/Home/issues/3307 we need to resolve is how to make sure both AspNetCore.App and NETCore.App end up in the restore graph so you get all the right ref assemblies.

@JunTaoLuo looked into this in the past but ran into issues. We should take a closer look at those again to inform our strategy about how we should move forward with https://github.com/aspnet/Home/issues/3307

**Comment by JunTaoLuo** [comment]
I forget the issue we ran into originally, but it may have been resolved. A few things we would want to check are:
1. The correct set of build/compile targets are brought in correctly
2. The deps files generated are compatible with MVC features
3. The generated shared frameworks in our build contains the full set of binaries required for layered frameworks
4. No restore graphs and publish output regression

**Comment by dsplaisted** [comment]
Instead of adding a package dependency, why wouldn't we just have two separate implicit package references?

**Comment by natemcmaster** [comment]
It looks like there may be one side effect. The .deps.json generation produces a slightly difference result when NETCore.App is transitive.

When you have NETCore.App and AspNetCore.App as direct deps, you get.
```
      "Microsoft.NETCore.App/2.1.0": {
        "dependencies": {
          "Microsoft.NETCore.DotNetHostPolicy": "2.1.0",
          "Microsoft.NETCore.Platforms": "2.1.0",
          "Microsoft.NETCore.Targets": "2.1.0",
          "NETStandard.Library": "2.0.3"
        },
        "compile": {
          "ref/netcoreapp2.1/[BUNCH OF ENTRIES FOR System*.dll HERE]": {},
        }
      },
```

But with only AspNetCore.App as the top-level dep and NETCore.App is transitive, you get,


```diff
      "Microsoft.NETCore.App/2.1.3-servicing-26708-02": {
        "dependencies": {
          "Microsoft.NETCore.DotNetHostPolicy": "2.1.3-servicing-26708-02",
          "Microsoft.NETCore.Platforms": "2.1.1-servicing-26708-02",
          "Microsoft.NETCore.Targets": "2.0.0",
          "NETStandard.Library": "2.0.3"
        },
        "compile": {
          "ref/netcoreapp2.1/[BUNCH OF ENTRIES FOR System*.dll HERE]": {},
        }
+       "compileOnly": true
      },
```

@dsplaisted is this an SDK bug? @pranavkm  would this break MVC/Razor compilation?

**Comment by natemcmaster** [comment]
Otherwise, build output and publish output looks the same.

**Comment by pranavkm** [comment]
MVC doesn't specifically look at the `CompileOnly` option from the deps file, so presumably not

**Comment by natemcmaster** [comment]
Ok, then I think we would be okay to make this change. I tested that build-time and runtime compliation still work.

**Comment by natemcmaster** [comment]
This is being punted for now. Removing from the 2.1 milestone

**Comment by natemcmaster** [comment]
At this point, there is no plan to change this in 2.1. @dsplaisted do you think we should address this in 2.2?

**Comment by dsplaisted** [comment]
My opinion is still that it would probably be better to address this in a different way (ie via two implicit references instead of a package dependency).  It's possible that I don't understand everything about this though.  From this issue, it's not clear to me if there's even a concrete problem that would be solved by adding the dependency, or by having multiple implicit references.

**Comment by natemcmaster** [comment]
Cool, two implicit references it is. That just reduces the differences between 2.1 and 2.2, and so far this hasn't been an issue.

Closing as wontfix since we don't have a compelling reason to do this.
