### ISSUE TITLE
`k test` does not show build failures

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#142]
The new Xunit test runner does not print compilation failures in tests and fails with a non-specific error:

```
Discovering: Microsoft.AspNet.Mvc.Razor.Host.Test
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.Mvc.Razor.Host.Test' or one of its depend
encies. General Exception (Exception from HRESULT: 0x80131500)
```

Running kpm build prints build failures:

```
kpm build --quiet

Building Microsoft.AspNet.Mvc.Razor.Host.Test for Asp.Net,Version=v5.0
Mvc\test\Microsoft.AspNet.Mvc.Razor.Host.Test\SpanFactory\UnclassifiedCodeSpanConstructor.cs(71,35): erro
r CS0246: The type or namespace name 'RazorDirectiveAttributeCodeGenerator' could not be found (are you missing a using
directive or an assembly reference?)

Build failed.
    0 Warnings(s)
    1 Error(s)
```

We should consider running `kpm build` as part of `_k-test.shade` so build failures are correctly reported. We could consider doing this conditionally do this the CI if it slows down local builds.

**Comment by pranavkm** [comment]
cc @bricelam @davidfowl

**Comment by rynowak** [comment]
We should just fix this in the runner. https://github.com/xunit/aspnet.xunit/issues/2

**Comment by pranavkm** [comment]
Closing since it's likely to be addressed by the runner.
