### ISSUE TITLE
ApiCheck baselines need to be updated

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#1427]
Missed updates to api check baselines seem more prevalent than I originally anticipated.

I've updated the Kestrel repo: https://github.com/aspnet/KestrelHttpServer/pull/2959. 

But now I see it in other repos as well: 
https://github.com/aspnet/Hosting/blob/release/2.2/src/Microsoft.AspNetCore.Hosting/baseline.netcore.json#L2. 
https://github.com/aspnet/IISIntegration/blob/release/2.2/src/Microsoft.AspNetCore.Server.IISIntegration/baseline.netcore.json#L2
https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authorization/baseline.netcore.json#L2
https://github.com/aspnet/MetaPackages/blob/master/src/Microsoft.AspNetCore/baseline.netcore.json#L2

This is by no means an exhaustive list, I just took a quick look at a few of our repos. We should systematically scan through all of our repos to make sure everything is up to date.

cc @ryanbrandenburg @Eilon

**Comment by ajcvickers** [comment]
Confirmed there are no breaking changes from 2.1 to 2.2 preview3 for these assemblies.

**Comment by Eilon** [comment]
Thanx!
