### ISSUE TITLE
problem with Microsoft.Extension.Configuration.*

### ISSUE THREAD

**Issue by iceoz** [aspnet/Universe#1478]
Hi, i'm facing a strange problem, i make some microservices, some of them are just consoleApp with hostbuilder using only Microsoft.NETCore.App SDK, and others are webapi using Microsoft.NETCore.App SDK and Microsoft.AspNetCore.App everyone with 2.1 version

everything worked fine until i try to make some nugets for helpers, in console applications and class libraries i'm using Microsoft.Extension.Options.ConfigurationExtensions with version 2.1.1 without problem, but when i try to install my nuget on webapi i get a error with Microsoft.Extension.Configuration.Binder 2.1.1 with is not compatible with Microsoft.AspNetCore.App 2.1.0, so i need to make a rollback in all nugets i'm using, and there is no updates inside nuget, i'm using the latest version of sdk 2.1.4.....

**Comment by Eilon** [comment]
This issue was moved to aspnet/Configuration#892
