### ISSUE TITLE
Have the build ensure that common files are up-to-date (gitignore, gitattributes, build scripts, etc.)

### ISSUE THREAD

**Issue by Eilon** [aspnet/Universe#15]
Each repo today has different flavors of our common files that are _supposed_ to be standardized. This should even include things like the dotsettings file for R#.

**Comment by CADbloke** [comment]
https://github.com/CADbloke/EntityFramework/commits/dev/EntityFramework.sln.DotSettings

**Comment by CADbloke** [comment]
https://github.com/aspnet/EntityFramework/commits/dev/EntityFramework.sln.DotSettings

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
