### ISSUE TITLE
Create tags for specific releases

### ISSUE THREAD

**Issue by kichalla** [aspnet/Universe#153]
Currently we do not have tags for specific releases (ex: Beta2) which makes it difficult to go back to certain point in history to get the build scripts for that release.

@pranavkm

**Comment by pranavkm** [comment]
cc @suhasj

**Comment by suhasj** [comment]
@kichalla Can you clarify when you say build scripts ? Do you mean the build.cmd or build.sh from the repos ?

**Comment by pranavkm** [comment]
The `KoreBuild` package. We need to ensure KoreBuild also gets branched and versioned when we do update-release \ update-master so that we can go back in time and rebuild packages with the right scripts.

**Comment by muratg** [comment]
I believe this is done automatically now. @pranavkm
