### ISSUE TITLE
Change repositories' "sources" section to "projects"

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Universe#166]
We renamed the "sources" section to "projects" in global.json. We should do it for our repositories.

**Comment by pranavkm** [comment]
I think I saw some project.json's that also had `code` attributes which are now `compile`. Should that change too?

**Comment by troydai** [comment]
Done in all repos. Waiting for a build pass on CI to close this bug.

**Comment by troydai** [comment]
Done
