### ISSUE TITLE
Make the Helios repository public

### ISSUE THREAD

**Issue by nathanaeljones** [aspnet/Universe#168]
As an [ASP.NET HttpModule/middleware developer](http://imageresizing.net), I've found the bridge between ASP.NET and IIS  to be the greatest source of trouble and bugs. Often small details (Like [preventing dynamically registered HttpModules from accessing static requests](http://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/5823099-add-overloaded-version-of-httpapplication-register)) make it impossible for me to provide developers with a painless experience.

There's a lot of middleware out there, and... every piece of middleware is unique. Furthermore, IIS has a seemingly infinite number of behavior permutations when it comes to HttpModule interaction.

The earlier we (library developers) can see Helios, the earlier we can identify architectural flaws which would otherwise make things impossible for us.

**Comment by davidfowl** [comment]
We're working on this, but FYI it doesn't contain any HttpModules, that's System.Web stuff. Helios is much lower level and has mostly pinvokes.

**Comment by nathanaeljones** [comment]
Yeah, it's the pinvokes I'm interested in. It's where IIS configuration and behavior meet ASP.NET that most of the serious (i.e, unfixable on my end) issues occur. I see new issues at that layer on a monthly basis, often coming down as security updates. Not fun. 99% were easily avoided, too, but no code review seemed to be happening - or, at least, not review for the kinds of issues that burn us middleware developers out.

Somewhat recently, IIS started breaking the rules around file access - reading files without establishing a read lock - while at the same time, .NET stopped flushing file writes deterministically. The overlap created devops nightmares around the globe. Low-level pinvoke details around things like WriteFile are actually really useful.

**Comment by nil4** [comment]
Would you mind giving a bit more details about why this was closed @muratg? Helios is still not public.
