### ISSUE TITLE
Rename nuget feed url key in Nuget.config to something other than NuGet.org

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Universe#174]
When `Nuget.config` contains a feed with key named `Nuget.org` VS nuget tooling seems to disable the public nuget feed due to a known issue : http://nuget.codeplex.com/workitem/4397.

We have seen many people run into this issue. Solution will be to rename the key name in all Nuget.config files to something other than `Nuget.org`.

**Comment by davidfowl** [comment]
The CI needs to be updated before this is done

**Comment by Praburaj** [comment]
Do we have redirect even for Nuget.org feed? I thought we redirect only the myget feed, no?

**Comment by davidfowl** [comment]
I'm pretty sure we have it for both. It's easy to check tho

**Comment by Praburaj** [comment]
Let me check this. I can take this work item.

**Comment by Praburaj** [comment]
I verified we don't hack the Nuget.org feed. We should be good to make the change. 

$packageShareName = "dev"
$branch = "%teamcity.build.branch%"
if($branch -eq "release") {
    $packageShareName = "release"
}

$config = "<?xml version=`"1.0`" encoding=`"utf-8`"?>
<configuration>
  <packageSources>
     <add key=`"KoreBuild`" value=`"<DropFolder>\Universe\${packageShareName}\latest\build`" />
     <update key=`"aspnetvnext`" value=`"<DropFolder>\latest-packages\${packageShareName}`" />
  </packageSources>
</configuration>"
[IO.File]::WriteAllText("$env:AppData\NuGet\NuGet.redirect.config", $config)
