### ISSUE TITLE
Change our default build to use CoreCLR

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Universe#194]
In an attempt to see if we can build our stack with the CoreCLR itself, I think we should see if we can do it with KoreBuild as a first step. The CoreCLR would also be crossgened so builds would go faster.

**Comment by muratg** [comment]
Yes!

**Comment by pranavkm** [comment]
I know @kulmugdha spent some time on converting Spark view engine to run on K (DNX). Might be useful to use that as a starting point to convert Sake.

**Comment by victorhurdugaci** [comment]
Not applicable anymore
