### ISSUE TITLE
Explicit versioning for build.sh

### ISSUE THREAD

**Issue by ryan1234** [aspnet/Universe#201]
Original issue from: https://github.com/aspnet/HttpAbstractions/issues/259

I'm not up to speed on the dev branches yet, so I'm still working from master branches. When I try to build with build.sh I am pulling down the dev version (beta5) of KoreBuild with all the dnx stuff.

I had to add explicit versioning for the KoreBuild nuget package to get beta3 stuff to build.

Example of old build.sh from master:

```
mono .nuget/nuget.exe install KoreBuild -ExcludeVersion -o packages -nocache -pre
```

Adding versioning to build beta3:

```
mono .nuget/nuget.exe install KoreBuild -ExcludeVersion -o packages -nocache -pre -version 0.2.1-beta3
```

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
