### ISSUE TITLE
MsBuild is hardcoded to v12

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Universe#205]
The native-compile target is hardcoded to MsBuild v12, which requires VS 2013 to be installed. This should be updated to v14 for VS 2015, or better yet, try both.
https://github.com/aspnet/Universe/blob/dev/build/_k-standard-goals.shade#L86

This breaks Helios if you don't have 2013 installed.  DNX is not broken because it defines it's own target.

**Comment by moozzyk** [comment]
#206

**Comment by moozzyk** [comment]
Fixed with e54a3b61c
