### ISSUE TITLE
New --parallel flag doesn't work for Roslyn / CoreCLR builds

### ISSUE THREAD

**Issue by Eilon** [aspnet/Universe#211]
On the CI the default build target is now `--parallel install` but that seems to break the Roslyn and CoreCLR builds. Sake explodes saying a key couldn't be found in a dictionary. Presumably it's trying to find a target that doesn't exist.

In the meantime I went to the TeamCity config and overrode the default build target for those two configs to remove the `--parallel` flag and now both builds pass.

Please investigate to see what the right long-term fix is.

@pranavkm

**Comment by pranavkm** [comment]
We should probably have those two use `k-standard-goals` (as a long term goal). For now your change seems ok. The unfortunate part is that I'm not seeing a significant drop in the total build time on the CI. Perhaps if we harden our tests and bring this back - https://github.com/aspnet/Universe/commit/d457b54a369ae27951f6e06132fd28ca3f20798c - we should start seeing better numbers.

**Comment by pranavkm** [comment]
We simply don't run those two configs in parallel. Doesn't seem to be an issue anymore.
