### ISSUE TITLE
Update build.cmd to pass in DNX_FEED \ flag to dnvm so we install the branch-appropriate DNX

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#215]
Based on conversation here - https://github.com/aspnet/Universe/pull/214/files#r29785476.

We should be able to pull in the latest dnvm and use it in our scripts without editing it.

**Comment by muratg** [comment]
How about KoreBuild?

**Comment by muratg** [comment]
Looks like this is not needed or done. Closing :) 

Reactivate if it's still needed. Thanks @pranavkm
