### ISSUE TITLE
Move nupkg to root of artifacts

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#22]
As part of #19, we're picking up everything under the artifacts directory. As a convenience thing, it would be nice to move the nupkg to the root of artifacts so we don't have to go about hunting for it in the artifacts view on the CI \ drop share.

**Comment by davidfowl** [comment]
@pranavkm Does this matter anymore?

**Comment by pranavkm** [comment]
It'll still be nice to do - we just have too many things that look for it under `artifacts\build`.
