### ISSUE TITLE
Pick up latest IdentityModel packages

### ISSUE THREAD

**Issue by danroth27** [aspnet/Universe#227]
We need to pick up the latest IdentityModel packages. The ones we have in our dev and release feeds are pretty old.

The new packages for beta5 are here: https://www.myget.org/gallery/azureadwebstackrelease.

**Comment by Eilon** [comment]
@pranavkm @danroth27 anything left to do here?

**Comment by pranavkm** [comment]
Nope. We've switched to their feeds - https://github.com/aspnet/Security/commit/6f935f8e28a4e2d6a811c89f27e3fce8825f53dd
