### ISSUE TITLE
Shell scripts do not quote variables when used as parameters, which breaks unescaped expansions.

### ISSUE THREAD

**Issue by dmccaffery** [aspnet/Universe#228]
For instance:

```` bash
#!/bin/bash

if test `uname` = Darwin; then
    cachedir=~/Library/Caches/KBuild
else
  if [ -z $XDG_DATA_HOME ]; then
        cachedir=$HOME/.local/share
    else
        cachedir=$XDG_DATA_HOME;
    fi
fi
mkdir -p $cachedir
````
In the above snippet, if the ~ expands to a home folder that includes a space in the path, then the mkdir command will fail. All parameters in bash including a space need to be escaped or quoted; even if they are a specified as a variable.

Assuming the following:

HOME=/Users/Deavon McCaffery/

then:

```` bash
mkdir -p $cachedir
````

expands to:

```` bash
mkdir -p /Users/Deavon McCaffery/Library/Caches/KBuild
````

This will fail. The $cachedir needs to be quoted when used as a parameter like:

```` bash
mkdir -p "$cachedir"
````

This issue is pervasive throughout all of the bash/shell scripts used in nearly every repository, and seems to originate from anything relying on the build-template in the universe repository: https://github.com/aspnet/Universe/blob/dev/build-template/build.sh

I'd be happy to fix the scripts up myself and submit a pull request, but this change would need to ripple through nearly every repository in aspnet; please advise as to the best way to proceed if you would like me to do this.

**Comment by dmccaffery** [comment]
... bump.

**Comment by dougbu** [comment]
@dmccaffery suggest closing this as a dupe of #99.

**Comment by dmccaffery** [comment]
Closing as duplicate per @dougbu request.
