### ISSUE TITLE
Build.sh will fail if wget is missing (curl missing output redirection).

### ISSUE THREAD

**Issue by dmccaffery** [aspnet/Universe#229]
The line at:

https://github.com/aspnet/Universe/blob/664d718398ab0d94ce14dc35d13509248d79f9fd/build-template/build.sh#L17

``` bash
wget -O $cachedir/nuget.exe $url 2>/dev/null || curl -o $cachedir/nuget.exe --location $url /dev/null
```

is missing an output redirection for curl, so the command will fail with an invalid or missing URL if wget is not available on the system.

Also, since $cachedir may be expanded with spaces in the path, the parameter which includes the variable should be quoted.

Line should be:

``` bash
wget -O "$cachedir/nuget.exe" $url 2>/dev/null || curl -o "$cachedir/nuget.exe" --location $url 2>/dev/null
```

**Comment by pranavkm** [comment]
Could you send a PR with the change to this repo - there's a copy of it in `build-template\build.sh`?

**Comment by dmccaffery** [comment]
@pranavkm sure. Can you merge #228 with this issue for reference since it also references unescaped sequences in parameter expansion?

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
