### ISSUE TITLE
CI builds will fail

### ISSUE THREAD

**Issue by dmccaffery** [aspnet/Universe#231]
Both of the CI build scripts [.travis.yml](https://github.com/aspnet/Universe/blob/664d718398ab0d94ce14dc35d13509248d79f9fd/.travis.yml#L4) and [appveyor.yml](https://github.com/aspnet/Universe/blob/664d718398ab0d94ce14dc35d13509248d79f9fd/appveyor.yml#L4) files include the following arguments:

- --quiet
- verify

These arguments are passed to sake as targets within build.sh. The #--quiet target is defined in the k-standard-goals include as part of KoreBuild. The #verify target is defined in the use-standard-goals include as part of Sake itself. Since neither of these includes are sourced in makefile.shade as part of the Universe build script (since it does its own git pull / build for each repository in the asp.net Universe), these CI builds will always fail.

I recommend changing the travis and appveyor commands to use the #verify-all target defined in makefile.shade, which will compile and verify each of the repos associated with the asp.net Universe. This will "prove" that all of the repositories are compiling and successfully passing tests. Otherwise; the CI build scripts should be removed (as they are useless the way they are defined now).

**Comment by victorhurdugaci** [comment]
We are no longer going to build this repo on travis/appveyor: https://github.com/aspnet/Universe/pull/268
