### ISSUE TITLE
Unable to find package 'KoreBuild' on Arch Linux

### ISSUE THREAD

**Issue by w4g3n3r** [aspnet/Universe#244]
Build.sh fails to install KoreBuild in any of the aspnet projects.
```
mono .nuget/nuget.exe install KoreBuild -ExcludeVersion -o packages -nocache -pre                                                        
Unable to find package 'KoreBuild'.

uname -a
Linux laptop-brianw 4.0.2-1-ARCH #1 SMP PREEMPT Thu May 7 06:47:54 CEST 2015 x86_64 GNU/Linux
```

**Comment by pranavkm** [comment]
What feeds is your `NuGet.config` pointing to?

**Comment by w4g3n3r** [comment]
The contents of my NuGet.Config file. I've also tried the vnext channel.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetVNext"
value="https://www.myget.org/F/aspnetmaster/api/v2/" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <disabledPackageSources />
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
</configuration>
```

**Comment by pranavkm** [comment]
The `KoreBuild` package seems to have been uploaded to Aspnetmaster about 4 days ago (See https://www.myget.org/gallery/aspnetmaster/). Could you try running `build.sh` again?

**Comment by muratg** [comment]
@w4g3n3r do you still have the issue? The package is also on aspnetvnext feed so not sure why it was failing for you.

**Comment by w4g3n3r** [comment]
I figured it out. I had to remove the /api/v2/ path off the AspNetVNext package source endpoint. Thanks guys.
