### ISSUE TITLE
Old author names still present in various build scripts and nuget specs

### ISSUE THREAD

**Issue by troydai** [aspnet/Universe#245]
Example:

https://github.com/aspnet/dnx/blob/dev/makefile.shade#L10
https://github.com/aspnet/Universe/blob/dev/build-template/makefile.shade
https://github.com/aspnet/Universe/blob/dev/KoreBuild.nuspec
https://github.com/aspnet/Universe/blob/dev/build/dnvm.ps1#L71

**Comment by Eilon** [comment]
Yup, this is on my list. Assigning to me for now.

**Comment by Eilon** [comment]
This looks like it's all gone now.
