### ISSUE TITLE
Korebuild should set NeutralResourcesLanguageAttribute as part of build

### ISSUE THREAD

**Issue by muratg** [aspnet/Universe#246]
https://github.com/aspnet/Options/issues/73 
https://github.com/aspnet/DependencyInjection/issues/256
https://github.com/aspnet/Configuration/issues/245

**Comment by muratg** [comment]
Not having this prevents UWP apps.

**Comment by muratg** [comment]
@Eilon who's the best person to look into this?

**Comment by Eilon** [comment]
Talked to @pranavkm and we will just do this manually in all the repos. We will then have an automated check that runs on every build as per https://github.com/aspnet/DnxTools/issues/3.
