### ISSUE TITLE
Change how pin-version target works

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#247]
Right now, the pin-version target requires specifying the version of CoreCLR and Roslyn packages and uses this information to perform a find and replace in `project.json`s. This process doesn't inspire too much confidence since it doesn't discriminate between arbitrary lines in the file.

A better approach would be to pin the versions based on aspnetmaster feed \ Coherence drop. It removes the risk of accidentally replacing incorrect values and being repeatable.

**Comment by troydai** [comment]
Looks good to me. Did we try it in a dry run?

**Comment by troydai** [comment]
:shipit:

**Comment by pranavkm** [comment]
Yeah, tried it on the current release branch (with the `git push` commented out) and the results looked good.
