### ISSUE TITLE
Build template changes alias

### ISSUE THREAD

**Issue by gingters** [aspnet/Universe#253]
In the build.cmd template (https://github.com/aspnet/Universe/blob/dev/build-template/build.cmd) there is this part:

    CALL packages\KoreBuild\build\dnvm install default -runtime CoreCLR -arch x86
    
    :run
    CALL packages\KoreBuild\build\dnvm use default -runtime CLR -arch x86

The problem is that this globally changes the `default` alias, which messes up with existing setups.
The template should be changed to either use no or another korebuild specific alias, and this should be propagated to all other repos that use the build template, as building any of these will change (and potentially break) existing settings.

**Comment by Eilon** [comment]
Yeah I do find this a little bit odd, but it is likely designed with the assumption that somebody running this is constantly working on the product, so setting it globally "isn't so bad". But I dunno, I could see it either way on this...

**Comment by dougbu** [comment]
We could choose a different alias but need _some_ alias because it's used not only in `build.cmd` and `build.sh` but also `_k-test.shade`. Current approach also works well when `$env:SKIP_DNX_INSTALL` is defined, as it is on our CI machines.

**Comment by victorhurdugaci** [comment]
dnvm is no longer used in KoreBuild so this will not be a bug anymore
