### ISSUE TITLE
Clear packages folder/cache + runtime on Linux/Mac CI

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#260]
The DNX build needs to clear the caches because you could get newer packages when you switch from dev to release

**Comment by victorhurdugaci** [comment]
@muratg can you please assign this to the CI buddies?

**Comment by muratg** [comment]
@victorhurdugaci These type of tasks won't be assigned to CI rotation.

**Comment by muratg** [comment]
@pranavkm Thoughts on this one?

**Comment by muratg** [comment]
Dup: #271

**Comment by pranavkm** [comment]
We actually do this on the CI now.
