### ISSUE TITLE
Add option to remove "src" from global.json

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#265]
This will be used to speed up the CI builds since we already have the product packages, there's no need to rebuild them during the test pass.

**Comment by victorhurdugaci** [comment]
@muratg can you please assign this to the CI buddies?

**Comment by muratg** [comment]
@victorhurdugaci These type of tasks won't be assigned to CI rotation.

**Comment by muratg** [comment]
Is this still needed with the dorkbuild?

**Comment by victorhurdugaci** [comment]
No
