### ISSUE TITLE
#native-compile should exclude certain known folders (e.g., node_modules, bower_components, etc.)

### ISSUE THREAD

**Issue by jeremymeng** [aspnet/Universe#269]
My project depends on the `grunt-sass` package, which pulls in the `libsass` source that include a .vcxproj.  However the source isn't build-able (due to missing `sassc` source code dependency).

It would be nice to exclude some known folders from `native-compile` target.  I was able to temporarily work around it via

```
      var excludedFolders = new[] { "node_modules"};
       ...
          foreach (var project in nativeProjects)
          {
            if (excludedFolders.Any(f => project.Contains(f))) continue;
            Exec(msbuildPath, project + " /p:Platform=Win32" + commonParameters);
            Exec(msbuildPath, project + " /p:Platform=x64" + commonParameters);
          }
```

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
