### ISSUE TITLE
We need a way to clean the nuget/dnu caches on the CI

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#271]
Who wants to implement this? Volunteers? :D

**Comment by davidfowl** [comment]
The CI shouldn;t be caching. We should just pass --no-cache to dnu restore on the ci. We also only cache if using http based sources (which we shouldnt; be on the ci).

**Comment by pranavkm** [comment]
Can we instead add an option to redirect where the cache gets stashed (via env variable)? We can simply move it to that location in that case. 
Alternatively if we're good citizens and clear the cache ever so often `%DNX_HOME%/temp/cache` would be a nice location to relocate it. We have %DNX_HOME% redirected to a subdir of the working directory on the CI so it we wouldn't need to do anything.

**Comment by muratg** [comment]
Closing this one too based on @pranavkm's comment on #260.
