### ISSUE TITLE
Builds pass silently even if some of the steps throw errors

### ISSUE THREAD

**Issue by kichalla** [aspnet/Universe#273]
The build step where we try to create the symlink for the `Latest` build results in access denied errors...in this case we need to return an error code..currently the build silently passes.

**Comment by muratg** [comment]
Could https://github.com/aspnet/dnvm/issues/428 be the reason?

**Comment by kichalla** [comment]
@muratg thanks for the link...will investigate more and will get back.

**Comment by muratg** [comment]
@kichalla any updates on the investigation?

**Comment by kichalla** [comment]
@muratg yes, I found that we are not using exit codes properly to indicate a build failure. I have fixed this in our CI, so this issue is good to be closed.
