### ISSUE TITLE
Bring back some way to run tests for a single repo (or split MVC + Music store)

### ISSUE THREAD

**Issue by HaoK** [aspnet/Universe#274]
I love how fast it is building in the new CI, but the workflow to verify/fix tests is pretty painful right now, as there's no way to rerun only failed tests (repos you are working on) so each iteration is a minimum of 50 minutes.

A simple mitigation would be to move MVC and Music store into a 3rd project since mostly its waiting 30 minutes to get to MVC + Music store tests to run/pass.

Core / EF / MVC + MusicStore as the 3 tests groups would be awesome :)

**Comment by pranavkm** [comment]
cc @victorhurdugaci

**Comment by muratg** [comment]
Let's try to do it in Beta 8.  We can move to RC1 if it doesn't fit.

**Comment by victorhurdugaci** [comment]
Fixed
