### ISSUE TITLE
Switch to coreclr for restore (at least on xplat)

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Universe#290]
It works better than mono.

/cc @dougbu @pranavkm

**Comment by dougbu** [comment]
Self-assigning and moving into this milestone. Travis is just too annoying.

**Comment by dougbu** [comment]
Reopening since 4e87b0c was not a fix for this bug.

**Comment by dougbu** [comment]
Part one of another run at this bug: aspnet/DNX@a2ed65a

**Comment by dougbu** [comment]
Part two: 419d3a3

**Comment by dougbu** [comment]
Travis runs on Ubuntu 14.04 and performs `dnu restore` using .NET Core in all of our repos now.
