### ISSUE TITLE
Branch Setup when branching for release

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#293]

**Comment by Eilon** [comment]
@joeloff FYI

@pranavkm does this just involve adding the Setup repo to the update script? Or do we have to do anything in the Setup repo too? Or the CI machine?

**Comment by pranavkm** [comment]
It's adding Setup to the list and making sure it branches correctly.

**Comment by joeloff** [comment]
I doubt there's anything we'd would need to add for Setup.
