### ISSUE TITLE
Test and fix any issues with the triggers

### ISSUE THREAD

**Issue by muratg** [aspnet/Universe#296]
- [x] Normal build triggered with check-ins. I believe this already works
- [ ] Manually triggering `Common` when `UniverseTests` or EF tests fail
- [ ] Manually triggering `Common` again when `Common` fails

The second and the third were the scenarios we had issues with during Beta 8. Let's fix these to make our CI more solid.

cc @Eilon

**Comment by pranavkm** [comment]
I didn't see any of these issues so far. I think the issue with canceling one of the DNX builds (from the trigger's logs), but I've haven't been able to repro the actual steps that cause this. I'll keep a look out for this issue.

**Comment by pranavkm** [comment]
Closing this since we're not seeing any of the specified issues.
