### ISSUE TITLE
Implement gating mechanism form the Roslyn configuration and enable daily builds

### ISSUE THREAD

**Issue by muratg** [aspnet/Universe#298]
In Beta 8, picking up a new build of Roslyn after we haven't for a while caused EF to fail, and they had to react quickly.  We should implement a "gating" mechanism similar to that @pranavkm implemented for CoreCLR:  Try out a new Roslyn.  If it's good, take it, if not, CI rotation folks would need to follow up, but we can continue to use the 'last known good' Roslyn.  The gating mechanism should probably involve trying to build EF.  We should run this daily like CoreCLR.

cc @Eilon @divega

**Comment by divega** [comment]
:+1: Our codebase (all of ASP.NET and EF in particular) are good scenario tests for Roslyn and it makes sense to do this to find bugs before they become a pain.

**Comment by muratg** [comment]
I believe the current plan is to integrate Roslyn gate to the current gate ("CoreCLR").

@ryanbrandenburg will you be doing this work?

**Comment by ryanbrandenburg** [comment]
I haven't been instructed to do this work, but I'd be interested and willing assuming @Eilon doesn't want someone else or have other plans for me. It might be worth just confirming that we still want this for RC2 considering how late in the game it is though.

**Comment by Eilon** [comment]
I'm fine with anyone doing this, so long as said person knows what to do here :smile:

**Comment by muratg** [comment]
Basically we try taking a new Roslyn in the "CoreCLR" configuration. Possibly running an EF build with it in addition to running "Build Universe, run MusicStore" test.

**Comment by muratg** [comment]
Looks like @pranavkm is already on it: https://github.com/aspnet/CoreCLR/pull/80

**Comment by pranavkm** [comment]
We need to unstick the Roslyn versions in our project.json to go with this change - 

* https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/project.json#L19
* https://github.com/aspnet/EntityFramework/blob/bfadc70c7f677641199a3c7ed80c20022379158c/test/Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests/project.json#L17
* https://github.com/aspnet/Scaffolding/blob/078ee20cd6359d0d4b1ec50378ece55a6e9c072b/src/Microsoft.Extensions.CodeGeneration.Utils/project.json#L7
* https://github.com/aspnet/Scaffolding/blob/078ee20cd6359d0d4b1ec50378ece55a6e9c072b/src/Microsoft.Extensions.CodeGeneration.Templating/project.json#L9

(might be more in Scaffolding).

**Comment by ryanbrandenburg** [comment]
Looks like there's also:  
- https://github.com/aspnet/Scaffolding/blob/078ee20cd6359d0d4b1ec50378ece55a6e9c072b/src/Microsoft.Extensions.CodeGeneration/project.json#L9
- https://github.com/aspnet/Scaffolding/blob/078ee20cd6359d0d4b1ec50378ece55a6e9c072b/src/Microsoft.Extensions.CodeGeneration.EntityFrameworkCore/project.json#L10
