### ISSUE TITLE
Enable CI test runs on downlevel Windows

### ISSUE THREAD

**Issue by muratg** [aspnet/Universe#305]

**Comment by victorhurdugaci** [comment]
This is done :)

**Comment by victorhurdugaci** [comment]
We got successful runs on all platforms. Closing

**Comment by muratg** [comment]
So it's green forever? :)  

Build buddies from now on should start watching these builds as well then.  cc @moozzyk @Tratcher

**Comment by Tratcher** [comment]
Oh? 2008R2 has almost never passed.

**Comment by muratg** [comment]
@victorhurdugaci?
