### ISSUE TITLE
Create a release feed with pacakges that we don't ship

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#306]
Today if you clone old releases (beta7 or beta8), it's almost impossible to build because a lot of packages don't exist anymore (KoreBuild, *.Sources.*, etc) so you end up having to build the universe in order to build a simple repo.

I propose that we create a feed that we never clean up that has all the packages from major release that we don't ship on NuGet. Then, each NuGet.config from a tag will point to both NuGet.org and that feed.

cc @muratg @Eilon

**Comment by pranavkm** [comment]
They should have a reference to aspnetmaster. We publish all our packages to it. Are you seeing issues here?

**Comment by Eilon** [comment]
Indeed, we already have that all in aspnetmaster. To use a 'master' branch you need the 'master' feed. Nature is full of symmetries such as this :smile:
