### ISSUE TITLE
Verify that all managed dlls are signed and have the same public key token

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Universe#310]
We need this verification once https://github.com/aspnet/dnx/issues/2615 is completed.

**Comment by moozzyk** [comment]
/cc @ajaybhargavb @cesarbs 

@muratg - please triage accordingly

**Comment by muratg** [comment]
@ajaybhargavb this is something the verifier tool do, right?

**Comment by ajaybhargavb** [comment]
Yes, but not sure if it verifies public key tokens.

**Comment by muratg** [comment]
This is not urgent, but we'll need to do it at some point to ensure the identity of the packages stay the same in the future.  We may need to add the functionality to read the public key tokens, and compare them with a single hardcoded token.

**Comment by Eilon** [comment]
The tool verifies that they are strong-name signed, but I think not the specific token. Can move the bug to DnxTools...

**Comment by ajaybhargavb** [comment]
aspnet/DnxTools@feda5f471c847ce3d0cb51242aab3c8ecf97f9ba
