### ISSUE TITLE
Change project.json to target minimal generations

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#315]
As a first pass in RC1, we modified project.jsons to target `net451` and `dotnet5.4` (https://github.com/aspnet/Universe/issues/300). To support EF in UAP, we added `netcore50` to libraries consumed by EF.

As a follow up, we need to determine the minimal generation to target. This would involve

* Replacing `net451` and `dotnet5.4` with a single `dotnet5.2` in projects where possible.
* Determine if simply targeting `dotnet5.4` (which is only consumable by projects targeting `net46` or higher) is acceptable.

**Comment by muratg** [comment]
I assume this changes with dotnet CLI and dorkbuild?

**Comment by bricelam** [comment]
I think we need updated UWP/NuGet tooling to support anything besides `netcore50` and `dotnet50`... But I'm sure it's in the works.

**Comment by davidfowl** [comment]
We need to take another look at this.

**Comment by muratg** [comment]
@davidfowl what needs to be done? for libraries we just change the TFM, no?

Maybe more is involved for user-secrets, iis-publish etc.

**Comment by muratg** [comment]
@davidfowl Are you looking into this?

**Comment by muratg** [comment]
@pranavkm Let's chat when you're back to understand what needs to be done.

**Comment by pranavkm** [comment]
* [*] PlatformAbstractions - Has to be cross compiled due to System.AppContext reference
* [*] Common
* [ ] Testing
* [*] JsonPatch
* [*] FileSystem - Microsoft.Extensions.FileProviders.Physical, FileSystemGlobbing have to be cross compiled due to System.IO.FileSystem reference
* [*] DependencyInjection
* [ ] Microsoft.Data.Sqlite - System.Data.SqlClient package is bad which prevents us from cross-compiling.
* [*] Configuration - Abstractions, Microsoft.Extensions.Configuration and Binder target netstandard1.1. The remainder reference System.IO.FileSystem.
* [*] EventNotification
* [*] HttpAbstractions - Only Headers could be converted. The remainder target Crypto and WebSockets which is only available at netstandard1.3.
* [*] Options
* [*] Logging - Console, EventLog, and TraceSource are cross compiled. The remainder target netstandard1.1
* [*] BrowserLink - Cannot be changed due to System.Runtime.Loader reference (netstandard1.5 only)
* [*] HtmlAbstractions
* [*] UserSecrets - Microsoft.Extensions.Configuration.UserSecrets references Configuration.Json which is cross compiled.
* [*] DataProtection - Cannot be changed due to crypto references.
* [*] Caching - Abstractions targets netstandard1.0. Caching.Memory uses AsyncLocal which is only available in netstandard1.3. Caching.SqlServer runs into issues with bad SqlClient package. Need to wait for non-alpha Redis package (https://www.nuget.org/packages/StackExchange.Redis.StrongName/1.1.572-alpha) to cross compile.
* [*] Hosting - Can't be changed due to HttpAbstractions references
* [*] Razor - Can't be changed due to crypto reference
* [ ] EntityFramework

The remainders are middlewares and servers which have to be cross compiled due to HttpAbstractions.

**Comment by pranavkm** [comment]
@bricelam we could avoid cross compiling some of the projects in EF (need to replace System.ReflectionTypeExtension methods with vanilla GetTypeInfo() calls). I'm not sure if that would affect the csproj generation though.

**Comment by bricelam** [comment]
I prototyped using our csproj generation for netstandard projects. It will require a little tweaking, but should work.

We wanted to stop cross-compiling in aspnet/EntityFramework#4578. When doing the work, I failed to realize that just because our dependencies cross-compile doesn't mean that we have to.

**Comment by pranavkm** [comment]
> When doing the work, I failed to realize that just because our dependencies cross-compile doesn't mean that we have to.

How does that work?

**Comment by bricelam** [comment]
If the identities of types are the same between frameworks, it doesn't really matter which one you're compiled against. It's the classic bait-and-switch model.

**Comment by pranavkm** [comment]
Spoke to @bricelam and we decided there wasn't anything we needed to at this stage.
