### ISSUE TITLE
Rebase xunit fork on latest upstream, and send xunit a PR for the latest relevant changes

### ISSUE THREAD

**Issue by Eilon** [aspnet/Universe#316]
The fork at https://github.com/aspnet/aspnet.xunit is both behind and ahead of the upstream branch.

We need to rebase the fork to the latest upstream, then send a PR with any relevant changes that we have in the fork.

@davidfowl @pakrym FYI

**Comment by dougbu** [comment]
First part ends at aspnet/aspnet.xunit@4f8591e

**Comment by dougbu** [comment]
Upstream change proposal in xunit/dnx.xunit#62 but it can't go forward 'til we update vnext feed.

**Comment by dougbu** [comment]
xunit/dnx.xunit#62 is now in.
