### ISSUE TITLE
Update CI configuration for dnvm repo to restore user %Path% when done

### ISSUE THREAD

**Issue by dougbu** [aspnet/Universe#319]
Looks like builds extend the `%Path%` value forever, eventually kicking out values we need. Likely culprit is builds in the dnvm repo. Other Windows builds have no reason to include `-p` when executing `dnvm` commands.

**Comment by muratg** [comment]
Is this still valid for RC2?  DNVM and DNX are being retired...

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
