### ISSUE TITLE
Reduce redundant compilation in KoreBuild

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#322]
When running a full build lifecycle, each project gets compile multiple times because we don't save the output to disk.

For example, `EntityFramework.Core` gets compiled 86 times when running KoreBuild on EF.

#### Full details:

Running `./build.cmd verify` compiles each project multiple times.

Project                  | Times Compiled
-------------------------|---
EntityFramework.Commands   | 16
EntityFramework.Commands.FunctionalTests   | 2
EntityFramework.Commands.Tests | 1
**EntityFramework.Core**   | **86**
EntityFramework.Core.FunctionalTests   | 36
EntityFramework.Core.Tests | 9
EntityFramework.CrossStore.FunctionalTests | 2
EntityFramework.InMemory   | 36
EntityFramework.InMemory.FunctionalTests   | 5
EntityFramework.InMemory.Tests | 1
EntityFramework.Microbenchmarks| 2
EntityFramework.Microbenchmarks.Core   | 5
EntityFramework.Microbenchmarks.EF6| 1
EntityFramework.MicrosoftSqlServer | 18
EntityFramework.MicrosoftSqlServer.Design  | 6
EntityFramework.MicrosoftSqlServer.Design.FunctionalTests  | 2
EntityFramework.MicrosoftSqlServer.Design.Tests| 1
EntityFramework.MicrosoftSqlServer.FunctionalTests | 6
EntityFramework.MicrosoftSqlServer.Tests   | 1
EntityFramework.Relational | 48
EntityFramework.Relational.Design  | 26
EntityFramework.Relational.Design.FunctionalTests  | 9
EntityFramework.Relational.Design.Tests| 1
EntityFramework.Relational.FunctionalTests | 17
EntityFramework.Relational.Tests   | 4
EntityFramework.Sqlite | 14
EntityFramework.Sqlite.Design  | 6
EntityFramework.Sqlite.Design.FunctionalTests  | 2
EntityFramework.Sqlite.Design.Tests| 1
EntityFramework.Sqlite.FunctionalTests | 7
EntityFramework.Sqlite.Tests   | 1

Calculated by counting the times *"Information: [RoslynCompiler]: Compiled ...'* appears in [the build log](https://gist.githubusercontent.com/natemcmaster/8acd64b566429edb5173/raw/15561624adc4e7085000d08457d7aa6c2508c2b7/build.log).

**Comment by muratg** [comment]
Valid with dorkbuild too?

**Comment by natemcmaster** [comment]
Until dotnet cli supports incremental builds, dorkbuild has the same issue. @victorhurdugaci, right?

**Comment by victorhurdugaci** [comment]
Correct

**Comment by natemcmaster** [comment]
Just FYI. (this doesn't include the in-memory compilcations by dnx when we test dnxcore50, just `dotnet compile`)

Project | Times compiled by dotnet
-----------|------------------------
EntityFramework.Commands   |   12
EntityFramework.Commands.FunctionalTests   |   2
EntityFramework.Commands.Tests   |   1
**EntityFramework.Core**   |   **44**
EntityFramework.Core.FunctionalTests   |   26
EntityFramework.Core.Tests   |   9
EntityFramework.CrossStore.FunctionalTests   |   1
EntityFramework.InMemory   |   28
EntityFramework.InMemory.FunctionalTests   |   3
EntityFramework.InMemory.Tests   |   1
EntityFramework.Microbenchmarks   |   1
EntityFramework.Microbenchmarks.Core   |   3
EntityFramework.Microbenchmarks.EF6   |   1
EntityFramework.MicrosoftSqlServer   |   12
EntityFramework.MicrosoftSqlServer.Design   |   4
EntityFramework.MicrosoftSqlServer.Design.FunctionalTests   |   2
EntityFramework.MicrosoftSqlServer.Design.Tests   |   1
EntityFramework.MicrosoftSqlServer.FunctionalTests   |   5
EntityFramework.MicrosoftSqlServer.Tests   |   2
EntityFramework.Relational   |   33
EntityFramework.Relational.Design   |   18
EntityFramework.Relational.Design.FunctionalTests   |   10
EntityFramework.Relational.Design.Tests   |   4
EntityFramework.Relational.FunctionalTests   |   19
EntityFramework.Relational.Tests   |   7
EntityFramework.Sqlite   |   9
EntityFramework.Sqlite.Design   |   4
EntityFramework.Sqlite.Design.FunctionalTests   |   2
EntityFramework.Sqlite.Design.Tests   |   1
EntityFramework.Sqlite.FunctionalTests   |   5
EntityFramework.Sqlite.Tests   |   2

**Comment by muratg** [comment]
Ugh..  I'm sure other repos are similarly affected.

Is the fix in dotnet build, or do we need to make changes in dorkbuild too?

**Comment by pranavkm** [comment]
I think `dotnet build` has to support incremental compilation. Right now publishing a project for tests, results in compiling all the dependencies.

**Comment by muratg** [comment]
Looks like this is tracked.  https://github.com/dotnet/cli/issues/232 

@danroth27 this may be another bug to track in the shiproom.  Basically, our build very slow with dotnet build.

**Comment by victorhurdugaci** [comment]
With dotnet it's a known issue.

In dnx we don't have that problem. At least not if you use KoreBuild V2. It uses globbing patterns so it doesn't recompile the entire dependency chain every time. So, for DNX you can either build with a globbing pattern (e.g. `dnu build src/**/*.json`) or set `KOREBUILD_BUILD_V2` = 1 to do that during `build.cmd/.sh`

**Comment by victorhurdugaci** [comment]
Leave this bug open because I'm going to use it to track the incremental build for `KoreBuild-dotnet`

**Comment by victorhurdugaci** [comment]
Scratch that last comment. There's already an issue to track that https://github.com/aspnet/Universe/issues/338
