### ISSUE TITLE
Environment flags used during build should be checked for =="1" instead of existence

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#326]
Some build flags are set by existing https://github.com/aspnet/Universe/blob/dev/build/_k-standard-goals.shade#L361. This could be confusing since the setting the value to "0" still turns it on. We should check whether the value is "1" instead like https://github.com/aspnet/Universe/blob/dev/build/_k-standard-goals.shade#L366.

cc @victorhurdugaci

**Comment by dougbu** [comment]
Disagree since `true`, `True`, and so on would inexplicably not do the needful. What is the use case for setting an environment variable to a value that means the same thing as not setting it at all?

**Comment by JunTaoLuo** [comment]
Isn't it better to have consistency across different settings? We can even whitelist `1`, `true`, `True` as recognized settings that turns flags on but it is rather confusing that `0` would turn on the settings. In fact I already suspect that a setting in our build is accidentally turned on because of this. 

Also, right now some settings are only turned on if the value is set to `1` and some are checked for existence. We should at least make it consistent across the board.

**Comment by Eilon** [comment]
I think we often do explicitly check for `1`, `true`, and `True`, so this sounds fine. Checking existence sounds super error-prone to me.

**Comment by dougbu** [comment]
@JunTaoLuo @Eilon this is completely internal: We're talking about environment variables that are rarely used off the CI machines. So, what errors are we concerned about? Why do more than check for existence -- make that consistent?

**Comment by Eilon** [comment]
To prevent bugs in the build system. Internal or not, it's something we all use every day...

**Comment by cesarbs** [comment]
My take, as I said in https://github.com/aspnet/Universe/pull/330, is to check that something is *not* `0` or `false` and treat all else as true. However I do concede it might be overkill and just checking for `== 1` could be all we need.

**Comment by muratg** [comment]
Per @Eilon's decision, we decided to just check for 1 and true (lowercase as far as I'm concerned) and ignore everything else.

**Comment by muratg** [comment]
@victorhurdugaci Is this something we should do in dorkbuild?

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
