### ISSUE TITLE
KoreBuild-dotnet should support concurrent builds

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#338]
Because it builds the entire compilation graph everytime, there's a good chance it will hit locked files. It makes our parallel build fail... Dotnet will add support for it as part of: https://github.com/dotnet/cli/issues/383

This issue is to track that we still need to add support for this. For now I'll disable it.

**Comment by muratg** [comment]
So when the dotnet-compile support goes in, do we just need to re-enable concurrent build, or will we need to change code?

**Comment by victorhurdugaci** [comment]
Not sure yet. Depends on how they implement the support for concurrent builds

**Comment by muratg** [comment]
Cool.  Putting in RC2 for now, since the CLI change seems to be scheduled for RC2 as well.  If it goes in too late, we'll move this one to 1.0.0

**Comment by victorhurdugaci** [comment]
This is happening automatically with the latest CLI. There's no work needed on our side.
