### ISSUE TITLE
How to disable Edit and Continue??

### ISSUE THREAD

**Issue by MrAndMrsK** [aspnet/Universe#340]
When I'm working on client-side code I don't need the debugger actually engaged and I want to be able to edit my html/js/ts/css/whatever and just refresh my browser and see the updates.  But I can't edit when I'm debugging and IIS Express quits when I can edit.  In ASP.NET vBefore the first thing to do was disable Edit and Continue so that IIS Express would stay running and available.  I cannot find that option in the Project properties anymore.

Is there a way to achieve it in ASP.NET 5?

Thanks!

**Comment by muratg** [comment]
This issue was moved to aspnet/Home#1196
