### ISSUE TITLE
Remove support for named parameters from `k-generate-resx.shade`

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#342]
The designer file that we generate supports named as well as indexed parameters in resx strings. AFAIK, this is not a common practice. Additionally, EF seems to seems a different generator for their resx files, so this wouldn't affect them.

**Comment by victorhurdugaci** [comment]
@pranavkm still applicable in KoreBuild-dotnet?

**Comment by pranavkm** [comment]
`build resx` no longer works in KoreBuild-dotnet. If the plan is to switch to to VS generated resx designer files, this is no longer an issue.

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
