### ISSUE TITLE
KoreBuild DNVM does not work when user path contains white spaces

### ISSUE THREAD

**Issue by Ermesx** [aspnet/Universe#343]
I have problem with running default build script using Sake and KoreBuild.
My user profile path looks like:  `C:\Users\Wojtek Gadziński\.dnx\...`
and the command which add runtime to the PATH doesn't work when path contains white spaces
The problem is located in [`dnvm.cmd`](https://github.com/aspnet/Universe/blob/dev/KoreBuild-dotnet/build/dnvm.cmd) file.

To resolve problem I've wrap `DNVM_CMD_PATH_FILE` variable with question marks like below:
```bash
@Echo off

for /f "delims=" %%i in ('PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.IO.Path]::GetTempFileName()"') do set DNVM_CMD_PATH_FILE=%%i.cmd

PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threading.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile='%DNVM_CMD_PATH_FILE%';& '%~dp0dnvm.ps1' %*"

IF EXIST "%DNVM_CMD_PATH_FILE%" (
  CALL "%DNVM_CMD_PATH_FILE%"
  DEL "%DNVM_CMD_PATH_FILE%"
)
```

Best Regards.

**Comment by Ermesx** [comment]
The same story with KoreBuild-dotnet.

**Comment by victorhurdugaci** [comment]
`dnvm` doesn't exist anymore in `dotnet`, and we're not going to fix this bug in `KoreBuild`.

`KoreBuild-dotnet` will stop using `dnvm` very soon so this problem will go away.
