### ISSUE TITLE
Refactor build.cmd/sh to not include blocks

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#347]
Do this after the dotnet migration

**Comment by victorhurdugaci** [comment]
More details in this PR: https://github.com/aspnet/HtmlAbstractions/pull/10#discussion_r49028200

**Comment by dougbu** [comment]
Poaching this because I was looking at unexpected differences between repos. This problem has been fixed in a few but not the majority.

**Comment by dougbu** [comment]
edd1f7a and loads of commits in individual repos to match
