### ISSUE TITLE
.travis.yml should install `openssl` on OSX

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#349]
Based on https://github.com/aspnet/Razor/pull/661/files#r49520330:

We need to add a `before_install` step that installs icu4c if we're running on OSX:

```
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
```

Followed by bulk updating repos.

**Comment by victorhurdugaci** [comment]
Is it needed for every repo?

**Comment by pranavkm** [comment]
cc @dougbu

**Comment by dougbu** [comment]
@victorhurdugaci we need ICU everywhere we execute w/ .NET Core. But this issue is less about absolute requirements and more about consistency -- in this case, with the `addons` list: We should also `brew install` everything needed even if the Travis images provide something by default (for now).

**Comment by muratg** [comment]
@dougbu Are you able to take this?

**Comment by dougbu** [comment]
I can do the batch update pretty quickly but my RC2 bug backlog may mean it takes a bit for me to get to it. But I think it's fine to do in a week or so. Any objections?

**Comment by muratg** [comment]
:+1+

**Comment by Eilon** [comment]
@dougbu anything left to do here?

**Comment by dougbu** [comment]
This was always a low-pri cleanup item about consistency between our `.travis.yml` files. The inconsistency remains: EntityFramework, Mvc, and a few other repos contain `brew install icu4c` but the majority do not. So, the action remains for whenever I have a sufficiently boring hour or two.

**Comment by Eilon** [comment]
Ok, moved it out then.,

**Comment by dougbu** [comment]
Repurposed this issue to cover `openssl` installation instead. CoreFx needs that but uses the OS' ICU now.

**Comment by dougbu** [comment]
Now have a script that builds on a single template for `.travis.yml` files and handles the (inconsistent) `secure` content we use for WebHooks notifications. I'm moving through the repos that have `.travis.yml` files in three groups and have completed the first group of 16 repos. Will pause until Tuesday to allow Travis to catch up (confirming the updated files work fine) and others to comment.

Have a look at aspnet/Common#143 for the basic template. That one contains most of the changes applied. On the other hand, some of the later repos will have different changes as I apply the template.

Note that 100% consistency, even allowing for different `secure` content is _not_ the goal. Some repos for example need Python or nginx installed and both are special cases. I'm reverting some changes using the template applies in the few repos where that is necessary.

**Comment by dougbu** [comment]
All Travis builds of my branches are green. Since that happened quicker than expected, I'll open PRs for the next group of 16 repos. Not pushing anything into `dev` branches 'til Tuesday of course.

**Comment by dougbu** [comment]
All done w/ creating PRs and confirming green Travis builds. Only KestrelHttpServer is red and that's an unrelated problem.

This work was primarily about making the `.travis.yml` files more consistent across repos. The script only added `openssl` installation to OS X builds in 3 repos. OS X builds are currently disabled in one of them (EntityFramework). Travis isn't set up for the other two (Scaffolding and WebListener).

@Eilon suggest configuring Travis for the Scaffolding and WebListener repos. Or we should remove the `.travis.yml` files from both. Similarly, AppVeyor config files exist in these repos though neither is set up on the AppVeyor site.

**Comment by dougbu** [comment]
aspnet/Antiforgery@c3476cf
aspnet/BasicMiddleware@7e4c9aa
aspnet/Caching@6e39854
aspnet/Common@087c6d9
aspnet/Configuration@f27f7a7
aspnet/CORS@bfd2c36
aspnet/DataProtection@4cfdc2e
aspnet/DependencyInjection@771cb48
aspnet/Diagnostics@fa36a7b
aspnet/dotnet-watch@6eec856
aspnet/EntityFramework@1c8c510
aspnet/Entropy@71f5b25
aspnet/EventNotification@248222f
aspnet/FileSystem@f578108
aspnet/Hosting@2fe8c27
aspnet/HtmlAbstractions@c269002
aspnet/HttpAbstractions@22e5dfd
aspnet/Identity@2a03500
aspnet/JsonPatch@e72d4b4
aspnet/KestrelHttpServer@4dc2a38
aspnet/Localization@f650de8
aspnet/Logging@e40b367
aspnet/Microsoft.Data.Sqlite@f04228c
aspnet/MusicStore@3ad40ba
aspnet/Mvc@c5d7fa6
aspnet/MvcPrecompilation@b4b3513
aspnet/Options@820c58a
aspnet/Performance@3da5bbd
aspnet/PlatformAbstractions@0fb224c
aspnet/Proxy@b23e0c5
aspnet/Razor@aa3bcc3
aspnet/RazorTooling@f3240cc
aspnet/ResponseCaching@0f711ce
aspnet/Routing@2fe646c
aspnet/Scaffolding@a8ef07e
aspnet/Security@5b323e5
aspnet/ServerTests@d7936af
aspnet/Session@e77d780
aspnet/SignalR-Redis@3623aca
aspnet/SignalR-Server@626da7a
aspnet/SignalR-ServiceBus@2b6f249
aspnet/SignalR-SqlServer@fd64681
aspnet/StaticFiles@df66f51
aspnet/Testing@c74396e
aspnet/UserSecrets@b789eae
aspnet/WebSockets@4e2ecf8
