### ISSUE TITLE
git pull does not update tracking branches

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#35]
When running build, the git command specifies the branch name `git pull git@github.com:aspnet/HttpAbstractions.git dev`. This does not update the tracking branch. 
- We could remove the branch refspec to avoid this.
- We could set up the repos initially so that only the dev branch is tracked. git remote add origin git@github.com:aspnet/HttpAbstractions.git -t dev. Any consecutive fetches from origin would only fetch the dev branch

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
