### ISSUE TITLE
Add target to specify src directories to build and test directories to test

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#360]
Add additional targets that are used to specify the folders to build and test. These will be defaulted to `src` and `test` but can be overridden if required. cc @victorhurdugaci

**Comment by Eilon** [comment]
Do we actually need this? If so, where?

**Comment by victorhurdugaci** [comment]
It would simplify some builds that override the make files (e.g. DataProtection) and it would prevent bugs that we introduce when we change the builds steps in KoreBuild but forget to update every repo that overrides that step

**Comment by Eilon** [comment]
Ok, sounds lower priority then.

**Comment by JunTaoLuo** [comment]
@anurse, you might want to consider this when moving towards MSBuild. It would be useful to be able to specify what counts as a `src` or `test` project in addition to inferring it from the directory that contains them. For example, in the Performance repo, some library projects are located under different folders like `stress-test`.

**Comment by anurse** [comment]
In theory that will definitely be possible in KoreBuild 2.0. The default `makefile.proj` will set up `src` and `test` but a repo could absolutely put a `makefile.proj` in it's repo root to override that and change the definition. Good thing to note though, thanks!

**Comment by Eilon** [comment]
Closing because we don't have a clear need for this.
