### ISSUE TITLE
Copy packages from external feeds

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#362]
So far we need:

- Microsoft.DotNet.Cli.Utils
- Microsoft.DotNet.ProjectModel.Loader
- Microsoft.DotNet.ProjectModel
- The xunit runner
- The command line parser from CLI

With all their dependencies, of course

cc @bricelam @moozzyk

**Comment by moozzyk** [comment]
+ "Microsoft.DotNet.ProjectModel"

**Comment by prafullbhosale** [comment]
+ "Microsoft.DotNet.ProjectModel.Loader"
"Microsoft.DotNet.ProjectModel.Workspaces"

**Comment by pranavkm** [comment]
> The command line parser from CLI

Wouldn't that eventually end up in the CoreCLR feed?

**Comment by prafullbhosale** [comment]
@victorhurdugaci @pranavkm 
The feed seems to be missing ProjectModel.Workspaces package

**Comment by victorhurdugaci** [comment]
@prafullbhosale do you want to send a PR with the packages you need. You have to include them in this list: https://github.com/aspnet/CoreCLR/blob/dev/tools/MirrorLatestCoreCLR/Program.cs#L65-L73

**Comment by prafullbhosale** [comment]
@victorhurdugaci I don't seem to have access to CoreCLR repo.

**Comment by victorhurdugaci** [comment]
No worries, I'll add it for you. Is `ProjectModel.Workspaces` the only packages?

**Comment by prafullbhosale** [comment]
Thanks!!

Yes ProjectModel.Workspaces, but along with its dependencies: 
"Microsoft.DotNet.Compiler.Common"
"Microsoft.DotNet.Cli.Utils"
"Microsoft.DotNet.Files"

**Comment by victorhurdugaci** [comment]
Some packages are missing from the feed. https://github.com/dotnet/cli/issues/1755

**Comment by prafullbhosale** [comment]
@victorhurdugaci dotnet/cli#1755 is closed. Can you please add these packages to the aspnetcidev  feed?
