### ISSUE TITLE
Remove mono from travis.yml

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Universe#377]
With conversion to dotnet we should no longer need to install mono when running builds on travis. It adds about 2 minutes to each build.

**Comment by victorhurdugaci** [comment]
We still need it to run `dnx451` tests... Unless I'm missing something...

**Comment by moozzyk** [comment]
I thought we were running only CoreClr tests on non-Windows. If we run dnx451 then you are right and we can close this.

**Comment by victorhurdugaci** [comment]
We still run the dnx451 tests and AFAIK there's no plan to stop doing that.
