### ISSUE TITLE
Remove facade references from projects

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Universe#379]
Across the board we need to remove the facade assemblies from our projects. This includes System.Runtime and family (anything under the facades folder on .NET Framework *).

/cc @bricelam @pranavkm

**Comment by bricelam** [comment]
We can't yet. Packages like `System.Diagnostics.DiagnosticSource`, `xuint.assert` & `xunit.extensibility.core` don't follow the rules.

**Comment by davidfowl** [comment]
@bricelam Which rules are those?

**Comment by bricelam** [comment]
@davidfowl keeping PCLs under `portable-*` directories, and declaring proper dependencies for `dotnet`
