### ISSUE TITLE
Need build options to skip tests and to ignore test results

### ISSUE THREAD

**Issue by dougbu** [aspnet/Universe#38]
If the test command exists in a repo, it's not currently possible to build w/o running the tests.  Builds also fail on the first failed tests rather than reporting later test failures.

Unit tests are not always necessary for intermediate builds or when building repos you're not working on directly e.g. checking that you haven't broken them w/ local changes.  Further unit test failures should not fail an entire `build.cmd install` in Universe.

Part of this might be avoided if the install loop in makefile.shade used a try / catch block.  Of course that could cause problems building later repos.  And would still want to skip tests or ignore test failures in individual repo builds.

FYI latest Universe build failures occur because Data repo includes a couple of tests that fail.  Relying on `build.cmd install` might not be recommended but is one way to enable work while disconnected.

**Comment by muratg** [comment]
Kinda done with the recent changes.
