### ISSUE TITLE
Disable app domains for tests using custom attributes

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#381]
cc @JunTaoLuo

**Comment by natemcmaster** [comment]
Is this due to the disappearing tests on full .NET https://github.com/aspnet/Testing/issues/203? Disabling app domains doesn't always fix the problem (as in EF tests). The fix for EF is to change all tests from `dnx451` => `net451`

**Comment by JunTaoLuo** [comment]
Hmm I'll try the approach mentioned above.

**Comment by pranavkm** [comment]
:+1: to switching to net451. If you feel up to it, feel free to bulk update tests in all our repos to switch to `net451`.

**Comment by JunTaoLuo** [comment]
All repos have been checked. Some will retain dnx451 due to dependencies on test sites (but they either do not require custom test discovery or have no issues with it) and EF's update is in PR https://github.com/aspnet/EntityFramework/pull/4509.
