### ISSUE TITLE
Upgrade *nix KoreBuild.sh to use dotnet 1.0.0.1333

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Universe#384]
Currently KoreBuild.sh is set to version `1.0.0.001244` which has a badly linked `System.Net.Http.Native.so` file. **This badly linked libcurl has cert problems that break our `dotnet restore` process.** We need to upgrade to `1.0.0.1333`.

The build lab was creating this broken native binary until about a week ago. `System.Net.Http` version 23809 and later are free of this problem. This is a blocking bug.

See dotnet/corefx#6079 for more information.

**Comment by victorhurdugaci** [comment]
We plan to have a gate mechanism for the CLI and it upgrade automatically to the latest version if the gate tests pass. @ryanbrandenburg works on this

**Comment by NTaylorMullen** [comment]
I believe this is fixed now. @troydai you said that they pushed a new dotnetcli set of packages. Does this mean we have also pulled their new `dotnet` cmd?

**Comment by DavidObando** [comment]
If the issue doesn't repro anymore in the Travis boxes I'm more than happy to close this one as fixed.

**Comment by DavidObando** [comment]
The issue is resolved. We're still affected by the segmentation fault issue in Linux (exit code 139) which got resolved last week dotnet/coreclr@149bc3f. Looking forward to the gate pass @victorhurdugaci mentioned to be operational.
