### ISSUE TITLE
Remove dotnet-pack hack once we update to CLI build with https://github.com/dotnet/cli/pull/1439 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#385]
Need to undo changes made to `_dotnet-pack.shade` made as part of https://github.com/aspnet/Universe/commit/a192f799058bf81aeb43e81d2b5e820164807f05#diff-8df17aca7cb204ad57c6581948614cbbR22

**Comment by pranavkm** [comment]
CLI issue: https://github.com/dotnet/cli/issues/1366

**Comment by davidfowl** [comment]
This if fixed now right?

**Comment by pranavkm** [comment]
Yup.
