### ISSUE TITLE
Update build to mono 4.2.2

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#393]
[Mono 4.2.2](http://www.mono-project.com/docs/about-mono/releases/4.2.2/) is the latest public release (Jan 28, 2016) and includes many fixes to async, LINQ, assembly loading, and networking.  We should consider updating our build to leverage this upgrade.

In particular, this fixes the xunit runner error [(example here)](https://travis-ci.org/aspnet/Microsoft.Data.Sqlite/jobs/110528804#L1917):

```
System.TypeLoadException: Could not load type 'Xunit.Sdk.XunitTestFrameworkDiscoverer, xunit.execution.desktop, Version=2.1.0.3179, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.
```
- [ ] Update travis.yml
- [ ] Update internal CI agents
- [ ] Investigate our use of `FrameworkSkipCondition` to see which tests now pass on Mono. (e.g. many EF tests fail on 4.0.x but pass on 4.2.2.)
- [ ] Check to see if our tests regress after upgrading (e.g. MVC)

**Comment by dougbu** [comment]
Suggest adding a bullet to execute tests in the MVC repo prior to getting too far along on this. We have a few issues with Mono builds after 4.0.x in that repo, even after getting past issues such as aspnet/External#48. aspnet/External#32 is one example and we never debugged that action selection issue deeply enough to report a useful bug to Xamarin (https://bugzilla.xamarin.com/show_bug.cgi?id=33468 is rather content-challenged).

**Comment by natemcmaster** [comment]
Mono 4.2.2 + nuget.exe continues to have lingering networking issues "Invalid chucked data" errors. We may not need to worry once we switch to dotnet-do

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
