### ISSUE TITLE
Consider caching nuget and dotnet to speed up AppVeyor/Travis

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#394]
`dotnet restore` can take >5min of CI time for big projects such as EF. AppVeyor and Travis support caching from build to build. We should consider leveraging this to improve the CI speed by caching NuGet packages.
- https://www.appveyor.com/docs/build-cache
- https://docs.travis-ci.com/user/caching/

Important considerations: 
- how to automate cleaning bad caches
- PR's can add to cache as well. We need to ensure this won't corrupt regular builds.

**Comment by muratg** [comment]
@victorhurdugaci do we have this now?

**Comment by victorhurdugaci** [comment]
Nope. We can look into this but it's pretty dangerous IMO. The best results are when the environment in clean and completely separated from the previous runs.

**Comment by victorhurdugaci** [comment]
I think the caches make sense for things that don't change, not for packages. Maybe (just maybe!) we could cache the latest coherence

**Comment by natemcmaster** [comment]
> We can look into this but it's pretty dangerous IMO.

We can mitigate the danger. Travis and AppVeyor have hooks for after a failed build. We could delete the package cache anytime a build fails. Furthermore, we can isolate PRs from caching. Both Travis and AppVeyor set different env variables when the build is for a PR. We could use this to put downloaded packages in a non-cached location.

**Comment by muratg** [comment]
Should this be in KoreBuild repo now?

**Comment by muratg** [comment]
Let's reconsider post RC2.

**Comment by Eilon** [comment]
@natemcmaster is this something we continue to see as being a problem?

**Comment by natemcmaster** [comment]
Caching NuGet may not be worth the headaches of clearing bad caches, but we should definitely look into building in a Mono-less environment once we port our build system. Installing Mono accounts for a minute of the build startup time.

Also, looking to the future, Travis supports specifying the version of dotnet-CLI in the .travis.yml file. See https://docs.travis-ci.com/user/languages/csharp/#Choosing-runtime-and-version-to-test-against

**Comment by natemcmaster** [comment]
Closing. Not worth the effort.
