### ISSUE TITLE
dotnet test skipped for dnxcore50 tests

### ISSUE THREAD

**Issue by tushargupta51** [aspnet/Universe#400]
This started happening because of a recent change in _k-standard-goals.shade, specifically here:

https://github.com/aspnet/Universe/blob/dev/KoreBuild-dotnet/build/_k-standard-goals.shade#L196

The assumption here is that dotnet-test-xunit is listed in every project.json that has dnxcore50 tests. But that is not true. For example. Microsoft.IdentityModel.Logging.Tests (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/test/Microsoft.IdentityModel.Logging.Tests/project.json) depends on Microsoft.IdentityModel.Tokens.Tests. MS.IM.Tokens.Tests has "dotnet-test-xunit" listed as a dependency but MS.IM.Logging does not since that gets pulled by MS.IM.Tokens.Tests automatically.

I think we should look for "dnxcore50" target and if no commands are specified (which means not running on dnx), we should run "dotnet-test" command.

**Comment by tushargupta51** [comment]
@pranavkm

**Comment by pranavkm** [comment]
The plan's to remove the conditional check once Mvc uses the cli to run tests. Should be soon.

**Comment by tushargupta51** [comment]
@pranavkm thanks :)
