### ISSUE TITLE
Determine a way to specify that a project should not execute tests in parallel

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#407]
We currently have a mechanism where specifying an environment variable would cause KoreBuild to specify `-parallel none` flag to runner. The environment variable is defined in several different places - the CI build configuration, in .travis.yml and in build.cmd \ build.sh. 

1. Customizing build.cmd \ build.sh causes issues makes it harder to bulk update these files (and might go away entirely with @victorhurdugaci's work).
2. Specifying it in the CI \ config files is a bad idea since we run it into issues with parallelism in local builds.

It would be nice for the embed this information in a per project basis and have the runners somehow figure this out so that `dotnet run` would flow it through.

**Comment by muratg** [comment]
I assume this one's no longer valid anymore. Closing. :)

**Comment by pranavkm** [comment]
We still need this. There are a couple of tests (like ServerTests) that I think don't work in parallel.

**Comment by pranavkm** [comment]
Oh nevermind. The KoreBuild one should take care of tracking the actual issue.
