### ISSUE TITLE
cli always downloaded on Mac 

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Universe#409]
Looks like there is something wrong with the logic that checks if dotnet cli should be installed on Mac when running build.sh:

This is what's on the box:
```
cat /Users/###/.dotnet/share/dotnet/cli/.version
6aeed1f52d73ffa8bb01229e4638fe3d8250b9e7
1.0.0.001540
```
This is supposedly the latest version on the server:

``` 
curl -s https://dotnetcli.blob.core.windows.net/dotnet/beta/dnvm/latest.osx.version
14e8b184bd9e0835ae9d7b6b8f0149b499712abf
1.0.0.001573
```

Because of the mismatch the build script downloads the latest runtime but it's the one that is already installed:

```
dotnet_install: Preparing to install .NET Tools from 'beta' channel to '/Users/###/.dotnet'
dotnet_install: Latest Version: 1.0.0.001573
dotnet_install: Local Version: 1.0.0.001540
dotnet_install: Downloading dotnet-osx-x64.1.0.0.001540.tar.gz from https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.001540
```

**Comment by victorhurdugaci** [comment]
Interesting... This is bug for github.com/dotnet/cli because we get the scripts from there

**Comment by muratg** [comment]
@moozzyk could you file a bug on dotnet/cli and close?

**Comment by moozzyk** [comment]
I actually think the bug is in our [script](https://github.com/aspnet/KoreBuild/blob/dev/build/dotnet/install.sh#L178-L191). We pin the build and then compare local hash with the latest and then download the pinned build.

**Comment by victorhurdugaci** [comment]
Those scripts are a copy of https://github.com/dotnet/cli/tree/rel/1.0.0/scripts/obtain

**Comment by moozzyk** [comment]
I see - I did not know.

**Comment by moozzyk** [comment]
Created a bug in cli repo https://github.com/dotnet/cli/issues/1628 and sent a PR with a fix.
