### ISSUE TITLE
Create a master-docs branch as part of creating master branch

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#415]
We'll use this for ongoing API doc changes once we've branched master. We need to figure out a way to merge any doc changes made in this branch back into dev.

cc @danroth27

**Comment by muratg** [comment]
KoreBuild repo?

**Comment by muratg** [comment]
Let's consider post RC2.

**Comment by Eilon** [comment]
Haven't seen a need for this resurface, so closing for now.

cc @Rick-Anderson @danroth27 in case there are objections.
