### ISSUE TITLE
Centralize environment variable reading

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#419]
If we use any environment variable in our scripts we should read it in a single place and store it in a variables. Also, reading all variables should be the first thing that the script does when it starts and it should print **all** the variables it uses + their value.

Things like `GetEnvironmentVariable` or `E()` should not appear anywhere in the script other than this central place that creates c# variables from environment variables.

**Comment by muratg** [comment]
KoreBuild repo?

**Comment by muratg** [comment]
Let's consider post RC2.

**Comment by Eilon** [comment]
Closing because we don't have a clear need for this.
