### ISSUE TITLE
Tag the Setup repo along with other repos as part of creating master branch

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#446]
We don't have Setup in the set of repos that we branch as part of our scripts. We should add it to the list.

cc @joeloff

**Comment by joeloff** [comment]
Last commit for RC2 for Setup's release branch was https://github.com/aspnet/Setup/commit/d6ebb6946cf615217d83fc6c6e8e65ed393438fc

**Comment by muratg** [comment]
Done?

**Comment by pranavkm** [comment]
Yeah. We can figure out what the story for these repos is with MorkBuild 2.0.
