### ISSUE TITLE
Use SQL Server on Travis CI

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#450]
The SQL Server for Linux preview is available as a docker image. Assuming we can setup Travis to protect our access key to the private preview, we could use docker on Travis CI builds to execute against tests SQL Server.

https://www.microsoft.com/en-us/server-cloud/sql-server-on-linux.aspx

https://docs.travis-ci.com/user/docker/

**Comment by photodude** [comment]
Have you actually proceeded in trying to accomplish this task? I would love to try to implement this kind of change in other projects I work with so those projects can have CI testing of all of their database code/drivers.

**Comment by natemcmaster** [comment]
@photodude I had it working at one point, but reverted the implementation. Travis agent's were too slow. Checkout https://docs.travis-ci.com/user/docker/ for a guide on setting up docker with Travis and https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-docker for a guide on setting up SQL Server in docker.

**Comment by photodude** [comment]
I totally can see that. Especially since things like docker images end up not being run on the travis container infrastructure. 

AppVoyer might be an option to consider for this kind of CI testing appveyor.com

**Comment by natemcmaster** [comment]
Closing as this is something we're probably not going to invest effort in.

**Comment by photodude** [comment]
@natemcmaster AppVoyer has been a successful solution for MSSQL testing for us.

**Comment by natemcmaster** [comment]
Yeah, same here. We use AppVeyor in our repos that need SQL Server.

**Comment by natemcmaster** [comment]
Btw, decided to revisit this for EF. https://github.com/aspnet/EntityFramework/pull/7842. It doesn't take too much to enable SQL Server on Travis now.
