### ISSUE TITLE
Remove release and master branches from repositories

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#470]
We no longer use the `release` branch and `master` branch hasn't been updated since the 1.0.0 release. Instead, branches or tags with the `rel/` prefix track releases for a repository. The plan is to delete the `release` and `master` branches since they are superfluous. 

## Status

* [x] Antiforgery
* [x] AzureIntegration
* [x] BasicMiddleware
* [x] BrowserLink
* [x] Caching
* [x] Common
* [x] Configuration
* [x] CORS
* [x] DataProtection
* [x] DependencyInjection
* [x] Diagnostics
* [x] DotNetTools
* [x] EntityFramework
* [x] EventNotification
* [x] FileSystem
* [x] Hosting
* [x] HtmlAbstractions
* [x] HttpAbstractions
* [x] HttpSysServer
* [x] Identity
* [x] IISIntegration
* [x] JavaScriptServices
* [x] JsonPatch
* [x] KestrelHttpServer
* [x] Localization
* [x] Logging
* [x] MetaPackages < Unmerged master branch
* [x] Microsoft.Data.Sqlite
* [x] MusicStore
* [x] Mvc
* [x] MvcPrecompilation
* [x] Options
* [x] Proxy
* [x] Razor
* [x] ResponseCaching
* [x] Routing
* [x] Scaffolding
* [x] Security
* [x] ServerTests
* [x] Session
* [x] SignalR
* [x] StaticFiles
* [x] Testing
* [x] WebSockets

## Non-product repo
* [x] Home
* [x] Universe
* [x] Coherence
* [x] Coherence-Signed
* [x] Entropy

**Comment by natemcmaster** [comment]
Has using `master` + tags per release been considered as an alternative? This is more convention git. cc @muratg

**Comment by muratg** [comment]
@Eilon did we talk about this previously in one of the engineering discussions? What was the decision?

**Comment by Eilon** [comment]
@muratg no we need to triage this.

**Comment by Eilon** [comment]
Naah.

**Comment by pranavkm** [comment]
Could we do this? Just avoids people sending PRs to master branches ever so often.

**Comment by Eilon** [comment]
Yes it's tracked here: https://github.com/aspnet/Coherence-Signed/issues/651

@muratg will write a Python script that will "solve all our problems" 😄

**Comment by pranavkm** [comment]
Spoke to @Eilon offline. For the list of repos in Universe, I'll do a manual check to ensure that `master` and `release` branches aren't pointing to anything useful (they're most likely set to the 1.0.0 tag). If so, I'll remove it. I'll work with individual repo contacts in the event these branches are pointing to something different.

**Comment by pranavkm** [comment]
A couple of repos have unmerged branches. Pinging owners to determine if they need be persisted or if we could delete them:

@Tratcher HttpSysServer - https://github.com/aspnet/HttpSysServer/tree/release/
@SteveSandersonMS - https://github.com/aspnet/JavaScriptServices/tree/master/
@muratg - https://github.com/aspnet/ResponseCaching/tree/master
@BrennanConroy  - https://github.com/aspnet/SignalR/tree/master

**Comment by BrennanConroy** [comment]
Gone

**Comment by muratg** [comment]
@pranavkm Assign back to me for further clean-up. (Mainly for the rando branches folks have checked in and not touched.)

**Comment by pranavkm** [comment]
All yours. We can sort out JavaScriptServices tomorrow.

**Comment by SteveSandersonMS** [comment]
Have removed JavaScriptServices/master.

**Comment by Eilon** [comment]
Can also just rename them if you want to be super safe. Rename `master` to `stale/master`, etc. Then at least it shouldn't confuse anyone.

**Comment by muratg** [comment]
Sounds good, will do!

**Comment by muratg** [comment]
Done with Release/Master.
