### ISSUE TITLE
Build for non-contributors

### ISSUE THREAD

**Issue by Maxim-Kornilov** [aspnet/Universe#473]
How can I build this if I am not a contributor? Clearly, my key will not work. Maybe I do not understand something?
```
PS D:\ASPNETCore\Universe> .\build.ps1
...
info:   program: cmd
info:   commandline: /C git clone --quiet git@github.com:aspnet/MetaPackages.git --branch dev
info:   workingdir:
Enter passphrase for key '/c/Users/Maxim/.ssh/id_rsa': Enter passphrase for key '/c/Users/Maxim/.ssh/id_rsa':
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

[build_log.txt](https://github.com/aspnet/Universe/files/746020/build_log.txt)

**Comment by pranavkm** [comment]
Is there a specific repository you're trying to contribute to? You could just clone that instead of building Universe. This repository has evolved to primarily be our build orchestrator and less of an entry point for contributors.

Also the error you're seeing is because you might not have an SSH key registered with GitHub. You could clone Universe over https and that should generally avoid this issue.

**Comment by Maxim-Kornilov** [comment]
For now I just want to run the entire ASP.NET from source code.
I cloned it over https and it failed to clone only these three repositories:
```
warn: Unable to clone repository at 'https://github.com/aspnet/Coherence-Signed.git': Exit code 128 from cmd
warn: Unable to clone repository at 'https://github.com/aspnet/CoreCLR.git': Exit code 128 from cmd
warn: Unable to clone repository at 'https://github.com/aspnet/BrowserLink.git': Exit code 128 from cmd
```
But then I got:
```
    Updating CLI to 1.0.0-preview2-003118
fail: Exit code 1 from cmd
fail: Stack trace:
   at View55f0ea5e6bda489188eaa9df72b62c3a.GitCommand(String gitFolder, String gitCommand) at c:\Users\Maxim\AppData\Local\Temp\240a040640e94f5b8c2197e71bd9af
7f-1.cs:строка 2283
   at View55f0ea5e6bda489188eaa9df72b62c3a.<RenderViewLevel0>b__68() at c:\Users\Maxim\AppData\Local\Temp\240a040640e94f5b8c2197e71bd9af7f-1.cs:строка 4822
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```
I guess I just join all repositories that I need with global.json and try to build it inside VS.

**Comment by pranavkm** [comment]
The 3 repos that failed to clone are private ones, so those warnings are expected. I'm not sure what's causing the exit code, perhaps something further up in the log is failing.
