### ISSUE TITLE
Change versions to 2.0.0-preview1

### ISSUE THREAD

**Issue by Eilon** [aspnet/Universe#476]
Need to:

1. Change all the NuGet packages (tools, runtime, etc.) to be `2.0.0-preview1-XYZ`
2. Need to update milestones in GitHub repos for issue tracking to rename `2.0.0` to `2.0.0-preview1`.

cc @DamianEdwards @davidfowl @ajcvickers @muratg

**Comment by natemcmaster** [comment]
This should be pretty easy to do now. Most of our repos will only need a change in two places, version.props and build/dependencies.props.

Are there any exclusions to what should be 2.0.0? e.g. SignalR, ResponseCompression middleware, etc. I'm thinking of things not currently building as "1.2.0".
