### ISSUE TITLE
Building Universe as one big project sometimes OOMs

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#481]
@pakrym investigated this (🥇) and launching inner build as an MSBuild target as opposed to launching `build.[ps1|sh]` causes the process to OOM. Setting `UnloadProjectsOnCompletion` on the build tasks might be an option.

**Comment by pranavkm** [comment]
cc @davidfowl

**Comment by davidfowl** [comment]
😄

**Comment by pranavkm** [comment]
😦 doesn't seem to help a lot. Here's a snapshot from building locally - this is about when it's trying to build DataProtection and EF, so about 60% of the way there and it keeps growing:

![image](https://cloud.githubusercontent.com/assets/174281/23783581/770c4100-0511-11e7-9a93-f8e01017eaba.png)

I'm going to switch Universe and CoreCLR to execing `build` instead. I think it's a safer option.

**Comment by pranavkm** [comment]
Still later:

![image](https://cloud.githubusercontent.com/assets/174281/23783842/51566754-0513-11e7-8fd1-b47c1821bf66.png)

**Comment by davidfowl** [comment]
:\

**Comment by pranavkm** [comment]
Much saner with the alternative:

![image](https://cloud.githubusercontent.com/assets/174281/23796401/9c8b7e94-054f-11e7-8ae8-08ccafdd8840.png)

**Comment by davidfowl** [comment]
How much slower?

**Comment by pranavkm** [comment]
It's faster by 5 minutes. Less thrashing of the page file I suppose.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Universe/commit/df66022ff8f0cc6da4c637dd6c46674063c2ed31
