### ISSUE TITLE
Question: How does the ASP.NET team measure code coverage?

### ISSUE THREAD

**Issue by kimbell** [aspnet/Universe#484]
For the last couple of years I've become more and more interested in code coverage. It's become sort of professional gamification; level up and get to the next boss fight. 

With the release of VS2017, Code coverage for .NET Core based projects seems to be lacking at the moment, and third party solutions such as Resharper don't provide an alternative yet. 

I posed the same question to the corefx repo, and was pointed in the direction of OpenCover. Looking at the csproj files of that repo, it looks like they are pre-2017. Since you guys have now updated to 2017, you are in the same boat as the rest of us. 

Have you figured out a way do code coverage? Any tricks or hacks you can share?

**Comment by pranavkm** [comment]
We don't have a formalized process for running code coverage. I can't speak for the remainder of the subteams inside Asp.NET / EF, but the Mvc team specifically hasn't focused much on code coverage as a a measure for determining what unit tests and how many to write. 

@Eilon does the engineering team have any thoughts on this?

**Comment by kimbell** [comment]
FYI

[Resharper blog about their issues](https://blog.jetbrains.com/dotnet/2017/02/21/resharper-net-core-unit-testing/)

[Live unit testing](https://blogs.msdn.microsoft.com/visualstudio/2017/03/09/live-unit-testing-in-visual-studio-2017-enterprise/)
Live unit testing isn't supported for .NET Core, Se FAQ at the end of the post. I imagine this uses some of the same infrastructure as code coverage. 

[Community question on code coverage](https://developercommunity.visualstudio.com/content/problem/21341/not-able-to-get-code-coverage-result-of-netcoreapp.html)
This has a reply from the VS team about missing support.

**Comment by Eilon** [comment]
Yeah code coverage just hasn't been a priority for us. We looked into it a bit a while ago (1+ years ago) and there weren't great options for us. I would imagine things are better these days, but we haven't looked deeply into it.

**Comment by kimbell** [comment]
Well, it looks like things have temporarily taken a turn for the worse. With the updating feature of Visual Studio, hopefully it won't take that long until this becomes available.

**Comment by Eilon** [comment]
Closing because we still don't run code coverage tools and don't plan to at this time.
