### ISSUE TITLE
Skip SignalR when net46 is not available

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#486]
Some of our downstream machines, Win8 for example, doesn't have net46 framework assemblies so we need to skip building and testing some of our repos that use that tfm on those platforms.

The proposal is to check the environment variable env.TEAMCITY_BUILDCONF_NAME in MSBuild and then determine whether to build or not. Would this be the best approach?

cc @natemcmaster

**Comment by pranavkm** [comment]
> Win8 for example, doesn't have net46 framework assemblies

Is that fixable? I think VS 2017 installs just fine on that platform.

**Comment by JunTaoLuo** [comment]
Just checked, yea seems like we can install for that platform. Though I think there is one specific configuration that we don't want to do that:  Win2012-NET452-Universe

**Comment by natemcmaster** [comment]
We plan to drop that net452 machine altogether. Just skip SignalR tests on that machine.

**Comment by Eilon** [comment]
Once we do https://github.com/aspnet/KoreBuild/issues/211, we should be able to build on all platforms no matter what. But of course you won't be able to *run* tests without having the right .NET FX installed.

**Comment by JunTaoLuo** [comment]
This issue can be closed, we have removed the NET452 configuration and installed VS2017 (which includes net461) on all other configurations.
