### ISSUE TITLE
Support incremental `BuildRepositories` runs

### ISSUE THREAD

**Issue by dougbu** [aspnet/Universe#495]
Currently `KOREBUILD_REPOSITORY_EXCLUDE` and `KOREBUILD_REPOSITORY_INCLUDE` affect cloning. However, `BuildRepositories` builds every repo in the `.r` folder. The root cause is the inner `BuildRepositories` target (in `RepositoryBuild.targets`) builds everything in the `BuildGraph.proj` file and that file lists every cloned repo. Fix is probably passing the narrowed `@(Repository)` items to that target.

Aim here is to support multiple `.\build.cmd /t:BuildRepositories` commands, fixing problems and updating one of the `KOREBUILD_REPOSITORY_*` environment variables as you go.

Side note: `_GenerateBuildGraph` rebuilds `BuildGraph.proj` in every build. This is not necessary because the graph cannot change once the repos are cloned.

**Comment by natemcmaster** [comment]
+💯 . The `/p:BuildGraphOf=HttpAbstractions` property helps a little, but it would be great for the inner dev loop if I didn't have to recompile the world if it can be avoided.

**Comment by Eilon** [comment]
Closing this because https://github.com/aspnet/Universe/issues/512 covers it all.
