### ISSUE TITLE
Update appveyor env vars to skip dotnet first run and telemetry

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#498]
Most of our appveyor runs don't set these variables. They may speed up the build.

DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
DOTNET_CLI_TELEMETRY_OPTOUT=1

cc @pranavkm

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Coherence-Signed/issues/415.
