### ISSUE TITLE
Use EditorConfig consistently

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#500]
EditorConfig has trickled into a few repos, but with some inconsistency. We should be consistent in our settings and investigate carefully what we want those settings to be.

**Goals:**
- use the same settings across all repos
- set Roslyn settings so that anyone with non-default VS formatting settings can still work on our code

**Resources:**
Compiler and VS do not yet enforce editorconfig. See progress here: https://github.com/dotnet/roslyn/projects/4
Docs for editorconfig + roslyn https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference

**Examples:** 
https://github.com/aspnet/DotNetTools/blob/f246dd3502b1e2aa976e8b8d668f1d5c5e79f96b/.editorconfig
https://github.com/aspnet/Razor/blob/5928d0d54b9b48bc60001f50b8bd68d84435323f/.editorconfig
https://github.com/aspnet/Mvc/blob/824d65ca3d6da81864c24350d6fb0d612a9c1d31/.editorconfig
https://github.com/aspnet/IISIntegration/blob/afb327ae02c4d48d26b9327ae8354a8fbf999523/.editorconfig
https://github.com/aspnet/SignalR/commit/76174580fd79c2f06289aff177203c97ae292ed0

cc @anurse @davidfowl @pranavkm

**Comment by pranavkm** [comment]
There was an engineering discussion about this. We were using Razor and Mvc as a test ground to see if what we have now helps. @rynowak \ @NTaylorMullen maybe you might have some inputs on if you found the settings to be intrusive in any way. If not, we could use the one in Razor \ Mvc as a template.

**Comment by rynowak** [comment]
I didn't notice much. It wasn't intrusive, but I didn't notice anything positive that it did because I already do things the right way.

**Comment by anurse** [comment]
I definitely think it would be good to set up one EC file. I think we should start simple and build up, since Code Style enforcement isn't quite there in Roslyn/VS yet. I had a really detailed one here: https://github.com/aspnet/SignalR/commit/76174580fd79c2f06289aff177203c97ae292ed0 but I think we'd need to have a larger discussion about style before going to that level.

Also, I kinda want to just leave it to things that VS/`csc` actually check so we don't suddenly get a bunch of warnings/suggestions/etc. when things turn on.

**Comment by NTaylorMullen** [comment]
Assuming the EC didn't get in the way of normal work behavior it'd be very useful. Just like @rynowak I haven't noticed any difference in Razor. At the very least it'd make it more likely that a contribution is easy to consume.

**Comment by pranavkm** [comment]
@anurse looking at the file you have - we had a discussion with the engineering team and decided we did not want any of the enforcements to be either a warning or an error. The intent is for the config to be guidance rather than enforcement.

**Comment by anurse** [comment]
Fine with me. The file was mostly a listing of the style rules I was aware of. We already have a significant lack of documentation of style rules (the list on the Home wiki is super out-of-date), so anything we can add will be much better than our current system of just assuming people know what to do :).

**Comment by Eilon** [comment]
I think contributors in general have been doing a good job with these things so I don't feel the value is there.

**Comment by pranavkm** [comment]
@Eilon can we copy the settings file we're using in Razor \ Mvc across repos - https://github.com/aspnet/Mvc/blob/dev/.editorconfig? We can make it a bit more opinionated about using certain features (along the lines of Roslyn's .editorconfig)?

That said, I actually find value in having errors for features I'd like to use and that's how I have it set up on my local VS instance. It can be a bit distracting, but results in some formidable amounts of 💯 points (See https://github.com/aspnet/JsonPatch/pull/100/files#diff-1af7353f2198d455625eced2048f3fc0).

**Comment by smitpatel** [comment]
What IDE or tools support the EditorConfig at present?

**Comment by pranavkm** [comment]
@smitpatel VS and VS Code support it out of the box.

**Comment by smitpatel** [comment]
In EF team, most of us use R# to enforce coding guidelines.

**Comment by Eilon** [comment]
I just don't think we've seen this being a big enough problem in the last several months. Even that JsonPatch PR it's a matter of personal preference that we wouldn't enforce one way or another.

**Comment by davidfowl** [comment]
Whats the downside though? Seems like all upside

**Comment by anurse** [comment]
It's worth it just to ensure my indentation settings are always right :)

**Comment by anurse** [comment]
Also: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#a-nameusingsorganize-usingsa

**Comment by Eilon** [comment]
It's work that we'll end up arguing over the details on, it'll take time, and not provide much value.
