### ISSUE TITLE
200k+ lines of output overwhelm TC and browser

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#501]
Our universe build on TC produces so much output that viewing the build log can cause the browser to crash. They are also really hard to sift through as error messages are produced to stdout, not stderr.

**Stats:**
Raw log files can be >= 60 MB.
The latest (failed) run of tests on macOS agents produce 234,871 lines before dying.

We should look into reducing the logged output to make it more manageable.

Some ideas that may help:

- Disable xunit's auto reporter: https://github.com/xunit/xunit/issues/1191
- Create our own logger that is smarter about what it produces: https://github.com/aspnet/KoreBuild/issues/183
 - Reduce the console verbosity of the tools in this repo (e.g. BuildGraph) and log to a file instead.

**Comment by ryanbrandenburg** [comment]
I filed https://github.com/aspnet/Hosting/issues/1087, which at a quick glance seems to account for ~50% of the output in Universe.

The size of these logs is making teamcity backups unwieldy (currently take over an hour to produce, the vast majority of that being logs) Not to mention it makes each TC backup ~9GB, which seems like it will get expensive to keep around fast.

**Comment by smitpatel** [comment]
> Disable xunit's auto reporter: xunit/xunit#1191

That issue is resolved already in 2.3-beta2 package of xunit we use. We should disable the auto-reporter.

**Comment by natemcmaster** [comment]
The auto reporter is already disabled on aspnetci :) https://github.com/aspnet/KoreBuild/pull/230

**Comment by Eilon** [comment]
Apparently the new TeamCity is better at this by not expanding huge logs by default. So closing.
