### ISSUE TITLE
When building in Universe repo.targets of inidividual repos is not getting used

### ISSUE THREAD

**Issue by kichalla** [aspnet/Universe#507]
**Repro steps:**
- Clone universe in rel/2.0.0-preview1 branch
- set environment variable to be `KOREBUILD_REPOSITORY_INCLUDE="MusicStore"`
- build.cmd /p:compileonly=true
- open up the generated msbuild.log file and look for target called `_FilterTestProjects` (which is the one defined in MusicStore repo's repo.targets file)

**Expected:**
Able to find the target _FilterTestProjects in build log (indicating that the repo.targets file is being used)

**Actual**
Cannnot find the target in the build log

cc @natemcmaster

**Comment by pranavkm** [comment]
We call build.cmd on individual repos. Look for the target in `.r\MusicStore\artifacts\msbuild\msbuild.log`.

**Comment by kichalla** [comment]
Thanks @pranavkm , I was looking at the wrong place! Closing this issue now
