### ISSUE TITLE
Presist runtime information in Coherence builds

### ISSUE THREAD

**Issue by joeloff** [aspnet/Universe#511]
Setup repos need to know the URL for the runtime to ensure we have matching bits that line up. E.g., the server host bundle pulls in the package store MSIs, runtime and ANCM. The runtime we pull in needs to exactly match what the coherence build depended on. For the setup repos, we only maintain URLs for the runtime installers, we redist, e.g. 

https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0-preview2-25317-03/dotnet-win-x86.2.0.0-preview2-25317-03.exe
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0-preview2-25317-03/dotnet-win-x64.2.0.0-preview2-25317-03.exe

Coherence builds used to provide the runtime version information. Right now the process is manual - lots of emails, etc. to ensure we're in sync and it often requires making additional builds before everything lines up.

**Comment by Eilon** [comment]
@joeloff we believe the builds now drop version files for each build so this is done. Can you confirm? If not done, please provide additional details.

**Comment by joeloff** [comment]
I think we're good. We get the information from the additional deps in the package store. For 1.x patches the process is still manual, but that's fine as we typically build the bundles for those ones or twice. My concern was more with things like the active dev/release where we want as much of the build automated
