### ISSUE TITLE
ApiCheck: Update baseline to 2.0

### ISSUE THREAD

**Issue by smitpatel** [aspnet/Universe#524]
As we are nearing to 2.0-RTM release, we need to update our baselines to v2.0.0.
There are 2 options to do it,
- Last commit in 2.0 release is updating the baseline.
- We update baselines while creating final tag for 2.0 release

**Comment by smitpatel** [comment]
This has been done for EntityFrameworkCore & Microsoft.Data.Sqlite repos.

**Comment by Eilon** [comment]
@smitpatel - did you do it "manually" or did you have some kind of script that makes it easier to run on multiple repos?

**Comment by smitpatel** [comment]
I did it manually since there were not many projects to update.

**Comment by Eilon** [comment]
@javiercn - since @ryanbrandenburg is going to be OOF, can you take a stab at this? We need to get this in ASAP to avoid accidental breaking changes in 2.1.

**Comment by javiercn** [comment]
@Eilon We did this for repos with high traffic (MVC, EF, Hosting, Kestrel, etc), but we should finish doing it for the rest of the repos. We need to re-enable the generation behavior from the build script. When we had sake we could run the generation from build.cmd but I think this functionality wasn't completely migrated to MSBuild. Is this correct @ryanbrandenburg or am I missing something? Last time I checked you were doing things in this area. We should have generation ability from build.cmd (with a task or something like that e.g build.cmd /t:UpdateBaselines (or GenerateBaselines) or similar). @ryanbrandenburg can you take over the remaining work here? (Reenable generation from build.cmd and run it on 2.0 for the remaining repos)

**Comment by Eilon** [comment]
Yes definitely let's finish this up.

**Comment by Eilon** [comment]
@javiercn is there work left to do here? Whatever is remaining we need to finish in preview2.

**Comment by Eilon** [comment]
Load balancing to @ryanbrandenburg . Please make sure changes are reviewed by @natemcmaster and @javiercn .

**Comment by ryanbrandenburg** [comment]
So, just to be clear here, we need to create baselines based on our latest 2.0.X release, and commit them to dev, correct?

**Comment by Eilon** [comment]
Yes

**Comment by ryanbrandenburg** [comment]
[Here's](https://github.com/aspnet/Security/pull/1697/files) one of the PR's I created. The full list can be found [here](https://github.com/search?q=org%3Aaspnet+author%3Aryanbrandenburg+is%3Apr+is%3Aopen). I assume we can have @javiercn just spot-check these, then merge as they pass?

**Comment by ryanbrandenburg** [comment]
Those PR's that remain are awaiting review by either the area "owner" or @Eilon.
