### ISSUE TITLE
Remove common prefixes from project paths/csproj names to avoid MAX_PATH issues

### ISSUE THREAD

**Issue by anurse** [aspnet/Universe#531]
We're hitting issues with paths being too long during our build. There are some redundant parts in our paths and project names that we can remove to reduce this.

* We should remove the `Microsoft.Extensions` prefix from all Project Directory names and `csproj` file names. For example: `Options/src/Microsoft.Extensions.Options.ConfigurationExtensions/Microsoft.Extensions.Options.ConfigurationExtensions.csproj` becomes `Options/src/Options.ConfigurationExtensions/Options.ConfigurationExtensions.csproj`
* Ditto`Microsoft.AspNetCore`: `KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.csproj` becomes `KestrelHttpServer/src/Server.Kestrel.Transport.Sockets/Server.Kestrel.Transport.Sockets.csproj`
  * Note that in this example, `Server.Kestrel.` could probably be eliminated too, since all projects in that repo start with it. However, I think it's good if we're consistent about which prefixes we eliminate for now and if we still hit path issues, we can get more aggressive
  * **Open Question**: There were repos (not sure if there still are) where there is a `Microsoft.Extensions.Foo` and a `Microsoft.AspNetCore.Foo`. For those, we would have to keep the second segment in place: `Extensions.Foo` and `AspNetCore.Foo`. Is this weird? Are we OK with that?
* Package IDs, Assembly Names, Root Namespaces (in MSBuild), etc. must be **unaffected** by this change (obviously)

**Comment by smitpatel** [comment]
Just for info. EF converted `Microsoft.EntityFrameworkCore` to EFCore a long time ago. It removed longer name and also preserved the context.

**Comment by anurse** [comment]
Yeah, that's another option, use a shorter prefix. Like `Ext` for `Microsoft.Extensions` and `AspNetCore` for `Microsoft.AspNetCore`.

**Comment by pranavkm** [comment]
Could we drop the longest prefix per repository e.g `Microsoft.AspNetCore.Server.Kestrel.Core` -> `Core`?

**Comment by pranavkm** [comment]
By the way, we could investigate if switching to Server 2k16 helps here (https://www.ghacks.net/2016/05/27/microsoft-260-long-path-limit)

**Comment by anurse** [comment]
> Could we drop the longest prefix per repository

Yeah, that's the extreme thing I mentioned in one of the sub bullet points. I think I have a slight preference for truncating the same prefix repo-wide (at least in the first pass) so that it's easy to mentally append `Microsoft.AspNetCore` or `Microsoft.Extensions` to get the package ID. Although now that I say that, the fact that there will need to be at least two of those prefixes means that maybe I've convinced myself the mental load is the same no matter which way we do it.

**Comment by natemcmaster** [comment]
Some repos have already started doing this. Here is a list of repos that have the folder names shortened.

 - [ ] Antiforgery
 - [ ] AzureIntegration
 - [ ] BasicMiddleware
 - [ ] BrowserLink
 - [ ] Caching
 - [ ] Common
 - [ ] Configuration
 - [ ] CORS
 - [ ] DataProtection
 - [x] DependencyInjection - https://github.com/aspnet/DependencyInjection/pull/561
 - [ ] Diagnostics
 - [ ] DotNetTools
 - [x] EntityFramework - https://github.com/aspnet/EntityFramework/pull/7779
 - [ ] EventNotification
 - [x] FileSystem - https://github.com/aspnet/FileSystem/pull/289
 - [ ] Hosting
 - [ ] HtmlAbstractions
 - [ ] HttpAbstractions
 - [ ] HttpSysServer
 - [ ] Identity
 - [ ] IISIntegration
 - [ ] JavaScriptServices
 - [ ] JsonPatch
 - [x] KestrelHttpServer - https://github.com/aspnet/KestrelHttpServer/pull/1555
 - [ ] Localization
 - [ ] Logging
 - [ ] MetaPackages
 - [ ] Microsoft.Data.Sqlite
 - [ ] MusicStore
 - [ ] Mvc
 - [ ] MvcPrecompilation
 - [ ] Options
 - [ ] Proxy
 - [ ] Razor
 - [ ] ResponseCaching
 - [ ] Routing
 - [x] Scaffolding - https://github.com/aspnet/Scaffolding/pull/583
 - [ ] Security
 - [ ] ServerTests
 - [ ] Session
 - [ ] SignalR
 - [ ] StaticFiles
 - [ ] Testing
 - [ ] WebSockets

**Comment by pranavkm** [comment]
Just a note on my previous suggestion for completeness - Server 2k16 actually works well for this. However, this wouldn't work for down level where we'd continue building and compiling.

**Comment by natemcmaster** [comment]
cc @ryanbrandenburg

**Comment by ryanbrandenburg** [comment]
The repos that run into this seem to have all been fixed/changed, do we still care about doing the rest for consistency or should we do this as things become problems?

**Comment by Eilon** [comment]
Closing for the reason @ryanbrandenburg mentioned. We'll tackle this on an as-needed basis.
