### ISSUE TITLE
Produce a Linux arm32 runtime for ASP.NET Core

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#554]
In 2.0.0, `microsoft/dotnet` Docker images added support for arm32v7 architectures in Debian Jessie/Stretch. To make ASP.NET Core work well in, we need to produce corresponding Docker images and an ASP.NET Core runtime store.

cref https://github.com/dotnet/core-setup/issues/3122

arm32 runtime announcement: https://github.com/dotnet/announcements/issues/29

**Comment by natemcmaster** [comment]
Potential issues:

- Does SQLitePCLRaw support for linux-arm? cc @bricelam @ericsink
- How do we configure a TeamCity agent to build the runtime store on arm32v7? cc @JunTaoLuo 
- Are there any other native components that need to xcompile to linux-arm32?

**Comment by ericsink** [comment]
"Does SQLitePCLRaw support for linux-arm?"

Yes, as of version 1.1.8.

**Comment by natemcmaster** [comment]
@ericsink thanks, good to know. 

Microsoft.Data.Sqlite 2.0.0 depended on 1.1.7, so we should consider patching this if we want to make SQLite work in a 2.0.x runtime store.

**Comment by JunTaoLuo** [comment]
Libuv and sqlitepclraw are the only native components in the store now so this is definitely possible. It's going to take a bit of work to set up the agents to build the store. Do we need to build installers for this or will a zip be sufficient?

**Comment by natemcmaster** [comment]
> Do we need to build installers for this or will a zip be sufficient?

tar.gz for sure so we can make the docker images. Installers would be great too if it's not too much work. If it is, then we should evaluate this in our triage discussion.

**Comment by nzain** [comment]
I want to add that many (most?) "arm developers" can't rely on default installation routines. Generic solutions (zip or tar.gz) and a little custom work are preferred in my oppinion. This is more the linux-way not the windows-way of doing things. For example, my team is neither working on a raspberry PI nor does our device run debian linux. Custom work is required anyways, flexibility is welcome.

**Comment by Eilon** [comment]
@DamianEdwards - do you know if we have ARM32 support planned for ASP.NET/EF Core?

**Comment by JensNordenbro** [comment]
So, when doing this, may I suggest to produce a crossgen:ed store for asp.net core since arm32 is one of the architectures that would benefit the most of not having to spend time JIT:ing IL.  (See [corefx-crossgen:ed](https://github.com/dotnet/core-setup/issues/3314)  for more of the same)

**Comment by Eilon** [comment]
Moving to Backlog for now.

**Comment by kasper3** [comment]
[`Microsoft.Data.SQLite 2.1.0-preview1-final`](https://www.nuget.org/packages/Microsoft.Data.SQLite/2.1.0-preview1-final) depends on ` SQLitePCLRaw.bundle_green (>= 1.1.8)`.

**Comment by Eilon** [comment]
@muratg - can you get an engineer lined up for this? Per @DamianEdwards , this is needed for 2.1.0.

**Comment by natemcmaster** [comment]
Our first arm32 builds is available here: https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/2.1.0-preview3-32175/aspnetcore-runtime-2.1.0-preview3-32175-linux-arm.tar.gz. It's not crossgen-ed, but should contain all the native and managed binaries necessary to run basic Microsoft.AspNetCore.App apps.

I'm unable to verify that it actually works on arm32 by just using a macbook due to https://github.com/dotnet/coreclr/issues/17487. Simple apps die on the first HTTP request before a connection can be established. Let me hunt down some real arm32 hardware to see if this works.

**Comment by muratg** [comment]
@natemcmaster that's awesome!  @anurse has a tower I think.

**Comment by natemcmaster** [comment]
I verified the linux-arm runtime works on a Raspberry Pi 2. There appear to be coreclr issues with QEMU + Docker, so the only way to verify the runtime is on true arm32 hardware.

Closing for now, however, there is some followup work we should consider doing soone. See 

- https://github.com/aspnet/Universe/issues/1061
- https://github.com/dotnet/dotnet-docker/issues/480
