### ISSUE TITLE
Automate dependency updates

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#577]
Because we plan to start committing repo hashes, build tool versions, and have already started committing exact versions of dependencies, we should make it easier to automate updates to these.

Workflow:
 - Run a scheduled or trigger-based update script
 - Ensure build still passes
 - Commit and push changes

cref #576 , #574 , #566

**Comment by ryanbrandenburg** [comment]
As per conversation in person, we would want this to work with either a NuGet feed or ProdCon as the "source of truth".

**Comment by natemcmaster** [comment]
cc @pranavkm

**Comment by natemcmaster** [comment]
@ryanbrandenburg I have a bunch of information now on how we can automate this now that prodcon is stabilizing. Is this work item one you still want to own?

**Comment by ryanbrandenburg** [comment]
Yeah, let's swap info about how exactly we want this to function and I'll drive it.

**Comment by ryanbrandenburg** [comment]
Some areas for to look at when doing this work:

- https://github.com/dotnet/versions/blob/cdce4ee1842eca91db64a1531c6fc4458c3e0bcf/Maestro/subscriptions.json#L559-L580
- https://github.com/dotnet/versions/blob/master/build-info/dotnet/product/cli/release/2.1/build.xml
- https://github.com/dotnet/corefxlab/blob/master/scripts/update-dependencies/update-dependencies.csproj

**Comment by ryanbrandenburg** [comment]
This work is "done" but we haven't seen a run of it in Maestro because ProdCon builds have not gotten to us in a while. We won't be able to learn more on this until they are flowing again, so it's blocked.

**Comment by ryanbrandenburg** [comment]
We successfully ran this script and merged the PR it created.
