### ISSUE TITLE
Run couple of iterations of microbenchmarks during Test target

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#590]
Benchmarks keep breaking (kestrel, DI) and it goes unnoticed.

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/dev/benchmarks/EFCore.Benchmarks/BenchmarkJobAttribute.cs

In EF Core we have attribute to create benchmark job. It is conditional on env var to set run strategy and iteration count. dotnet run runs 1 iteration of each benchmark. Only setting env var makes it to run as full result collecting benchmarks. We haven't bothered to look into integrating this into build script but with such setup, it would be as easy as to call dotnet run on the project. Perhaps something similar can help in above case.

**Comment by Eilon** [comment]
Yes this is reasonable. Can you investigate a solution for Kestrel and we can try to apply that to other repos that still need this?

**Comment by pakrym** [comment]
I started a thread in BenchmarkDotNet https://github.com/dotnet/BenchmarkDotNet/issues/566
