### ISSUE TITLE
Move archiver tool to Universe

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#595]
Currently lives in Metapackage's history at https://github.com/aspnet/MetaPackages/tree/7d3461eed4378b5142eabd48205d032d511d34c3/src/dotnet-archive

**Comment by JunTaoLuo** [comment]
We are using the pre-published version of that tool in our drop share which isn't ideal.

**Comment by Eilon** [comment]
@JunTaoLuo where do we use this tool?

**Comment by natemcmaster** [comment]
We use it to make the LZMA. We should definitely do this.
