### ISSUE TITLE
Run deb/rpm packages builds in parallel

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#610]
Currently this takes 50 to 60 minutes because we build a dozen variants of deb/rpm installers. These can all run in parallel since each deb/rpm build is isolated in a docker container.

**Comment by JunTaoLuo** [comment]
I wonder how relevant this will be if we decide to move towards platforms. Also, https://github.com/dotnet/core-setup/issues/3325 would simplify installer builds for us significantly.

**Comment by natemcmaster** [comment]
Not really important now that we only build one .deb file.
