### ISSUE TITLE
Update installer platform requirements

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#629]
Ubuntu 16.10 support has ended we can remove this.
Ubuntu 17.04 will be dropped in January
ubuntu 17.10 is added, need to figure out how to build this one.

This is required for future builds with runtime store in the 2.0.x patch branch.

**Comment by JunTaoLuo** [comment]
For January, we have decided to drop 16.10 support but keep all plaforms the same. The plan will be re-evaluated for the February patch.

**Comment by Eilon** [comment]
@JunTaoLuo can you give an update on this when you're back? Also, I'm not sure exactly what this is about - which installer are we talking about here?

**Comment by JunTaoLuo** [comment]
I'll need to check with @leecow.

**Comment by leecow** [comment]
This is concerning keeping the provided linux native installers inline with what's in support. From your side it will be aspnetcore-store and dotnet-hosting

**Comment by Eilon** [comment]
@JunTaoLuo can you provide an update?

**Comment by JunTaoLuo** [comment]
Our installers are now distro agnostic in 2.1, we no longer produce .deb and .rpm files with distro RIDs in them so this issue no longer applies. 

The work required here is to make sure our 2.0 installers' names are kept up to date for aspnetcore-store and dotnet-hosting. I'll move the milestone to the appropriate one.

As a side note, we never had any platform specific implementation differences in our installers but we kept the naming to be the same as the core installers, which contains distro RIDs in 2.0.

**Comment by JunTaoLuo** [comment]
I forgot there was already an issue tracking this work and opened a separate issue at https://github.com/aspnet/Universe/issues/971. Closing this as it is already done.
