### ISSUE TITLE
Find a way to embed the git sha in the assembly info

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Universe#64]
We can use the AssemblyMetadataAttribute but we need a way to integrate it. Maybe we can set and environment variable that the runtime can use to populate assembly info on the fly instead of editing files.

**Comment by bricelam** [comment]
@pranavkm, make it so

**Comment by dmccaffery** [comment]
Been doing this for years; and it is very useful. I emit the following as part of my build system (for MSBuild):

Version (Simple Versioning) - 1.0.0.0
File Version (Includes Build Number) 1.0.0.061605
Informational Version (SemVer) - 1.0.0-beta-061605-1232

Metadata:
Built By (or Requested By)
Built On (Machine)
Build Date (UTC)
Commit ID (Git SHA Hash or Commit ID from TFVC)
Build Definition (Name of Build Definition from TFS)

The SemVer is generated using the following scheme:

Local Builds
Major, Minor, Patch specified by dev in a "build.props" file.
Pre-release tag is always Alpha
Current date and time is appended to pre-release tag (UTC) to ensure that subsequent local builds always have a greater version (great for local testing of NuGet packages)

Server Builds
Major, Minor, Patch specified by dev in a "build.props" file.
Pre-release tag is based on branch:
Feature (or not recognized): alpha
dev or develop : beta
main or master: rc
release: -none-

Both TFVC and Git are supported, although I prefer Git using gitflow (makes all the automation easy).

One thing to note: the version info file generated and appended with a guid dumped in obj/ folder at solution really root and referenced by all projects in the solution automatically during MSBuild -- which ensures local builds through Visual Studio always have the same version when built together. Obviously, this wouldn't work the same way for the DNX build system, but I suppose emitting to a shared source folder that each project.json includes would work. All that should be needed would be build target that generates the assembly info file before compiling; possibly using the pre-compile target in standard lifecycle?

**Comment by muratg** [comment]
@victorhurdugaci Can we reuse some of the work from dnu source to make this happen?

**Comment by pranavkm** [comment]
Could we simply provide the value of `AssemblyInformationalVersion` to DNX? Most CIs already have a way to get to the commit information, so we'd be able to embed this information in a source control system agnostic way.

**Comment by muratg** [comment]
Sounds nice to me.

**Comment by pranavkm** [comment]
Spoke to @davidfowl about this. DNX currently uses the `AssemblyInformationalVersion` to stash the semantic version for the assembly and uses it in display. Consequently we can't use this attribute. We could use [https://msdn.microsoft.com/en-us/library/system.reflection.assemblymetadataattribute(v=vs.110).aspx](`AssemblyMetadataAttribute`) instead.

The recommended way of doing this would be to use a PrecompileModule to read magical env variables to create these attributes on the fly. @davidfowl, when would this be ready by? 

If this feature is still some ways out, we could go with @dmccaffery's suggestion and simply generate a `ExtraAssemblyInfo.cs` on the fly on the CI.

**Comment by victorhurdugaci** [comment]
How will the commit hash work with source packages? You clone a repo, sync to that commit id but then how do you get the appropriate sources packages?

**Comment by pranavkm** [comment]
@victorhurdugaci Isn't this for embedding info in assemblies?

**Comment by victorhurdugaci** [comment]
Yes, but you embed it because you want to use it later. How are you going to use the hash with projects that use sources packages?

**Comment by dmccaffery** [comment]
Condo already does this. You're welcome to use/copy this for KoreBuild:

https://github.com/PulseBridge/Condo/blob/75c0f77dccf567d517298c2a7d3449ce4412118b/src/build/sake/Condo.AssemblyInfo.shade

https://github.com/PulseBridge/Condo/blob/75c0f77dccf567d517298c2a7d3449ce4412118b/src/build/sake/_info-collect.shade

https://github.com/PulseBridge/Condo/blob/75c0f77dccf567d517298c2a7d3449ce4412118b/src/build/sake/_info.shade

It emits a Condo.AssemblyInfo.cs file, which is included in the build to add the additional attributes, and then cleaned up afterwards.

There is an example project in the repo. that will execute the default targets if you need an example. Its also fully cross-platform.

**Comment by dmccaffery** [comment]
One other thing to point out; Condo does not rely on git being available at the command line to discover the commit id, branch, etc. It parses the git config files manually. It also supports emitting the commit id for TFVC if one is not using git.

**Comment by muratg** [comment]
I think @victorhurdugaci has a point.  *.Sources packages would not have this information embedded (since they're not actual assemblies, just build time dependencies.)

**Comment by pranavkm** [comment]
Wouldn't that need to go in the package though? I thought embedded it in the assembly was purely informational - it's not a replacement for `dnu sources`

**Comment by muratg** [comment]
We're removing `dnu sources` feature (for now.)  

I agree though, this would definitely have informational value, and once we automate it, free.
