### ISSUE TITLE
Add templating tests to universe

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#642]
Currently, the tests in aspnet/templating are very unreliable. We should add them to universe once the flakiness is addressed.

cref https://github.com/aspnet/templating/issues/63, https://github.com/aspnet/templating/issues/150

**Comment by natemcmaster** [comment]
FYI - @SteveSandersonMS - aspnet/Templating is building in aspnet/Universe on dev, but the tests are still still skipped.

**Comment by SteveSandersonMS** [comment]
@natemcmaster Should be safe to re-enable now.

**Comment by natemcmaster** [comment]
Thanks @SteveSandersonMS
