### ISSUE TITLE
BuildGraphOf is broken

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Universe#650]
Currently when you try to use the `/p:BuildGraphOf` property you'll get a failure when it doesn't find the packages for the given repos dependencies within Universe. We should fix this scenario to make it easier for people to fix Universe-only problems.

**Comment by Eilon** [comment]
@ryanbrandenburg is this still an issue?

**Comment by Eilon** [comment]
Per triage discussion, this won't be useful anymore because we'll have incremental builds.

We should just delete the parts of the build that support `BuildGraphOf` and never worry about it again.
