### ISSUE TITLE
Implement configurable publishing

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#653]
Need to add support for publishing build results to the following:

 - myget
 - azure blob storage

Currently, only myget is supported. We need to be able to publish to one or many publish sources.

![image](https://user-images.githubusercontent.com/174281/33085204-e319e720-ce98-11e7-8bad-2d70cce19791.png)

**Comment by pranavkm** [comment]
My guess is `versions` wouldn't apply to aspnetcore's build. The other two options seem straightforward.

**Comment by natemcmaster** [comment]
This bug may not be important given https://github.com/aspnet/Coherence-Signed/issues/701. We should be able to move the current /t:Push target to coherence-signed instead and close this out.

**Comment by pranavkm** [comment]
Resolved in https://github.com/aspnet/Universe/commit/db8adaf5b78dd11a7d25302606881728a40740b8
