### ISSUE TITLE
UpdateSubmodules should update BuildTools as well

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Universe#658]
The UpdateSubmodules script needs to also update and commit new BuildTools in case on of the retrieved submodules uses a new 3rd party dependency (which lives in BuildTools)

**Comment by Eilon** [comment]
Seems like we have to do this for correctness, right?

cc @natemcmaster

**Comment by natemcmaster** [comment]
We don't need this anymore. The 3rd-party list was removed from build tools, and we added a script that updates build tools automatically.
