### ISSUE TITLE
Produce AspNetCore Platform

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#662]
- [x] Produce platform by publishing framework dependent app
  - [x] win7-x64, win7-x86, osx-x64, linux-x64
  - [x] Update artifacts (naming and trimming) including deps.json, runtimeconfig.json and .version files
  - [x] Create optimized binaries using cross-gen 
  - [x] Create symbols
  - [x] Create installers
- [x]  M.A.All package
  - [x] Remove manifests
  - [x] Update publish targets to set `MicrosoftNETPlatformLibrary`
  - [x] Errors
  - [x] Enforce dependent version ranges

**Comment by natemcmaster** [comment]
FYI - I'm working on https://github.com/aspnet/Coherence-Signed/issues/690 next
