### ISSUE TITLE
Add a way to disable strong name verification and execute it when building things on the CI

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#673]
Due to issues with the signing infrastructure some of the newer packages coming out of our partner builds. This results in failures when we test or run something on desktop `net4x`. To workaround this, we'll add a way to disable strong name verification and execute this as part of our CI builds. Devs \ contributors would have a way to run this to avoid seeing issues around this when building locally.

AspNetWebStack used an MSBuild target that needed to be run to do this. Perhaps that's a way to go about it.

**Comment by ryanbrandenburg** [comment]
The targets get added in aspnet/BuildTools#501. We no longer need to use it on the CI yet, correct?

**Comment by pranavkm** [comment]
Not until we pick up unsigned binaries.

**Comment by ryanbrandenburg** [comment]
Fixed by https://github.com/aspnet/BuildTools/commit/00ce1383114015fe89b221146036e59e6bc11219.
