### ISSUE TITLE
Generate a bill of materials

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#679]
Data to include

 - File name for all nupkg, zip, deb, rpm, tar.gz, etc. files
 - Source repo (e.g. aspnet/Razor)
 - Version 
 - Logical name (for nupkg, this is package ID, for rpm, deb, it might be the display name of the installer)
 - Category (ship, shipoob, noship)
 - Artifact type (NuGetPackage, NuGetSymbolsPackage, VsixInstaller, ZipArchive, etc.)

**Comment by natemcmaster** [comment]
@pranavkm was just talking to Eilon. It looks like we will need to do this for Orchestrated Builds. We need to have a final output of all packages that we can hand off to downstream partners.

Some of this work is already done. Each repo build is already producing artifacts/manifest.xml. 
Remaining work:

 - Merge the manifests from repo builds into one
 - Ensure all files are in the manifest, including windows installers, deb/rpm files, etc. Anything that ends up on the transport feed should be in the manifest.
 - Ensure file hash is updated after signing. Currently, the manifest is generated pre-signing. We should update file SHA after code-signing our binaries.

**Comment by pranavkm** [comment]
Sure, I can have a look at this. What's the timeline for doing this?

**Comment by natemcmaster** [comment]
This is something we wanted to get in for preview1. I'm also keeping myself assigned because I'll be syncing up with @dagood on how we can use this manifest for the "publish plan".

**Comment by natemcmaster** [comment]
FYI - https://github.com/dotnet/versions/blob/e271d197d696866e11337ed78320537cb1fe3556/build-info/dotnet/product/cli/release/2.1/build.xml

**Comment by pranavkm** [comment]
Sweet!

**Comment by Eilon** [comment]
Let's:
1. Remove the bill of materials that we have right now
2. Talk to the ProdCon people about anything extra we would like added to the versions repo

**Comment by natemcmaster** [comment]
See https://github.com/dotnet/buildtools/issues/1937 and https://github.com/aspnet/BuildTools/pull/595
