### ISSUE TITLE
Project.json should allow empty strings for the versions of dependent NuGet packages.

### ISSUE THREAD

**Issue by thereverand** [aspnet/Universe#68]
Right now "kpm restore" requires at least a partial version to be present if the package has not yet been installed from NuGet. The suggested behavior is for an empty version string to indicate that the highest version number package should be used/obtained.

**Comment by artiomchi** [comment]
I do agree with @davidfowl that no version number is a very very bad idea.

At the same time allowing wildcards for version numbers without forcing a dash before the wildcard is a very valid suggestion!

**Comment by muratg** [comment]
Thanks folks. Closing this one, and feel free to file a suggestion for the wildcard behavior.

**Comment by mishfit** [comment]
@thereverand On a Mac I often don't know the version of the package, just the name...this works for me (without editing project.json directly):

```shell
dnu install Newtonsoft.Json
```
