### ISSUE TITLE
Split artifacts.props up into individual repos

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#686]
Instead of one massive list here: https://github.com/aspnet/Universe/blob/dev/build/artifacts.props, each repo should contain a "repo manifest" indicating the shipping status of each artifact.

See also #679

**Comment by natemcmaster** [comment]
I know there was some resistance to the idea because a few people like having a central list for all things, but trying to keep aspnet/Universe's 49 submodules and the build/artifacts.props list in sync has been a cause of more headaches and build breaks than I think it's worth. 

@Eilon @muratg - can we do this for rc1 instead of waiting for MQ? This issue is a continual source of pain.

cc @pakrym @anurse

**Comment by anurse** [comment]
I definitely wasted like... 20mins of my time managing this. If we want a master list, have Universe generate it and spit it out at the end rather than requiring it be consumed.

> can we do this for rc1 instead of waiting for MQ? This issue is a continual source of pain

![https://media3.giphy.com/media/aZ4sQUpybai5y/giphy.gif](https://media3.giphy.com/media/aZ4sQUpybai5y/giphy.gif)

**Comment by muratg** [comment]
@anurse I was thinking the same. We can get the same benefit in other ways.

**Comment by Eilon** [comment]
Sure thing.

**Comment by natemcmaster** [comment]
No plans to change this at the moment. If the mondo-repo plans fall through, we can revisit.
