### ISSUE TITLE
Consider creating HostingStartup builder package

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#694]
It will contain template, TrimDeps task, and enough targets to be able to build correct `deps.json` file having only `HostingStartup` package. To be used by us and AI team.

**Comment by muratg** [comment]
cc @Eilon @JunTaoLuo @Tratcher 

The idea is to prevent some very-easy-to-make mistakes that could cause partner HostingStartup's to possibly fail. There was one such failure in 2.0.3, but it was hidden because of another bug in dotnet muxer.

**Comment by muratg** [comment]
Re: distribution -- I'm thinking of a myget feed for partner dependencies like this.  Antares has a similar need with "detectoid" source package.  

The other option is to keep 0.x versions for these packages and always keep them in "preview" versioning on NuGet.

**Comment by Eilon** [comment]
Sounds a'ight.
