### ISSUE TITLE
"csc.dll" exited with code 255

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Universe#699]
We sometimes get errors such as [this](http://aspnetci/viewLog.html?tab=buildLog&buildTypeId=XPlat_Windows_Win7_Universe&buildId=363350&_focus=16254) when building Universe. Seems to be a Roslyn issue, but we should do some investigation to provide a better report to the Roslyn team, and see if we can't mitigate it in the mean time.

**Comment by ryanbrandenburg** [comment]
This happened again [here](http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=370006&_focus=8865). Not sure what steps to take to get more information. Maybe we could extract/preserve the error log from [this task](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L84) somehow?

**Comment by natemcmaster** [comment]
Would be good to open an issue on dotnet/roslyn. They may be able to provide instructions on gathering more data.

**Comment by ryanbrandenburg** [comment]
Good point. I was hoping we could have a little more to go on before filing against them, but they'll know best how to get that information.

**Comment by smitpatel** [comment]
I am seeing this consistently on EF repo on Ubuntu since yesterday.

**Comment by natemcmaster** [comment]
Any chance you have a crash dump? If so, can you share it with the roslyn team dotnet/roslyn#23846 ?

**Comment by smitpatel** [comment]
I am not able to make it fail while running on Ubuntu directly. It fails only while running through CI only. Any ideas?

**Comment by natemcmaster** [comment]
none other than what has already been discussed on  dotnet/roslyn#23846

**Comment by Eilon** [comment]
Closing this because there's nothing left for us to track. It was ultimately a JIT bug.
