### ISSUE TITLE
Test generated shared framework

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#706]
Add tests to test end to end functions of the shared framework. We can test using templates, e.g. dotnet new mvc, and/or using something like MusicStore.

**Comment by Eilon** [comment]
Can you come up with a specific list of tests and we can triage again?

**Comment by JunTaoLuo** [comment]
# Variations

## Platforms:
Each of the follwing os and bitness must be tested
- win-x64
- win-x86
- osx-x64
- linux-x64

## Installers:
Each of the following types of installer must be tested
### Installers: 
- Windows: Windows Hosting Bundle (.exe) SDK (.exe)
- macOS: SDK (.pkg)
- Linux: SDK (.deb, .rpm)
### Archives:
- Windows: SDK (.zip)
- macOS: SDK (.tar.gz)
- Linux: SDK (.tar.gz)

## Metapackages
While the default templates will use .App as its metapackage, we need to ensure an app using either of the following metapackage can execute
- Microsoft.AspNetCore.App
- Microsoft.AspNetCore.All

## App templates
We want to test as many different types project templates. At a minimum we should verify using mvc and razor templates
- mvc aka ASP.NET Core Web App (Model-View-Controller)
- razor aka ASP.NET Core Web App
Each template should be tested with as many variations as possible. For example mvc and razor templates can be configured with individual auth, to use local db, or to use BrowserLink, etc

## Tooling Experience
Complete the test using VS tooling and CLI
- Visual Studio
- dotnet cli
- VSCode (optional?)
- VS for mac (optional?)

# Scenarios

## dotnet new and offline restore
Create a new app using the dotnet new command and ensure restore works offline. This ensures our packages are included in the LZMA/offline restore cache.

## dotnet build and dotnet run
Builds successfully and can run the app. The build output should not include any binaries from the shared frameworks (i.e. should only contain the app's main dll)

## dotnet publish portable and run the published outupt
Publishes successfully and can run the app. The publish output should also only inclulde the app's main dll

## dotnet publish portable and disable publish trimming
Publishes successfully and can run the app. Add ExcludeAssets="Build" to the reference of the metapackage and the publish output should now include the app's main dll and all the aspnetcore binaries referenced.

## dotnet publish standalone
Publish the app and specify a runtime. The published output should include the app's dll, aspnetcore binaries and dotnet core binaries. The published output should be able to run on a fresh machine with no dotnet installed.

## debugging
Ensure that when debugging the app, symbols can be loaded from the symbol server. This is a Visual Studio scenario only and cannot be tested on the command line. Also ensure profiling symbols can be loaded on Linux/Windows.

## error messages
Try to break things! And see if error messages are useful.
- Use a tfm that does not match the metapackage
- Try to run a portable app (from build or publish) when no shared frameworks are installed or are removed (delete /shared/Microsoft.AspNetCore.App and Microsoft.AspNetCore.All)
- Try to transitively lift out a package referenced by Microsoft.AspNetCore.App. This scenario only applies to .App, .All do not lock versions

## analyzers
TODO:

These are tests we should perform for preview1, some of these steps can also be automated and should be incorporated into our builds.

**Comment by natemcmaster** [comment]
This is still in 2.1.0. Should it be moved out to 2.2.0?

**Comment by JunTaoLuo** [comment]
I believe @mikeharder  is working on something that'll help with this. Yes this can be moved out.

**Comment by JunTaoLuo** [comment]
@mikeharder I think this is mostly covered by the testing that you have been working on so I'll reassign this item to you for now.

**Comment by natemcmaster** [comment]
Closing as complete.
