### ISSUE TITLE
Produce Microsoft.AspNetCore.App package and shared framework

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#721]
This package will include first party packages and a few sanctioned third party packages. The .All package will take a dependency on the .App package and exclude its build assets. The .All shared framework will be dependent on the .App shared framework. Transitive references to third party references in both packages will be flattened.

Packages in the .All that will be removed from .App:
```
SQLitePCLRaw.*

    <PackageReference Include="Microsoft.Data.Sqlite" version="2.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" version="2.0.1" />

StackExchange.Redis

    <PackageReference Include="Microsoft.Extensions.Caching.Redis" version="2.0.0" />

WindowsAzure.Storage

    <PackageReference Include="Microsoft.AspNetCore.DataProtection.AzureStorage" version="2.0.1" />

Microsoft.Azure.KeyVault

    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" version="2.0.0" />
 ```

Third party packages remaining in .App:
```
Libuv
Remotion.Linq
Newtonsoft.Json
Microsoft.VisualStudio.Web.BrowserLink
System.Interactive.Async
```

cc @anurse @DamianEdwards

**Comment by natemcmaster** [comment]
FYI - BrowserLink isn't third-party. We build it. https://github.com/aspnet/browserlink

**Comment by JunTaoLuo** [comment]
Fair, though I believe there's some discussions on whether this package should remain in .App in the future, which is why I called it out explicitly here.

**Comment by Eilon** [comment]
The list above is missing Ix-Async. @ajcvickers can you follow up with @DamianEdwards to confirm that this stays in the list? And if not, what is the plan?

**Comment by DamianEdwards** [comment]
It should be there, along with EF Core in general.

**Comment by JunTaoLuo** [comment]
Updated. I think I missed it because the package name is System.Interactive.Async so I missed it in my previous list.

**Comment by JunTaoLuo** [comment]
Seems like I was generating the list of packages based on 2.0 packages for the original list. In 2.1 we also need to exclude these packages:
```
Microsoft.Azure.KeyVault
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.AzureKeyVault" version="2.1.0-preview1-28086" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.Service.AzureKeyVault" version="2.1.0-preview1-28086" />
    <PackageReference Include="Microsoft.AspNetCore.AzureKeyVault.HostingStartup" version="2.1.0-preview1-28086" />
```
