### ISSUE TITLE
Don't make changes to korebuild-lock.txt when building each repo

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#734]
Now that korebuild-lock.txt is committed to source, we should stop overwriting it. We should use a different mechanism to override the korebuild version so that we're not modifying a source-controlled lockfile on build. It breaks `git submodule update`.

**Comment by jkotalik** [comment]
As a temporary workaround, do: git submodule foreach 'git checkout -- korebuild-lock.txt'

**Comment by jkotalik** [comment]
Also, for SignalR we will need to do the same for client-ts/package.json

**Comment by anurse** [comment]
Well, unfortunately that's a lot harder. NPM really doesn't provide any other way to pack with a version other than the one in the `package.json`. We could build a whole bunch of copy logic to create a temporary copy of the whole package layout before packing (NPM is also extremely strict on the layout of the directory being `npm pack`ed), but that's pretty much our only option.

**Comment by natemcmaster** [comment]
@anurse Could you make a backup copy of the original package.json, modify and pack, then replace it with the backup? I believe this is what the current SignalR build attempts, but it relies on git-checkout...which I've found is flaky.

**Comment by anurse** [comment]
Yeah, that would be fine.
