### ISSUE TITLE
Add a way to propagate dependency version changes to subrepos

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#741]
Useful when updating third-party references

1. Update every submodule `dependencies.props` to the versions from universe `dependencies.props`
2. Add temporary custom feeds to repositories affected (so they can be built on their own with new packages)
3. Optionaly: Create branches for affected repositories

There should be a way to continually update versions (we found a bug, it was fixed and we need to update again)

**Comment by natemcmaster** [comment]
Should be as simple as adding a script that does this:

1. `build.cmd /t:GeneratePropsFiles`
2. `./scripts/UpdateRepos.ps1 -Source ./artifacts/build/ -NoPush`

**Comment by pakrym** [comment]
Doesn't solve problems with feeds.

**Comment by natemcmaster** [comment]
Custom feeds shouldn't be necessary. We can push new packages to aspnetcore-dev as needed

**Comment by pakrym** [comment]
Manually? What if they are broken?

**Comment by natemcmaster** [comment]
I assume we don't want CI pushing broken state. This is why UpdateRepos.ps1 ensures a repo can still build and tests pass before it pushes updates.

CI pushes can be automated. 

clarify this for me: are you talking about making this run on CI? Or on your local box?

**Comment by pakrym** [comment]
It's on the local box. I want to get repos to the state where they work outside of universe with updated package versions so I can debug/do changes/open PRs.

**Comment by natemcmaster** [comment]
Sounds similar to this conversation https://github.com/aspnet/Coherence-Signed/issues/680

**Comment by pakrym** [comment]
Not really, in this case, I don't want CI to do things for me, I want to get local universe submodule into a state as if they were updated to new versions. So I can cd into submodule and fix/debug failures.

**Comment by Eilon** [comment]
@pakrym can you chat with @natemcmaster in person to provide more details on the scenario?

**Comment by natemcmaster** [comment]
_Engineering triage decision:_ this does not appear to be high priority, and we do not plan to address this.

This raised an important question about managing external dependencies. This has been added to the notes in our repo reduction plans.
