### ISSUE TITLE
Add a switch to continue running universe even when tests fail

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#742]
And have a report of failed tests when finished.

/cc @natemcmaster @ryanbrandenburg

**Comment by ryanbrandenburg** [comment]
In addition to the standard "peeling the onion" of test failures help, this would also help with our test statistics. Currently tests run at the end of builds are less likely to pass, so the statistics for them are all screwy.

**Comment by Eilon** [comment]
Recommendation is to change Universe build to do this:

1. Build everything
2. Test everything by running all test projects, no matter whether one failed or not
   * If any test project fails, ultimately fail the Universe, but keep running more test projects
