### ISSUE TITLE
LZMA needs to include full framework assets

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#744]
As discovered by @jbagga some full framework only package dependencies, such as ManagedEsent, are not captured in the LZMA which means full framework samples are not able to be restored offline. This occurs because we build the LZMA with packages restored for netcoreapp2.0 TFM only.

The simple fix would be to restore for both core and full framework at https://github.com/aspnet/Universe/blob/cf7eccab5eec7d68ba3f9c201c5a109bb70036dd/build/tools/templates/Archive/Archive.csproj#L6.

@natemcmaster I know we talked about overhauling the mechanism to remove the reliance on restore and use an explicit list of packages. I'm assuming we wouldn't want to do this in the release/2.0 branches but instead explore that option in dev?

cc  @Eilon

**Comment by natemcmaster** [comment]
> full framework samples are not able to be restored offline

IIUC this scenario is out of scope for the LZMA. We don't intend to support all possible projects...just the most common ones. For example, we don't support offline restore for standalone .NET Core applications. Users who specify a RID have to be online to get the runtime-specific packages.

cc @livarcocc

**Comment by livarcocc** [comment]
Correct. This has been the direction we have been keeping since 1.0.

**Comment by JunTaoLuo** [comment]
I remember we didn't include the RID specific packages but I wasn't sure about the full framework ones. We spoke with @DamianEdwards this morning and it seemed like we did actually want to support full framework samples?

**Comment by natemcmaster** [comment]
If this is a new direction we want to take (cc @DamianEdwards), it would have a negative impact on cross-plat. Currently, there is only one LZMA file and its used by Windows, Linux, and macOS. I don't think we should add .NET Framework assets (effectively Windows-only assets) unless we are willing to produce different LZMA files for different platforms.

**Comment by natemcmaster** [comment]
cc @muratg for triage

**Comment by JunTaoLuo** [comment]
I think we should check how many more packages are added if we add full framework dependencies. If it's just the ManagedEsent package, for example, I think it wouldn't be too bad to include it on all platforms. If we need to support different LZMA for each platform, I would be more hesitant to add the full framework packages.

**Comment by JunTaoLuo** [comment]
Did a quick test and it looks like if we want to make offline full framework restore work, we will need the following packages
```
managedesent\1.9.4
microsoft.applicationinsights.agent.intercept\2.4.0
microsoft.applicationinsights.perfcountercollector\2.4.1
microsoft.applicationinsights.windowsserver.telemetrychannel\2.4.0
microsoft.azure.keyvault.core\1.0.0
microsoft.data.services.client\5.8.2
newtonsoft.json\6.0.8
sqlitepclraw.provider.e_sqlite3.net45\1.1.8
system.componentmodel.eventbasedasync\4.0.11
system.dynamic.runtime\4.0.0
system.linq.queryable\4.0.0
system.net.http\4.3.1
system.net.requests\4.0.11
```

**Comment by livarcocc** [comment]
We should not produce the lzma by maintaining the list of packages manually. The lzma today is produced by doing a dotnet new, dotnet restore to a particular folder and using the packages of that folder to produce the lzma.

I don't know if above you were just illustrating the delta of packages or state it as a list of packages to be somehow manually added to the lzma.

**Comment by JunTaoLuo** [comment]
It's a delta list of packages that would need to be added to the lzma if we needed to support restoring full framework samples offline. I generated it by restoring for net461 instead of netcoreapp2.0 and comparing the restore output folders.
