### ISSUE TITLE
Add runtime-specific packages to .All

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#762]
Add a runtime.json for RID-restore to make sure rid-only packages are included. i.e. Microsoft.AspNetCore.Server.IIS.

**Comment by muratg** [comment]
cc @JunTaoLuo FYI. 

I wonder if this would have any unforeseen impact...

**Comment by natemcmaster** [comment]
Currently not planning to put this into preview1 so we have more time to consider the impact.

**Comment by natemcmaster** [comment]
@shirhatti @jkotalik should we do this for 2.1.0-preview2? i.e. should Microsoft.AspNetCore.Server.IIS be included in standalone deployments? We bumped this from preview1 b/c aspnetcorerh wasn't ready yet.

**Comment by jkotalik** [comment]
Yes, as long as @shirhatti is okay with it.

**Comment by shirhatti** [comment]
We don't do this already? 😕 How does libuv work today without this?

**Comment by natemcmaster** [comment]
Libuv isn't a RID-split package (yet), so it is included in the restore graph of a portable project. When/if we rid-split libuv, it would be in the same category as Microsoft.AspNetCore.Server.IIS.

**Comment by natemcmaster** [comment]
How to do this:

1. In Microsoft.AspNetCore.App and .All, add a file into the package at <root>/runtime.json. Contents:
```json
{
  "runtimes": {
    "win": {
      "${MetaPackageId}": {
        "runtime.win.${MetaPackageId}": "${PackageVersion}"
      }
    }
  }
}
```
2. Create two new packages, runtime.win.Microsoft.AspNetCore.App and  runtime.win.Microsoft.AspNetCore.All, and add to these packages dependencies which should only apply to a standalone deployment on windows.
```xml
<package>
  <metadata>
     <dependencies>
        <dependency id="Microsoft.AspNetCore.Server.IIS" version="$IISVersion$" />
     </dependencies>   
   </metadata>
</package>
```

Testing:
 - in a normal restore (no runtime identifiers set), Microsoft.AspNetCore.Server.IIS does not end up in project.assets.json.
 - in a restore with RuntimeIdentifier = win-x64, win-x86, win7-x64, win7-x86, etc, that Microsoft.AspNetCore.Server.IIS is in project.assets.json
 - in a standalone publish `dotnet publish -r win-x64`, ensure that aspnetcorerh.dll is in the output
 - in a standalone publish for other platforms such as `linux-x64`, aspnetcorerh.dll is not in output

Let me know if you have more questions.
