### ISSUE TITLE
Set default ANCM hosting model to InProcess from .App metapackage

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#766]
The default hosting model is currently out-of-proc. When we are ready, let's enable in-proc by default.

To do this, we need a copy of the MSBuild properties in M.A.Server.IIS -- which sets the `AspNetCoreHostingModel` msbuild property -- copied into the .App metapackage.

https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IIS/Microsoft.AspNetCore.Server.IIS.targets
  
Depends on https://github.com/aspnet/Universe/issues/762

**Comment by shirhatti** [comment]
Moving to 2.1.0

**Comment by DamianEdwards** [comment]
In-proc got moved out past 2.1.0

**Comment by Eilon** [comment]
@shirhatti / @DamianEdwards / @muratg - what's the plan for this issue?

**Comment by shirhatti** [comment]
We can't make this change in 2.2.0. It's too big of a behavior change.

For 3.0, we've already made this change in the websdk https://github.com/aspnet/websdk/pull/407

**Comment by shirhatti** [comment]
Yes
