### ISSUE TITLE
Add "don't touch this" doc to all pubternal types in all packages

### ISSUE THREAD

**Issue by Eilon** [aspnet/Universe#767]
We need to add docs to all our pubternal types (i.e. `public` types in a `.Internal` namespace) to indicate that they are not supported.

I suggest writing a tool that uses Roslyn to insert a comment for all applicable types:
```c#
///   <summary>
///       This API supports infrastructure and is not intended to be used directly
///       from your code. This API may change or be removed in future releases.
///   </summary>
```

This will also make it easier in the future to enable the "doc comments required" C# compiler error because we *would* have docs for all accessible types.

For example, here's what EF Core does: https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore/Internal/Graph.cs#L9-L24

```c#
///   <summary>
///       This API supports the Entity Framework Core infrastructure and is not intended to be used
///       directly from your code. This API may change or be removed in future releases.
///   </summary>
```

- Ⓜ️🌊🔨

**Comment by rynowak** [comment]
Can we make some of these proper internal and leave pubternal for when it's actually required or valuable?

**Comment by Eilon** [comment]
You mean even in 2.1? Per our own rules that isn't a breaking change, so we certainly *could*...

**Comment by natemcmaster** [comment]
Can we also stop setting NoWarn CS1591? Devs regularly miss documenting API -- even normal API -- because we suppress this warning in many of our projects.

**Comment by Eilon** [comment]
@natemcmaster yup that's mentioned in the initial description 😄

**Comment by natemcmaster** [comment]
Re-read my question - don't think I was clear. I actually meant something stronger. Could we _forbid_ use of NoWarn CS1591?

**Comment by Eilon** [comment]
Oh - well, once we get all the docs actually cleaned up, yes, we'd consider banning it. Though, for some prototype code, or local dev work, we might not want to be quite so strict.

**Comment by benaadams** [comment]
> Can we makethings proper internal and leave pubternal for when it's actually required or valuable?

I assume then you'd make them properly public :)

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspNetCore#3656
