### ISSUE TITLE
Consider removing all Obsolete APIs when we start working on 3.0.0

### ISSUE THREAD

**Issue by Eilon** [aspnet/Universe#776]
In theory, when we start working on 3.0.0, we should delete all APIs that have been marked as `[Obsolete]`. There could be exceptions to that, but we should at least look.

**Comment by davidfowl** [comment]
👍

**Comment by Eilon** [comment]
cc @DamianEdwards as well.

**Comment by Eilon** [comment]
And credit to @kichalla for the idea 😄

**Comment by rynowak** [comment]
That's a cool original idea. Bravo @kichalla

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspNetCore#3654
