### ISSUE TITLE
Create an analyzer metapackage

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#787]
We have a analyzer packages that are ready for preview1:

* https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.Analyzers
* https://github.com/aspnet/Mvc/pull/7258

We need to produce a meta-analyzer package that combines these and is published to MyGet for the preview1 release.

**Comment by muratg** [comment]
Candidates for the package name?

FYI @natemcmaster a new package coming in.

**Comment by natemcmaster** [comment]
Microsoft.AspNetCore.Analyzers

**Comment by DamianEdwards** [comment]
Approve of *Microsoft.AspNetCore.Analyzers*

**Comment by DamianEdwards** [comment]
And to clarify, we want this versioned as 0.1.x and to be pushed to nuget.org for preview1

**Comment by muratg** [comment]
@pranavkm are you able to take this?

**Comment by pranavkm** [comment]
Sure.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Universe/commit/13cf9f76bdc50a3d6beba93fd28cd5888a1a29b5
