### ISSUE TITLE
Build timestamped cumulative runtime store archives for CLI ingestion

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#806]
We build the cumulative runtime store archives for the CLI installers. These artifacts are named like Build.RS.linux.tar.gz and only contain the no-timestamp stores. We should also produce archives with naming such as Build.RS.linux-rtm-10008.tar.gz so we can switch between timestamp and no-timestamp builds easily.

**Comment by Eilon** [comment]
@JunTaoLuo anything further required for the 2.0.6 patch?

**Comment by JunTaoLuo** [comment]
It's not strictly required for the 2.0.6 patch actually, but it'll be nice to have for the next non-stabilized build next time we patch. Not strictly required for 2.0.6

**Comment by Eilon** [comment]
Do you have time to work on this this week?

**Comment by JunTaoLuo** [comment]
Definitely, it's a quick fix.

**Comment by Eilon** [comment]
Ok then let's try to do it in the 2.0.6 timeframe.
