### ISSUE TITLE
Microsoft.AspNetCore.All does not include any target \ prop files from packages

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#810]
We explicitly exclude build items from .App and it's dependencies. This was done to avoid picking up the App's props file that sets the TFM. Since NuGet ensures targets and props are imported in dependency order, we don't need to do this - the .All package's props file will get imported after .App and should override any configured setting.

**Comment by pranavkm** [comment]
cc @muratg \ @JunTaoLuo

**Comment by muratg** [comment]
@JunTaoLuo Was this by design?  Anything we need to do for preview1?

**Comment by pranavkm** [comment]
This essentially results in the Razor.Design \ Razor.Compilation targets not being imported. We should fix this for preview1.

**Comment by JunTaoLuo** [comment]
Oops, I commented on the wrong issue, but this is the actual bug I'm working on testing.

**Comment by Eilon** [comment]
We need to make sure this works in .App and .All right?

Approved for preview1.
