### ISSUE TITLE
EnsureTFMCompatibility check should not run when IsCrossTargetingBuild = true

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#811]
Repro steps

1. dotnet new mvc
2. dotnet run
3. Edit the csproj to change `<TargetFramework>netcoreapp2.1</TargetFramework>` to `<TargetFrameworks>netcoreapp2.1</TargetFrameworks>`
4. Run dotnet restore

Expected: Things work
Actual: This version of Microsoft.AspNetCore.All is only compatible with the netcoreapp2.1 target framework.

**Comment by pranavkm** [comment]
@muratg \ @JunTaoLuo it will be good to take a fix for this in preview1. The workaround involves wiping the obj directory before proceeding which is just bad experience.

**Comment by JunTaoLuo** [comment]
Yes, I'm looking into fixing this for preview1. Testing fix locally right now.
