### ISSUE TITLE
Packages aren't being published to transport feed anymore

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#822]
Possibly related or due to #804. Package aren't being published to our transport feed anymore

cc @pranavkm

**Comment by pranavkm** [comment]
Are you looking in to this?

**Comment by natemcmaster** [comment]
Yup, working on reproducing it right now. I'll send a PR soon-ish

**Comment by natemcmaster** [comment]
Fixed with https://github.com/aspnet/Universe/pull/826
