### ISSUE TITLE
Flatten Microsoft.AspNetCore.All dependencies

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#836]
Currently Microsoft.AspNetCore.All references Microsoft.AspNetCore.App which transitively references other aspnet components: Hosting, Kestrel, Mvc, etc. As per offline discussion yesterday, we would like to flatten the dependencies instead so that Microsoft.AspNetCore.All directly references all of its dependencies and remove its reference to Microsoft.AspNetCore.App.

cc @DamianEdwards @Eilon since this is a preview1 change

**Comment by DamianEdwards** [comment]
The key here is to ensure we don't change the dependency graph of the existing meta-package (.All) in this release, as moving dependencies to the different levels of the tree can introduce behavior changes.

**Comment by JunTaoLuo** [comment]
What do you mean by no change in the dependency graph of the existing .All metapackage? I did a diff of the 2.0.5 and the new 2.1.0-preview1 .All metapackages and ensured nothing was removed. However, in 2.1 we are adding references to new packages, for example Microsoft.AspNetCore.Identity.Service.*. I'm pretty sure this is fine but just wanted to check.

**Comment by natemcmaster** [comment]
Related questions:
 - do we flatten third-party dependencies too?
 - do we also version-cap third-party dependencies?

If yes to both, my concern here is that we will be locking all aspnetcore users everywhere to third-party dependencies we don't control. `<dependency id="Newtonsoft.Json" version="[10.0.1]" />` seems dangerous.

**Comment by DamianEdwards** [comment]
@JunTaoLuo I mean the depth of the graph should be the same, e.g. don't hoist anything higher or push anything lower. This can have semantic differences and affect how something is restored.

@natemcmaster no, in line with above, we should not be flattening anymore than we did before. Version caps **is** in *Microsoft.AspNetCore.App* but I agree we should likely not introduce them now in .All to ensure the behavior for folks using it remains the same.

**Comment by JunTaoLuo** [comment]
Ah, let me remove the version caps in .All
