### ISSUE TITLE
Remove/"Convert to tag" older patch branches which are already released

### ISSUE THREAD

**Issue by smitpatel** [aspnet/Universe#838]
Since we now use `release/x.x` branches for patch/preview releases, can we get older patch branches cleaned up (`rel/x.x.x` & `patch/x.x.x` ones)

**Comment by natemcmaster** [comment]
I believe I cleaned up all patch/2.0.x and rel/2.0.x branches. @JunTaoLuo was looking into doing the same for 1.x.

**Comment by natemcmaster** [comment]
We shouldn't delete tags because release notes may be linked to them, however, we do want to add tags in a consistent manner from now. Tags generally will match the package version of that release

**Comment by smitpatel** [comment]
Updated title to be more clear on tags 😄

**Comment by muratg** [comment]
@smitpatel Looks like EF is clean now. Closing this one.
