### ISSUE TITLE
LZMA is missing Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#848]
2.1.0-preview1-28226 is missing Microsoft.AspNetCore.App from the offline cache.

https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1

cc @JunTaoLuo @Eilon

**Comment by natemcmaster** [comment]
had to revert #849.

**Comment by muratg** [comment]
👀

**Comment by JunTaoLuo** [comment]
Build passed. Closing
