### ISSUE TITLE
Publish symbols to prodcon feed

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#850]
Here are notes on what the symbol publish step will be looking for in the manifest:https://github.com/dotnet/core-eng/blob/master/Documentation/Orchestrated-Build/Api/publish.md#publish-symbol-packages-to-symbol-server. (Something that might not be clear is that it’s looking for Blob elements, not Packages.)

*Placeholder for what do with profiling (.ni.pdb) pdbs produced as part the build.*

**Comment by pranavkm** [comment]
cc @natemcmaster \ @JunTaoLuo \ @dagood

**Comment by ryanbrandenburg** [comment]
We confirmed that this made its way onto the Prodcon feed.

**Comment by ctaggart** [comment]
@ryanbrandenburg Is the prodcon feed something can be access externally/publicly?

**Comment by ryanbrandenburg** [comment]
It is not. To my knowledge there has not been a decision on where/how/if to make symbols publicly available.

**Comment by ctaggart** [comment]
Is there another issue for making the publicly available? If not, can you make one and link it here?

**Comment by dagood** [comment]
The ProdCon feed is available for each build, for example this is the 2.1.1 build: https://github.com/dotnet/versions/blob/726018548f536bb1176c25792a6bf18f88b5d989/build-info/dotnet/product/cli/release/2.1/build.xml. That said, it's not easy to navigate these and ProdCon feeds aren't terribly useful as a symbol source.

When we release a build, symbols should be available on `https://msdl.microsoft.com/download/symbols`. In Visual Studio, this is the default location called "Microsoft Symbol Servers".
