### ISSUE TITLE
Remove the need to mirror packages + transition to dotnet.myget.org/dotnet-core

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#856]
Our repositories currently reference aspnetcore-[dev|release] feeds and NuGet.org while relying on Universe to mirror packages for us from `dotnet-core`, `dotnet-corefxlab`, `roslyn`, `vssdk` and `vsformac` feeds. 
CoreFxLab will transition to dotnet-core and `dotnet-corefxlab` will no longer need to be referenced. The remainder are meant to support tooling and are not consumed by runtime packages. 

Here's my suggestion, once `dotnet-corefxlab` goes away,

* [x] Update repos to reference `dotnet-core` as a source
* [ ] Have Razor explicitly reference `roslyn`, `vssdk`, and `vsformac` (Are there other repos that reference packages from an external feed?)
* [x] Tell customers to use `dotnet-core` to get their ASP.NET Core nightlies. We should be ready to make an announcement to this effect and stop using aspnetcore-dev. - https://github.com/aspnet/Announcements/issues/293

**Comment by pranavkm** [comment]
cc @natemcmaster \ @pakrym \ @Eilon

**Comment by Eilon** [comment]
This does look overall correct to me.

**Comment by natemcmaster** [comment]
+1. I'm in favor of this.

**Comment by pranavkm** [comment]
@pakrym could I assign this to you so we can track whenever you're done with the corefxlab changes?

**Comment by pakrym** [comment]
Sure,

**Comment by natemcmaster** [comment]
How would we handle situations like this? #869  - we need a new version of xunit from yet-another myget feed. Should we update the feeds in each repo? Or continue to mirror?

**Comment by pranavkm** [comment]
Not entirely sure. A test-only package is easy to deal with since the repo could reference the package and we'd be done. Packages consumed by runtime would be far more problematic (for instance if Kestrel needs a nightly build of Libuv?). Maybe we'll still need to keep the feature around, just not use it.

**Comment by pakrym** [comment]
Unblocked now.

**Comment by Eilon** [comment]
We decided that for now we should stop mirroring dependencies and we'll see if anything breaks.
