### ISSUE TITLE
Don't ship Microsoft.AspNetCore.AspNetCoreModule after preview1

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Universe#875]
This is an issue to remind ourselves to mark Microsoft.AspNetCore.AspNetCoreModule as noship after preview1
Related #873

**Comment by muratg** [comment]
Blocked until preview21 ships.

**Comment by Eilon** [comment]
preview21?

**Comment by natemcmaster** [comment]
Why is it blocked? We can mark it as noship for preview2 right now

**Comment by muratg** [comment]
Good point! :D

**Comment by muratg** [comment]
Good point! :D

**Comment by muratg** [comment]
Good point! :D

**Comment by muratg** [comment]
Good point! :D
