### ISSUE TITLE
Review packages built using nuspec and parameter values

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#884]
I took a quick look at our repos and noticed some components use (or seem to use) .nuspec files to build packages. We should review whether this is necessary or we can rely on using .csproj instead. We need to also update the LicenseUrl, which is right no outdated, and other related parameters in these .nuspec files.

The affected repos/packages include (but are not limited to): 
* https://github.com/aspnet/IISIntegration/blob/dev/nuget/AspNetCore.nuspec
* https://github.com/aspnet/AspNetCoreModule/blob/dev/nuget/AspNetCore.nuspec

cc @Eilon @muratg @natemcmaster

**Comment by Eilon** [comment]
We should keep this NUSPEC but change the package name and metadata to be clear it is super duper internal and not for public consumption:
* https://github.com/aspnet/IISIntegration/blob/dev/nuget/AspNetCore.nuspec

We'll delete this package anyway:
* https://github.com/aspnet/AspNetCoreModule/blob/dev/nuget/AspNetCore.nuspec

**Comment by Eilon** [comment]
Everything that needs to be done for shipping packages is done.
