### ISSUE TITLE
64-bit .NET Core on Antares

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Universe#885]
As part of our effort to add support for 64-bit runtimes on Antares, we'll need to verify that this works on a private stamp.
The current plan on record deploy only the 64-bit runtime (and not the 64-bit SDK) via rapid update mechanism.

**Comment by shirhatti** [comment]
cc @muratg @leecow @davidebbo

**Comment by muratg** [comment]
cc @BrennanConroy

**Comment by BrennanConroy** [comment]
In 2.1.0-preview1 we now install the runtime/sdk via a Site Extension instead of already having the runtime/sdk already installed on the machine. Is this not how we want to do 64 bit also?

**Comment by shirhatti** [comment]
Nothing changes for the previews.

However, this is how we plan to ship rc/rtm (for both 32/64 bit). I only put it in the preview2 milestone so we can validate this scenario during that time frame.

**Comment by shirhatti** [comment]
@BrennanConroy, @muratg and I spoke offline.

The current plan is to deploy only a 64-bit runtime (in addition to the 32-bit SDK and runtime that we already deploy). We will not be deploying a 64-bit SDK. 
Additionally, 64-bit support for out-of-proc apps is a non-goal.

The scenarios we want to verify are
- [ ] Publishing via kudu. (Build with 32-bit SDK and run against a 64-bit runtime)
  - [ ] Test with an app that has a native dependency
- [ ] Ensure in-process 32-bit apps will still work

@jkotalik @davidebbo Any other scenarios you want tested?

**Comment by davidebbo** [comment]
Did you mean *Ensure **out-of-process** 32-bit apps will still work*? Since that's all we have today.

**Comment by jkotalik** [comment]
Also we should ensure that inproc works with both 32 and 64 bit (that it at least starts).

**Comment by muratg** [comment]
@BrennanConroy @shirhatti This is done?

**Comment by BrennanConroy** [comment]
InProc worked well on x64 and x86, and out-of-process 32 bit apps still work

**Comment by muratg** [comment]
@shirhatti Anything else you'd like verified? Or good to close?

**Comment by shirhatti** [comment]
Good to close 😄
