### ISSUE TITLE
Offline package cache lacks package for linux standalone publish

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#888]
```
Linux pakrym-rh-74 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
```

1. Get sdk.tar.gz, unpack
2. `dotnet new razor`
3. `~/.dotnet/dotnet publish --runtime rhel.7-x64"

Expected:

All good, app published

Actual:
```
[pakrym@pakrym-rh-74 razor]$ ~/.dotnet/dotnet publish --runtime rhel.7-x64
Microsoft (R) Build Engine version 15.7.11.29948 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /home/pakrym/razor/razor.csproj...
/home/pakrym/razor/razor.csproj : error NU1102: Unable to find package runtime.linux-x64.Microsoft.NETCore.App with version (>= 2.1.0-preview1-26213-01)
/home/pakrym/razor/razor.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 2.0.5 ]
/home/pakrym/razor/razor.csproj : error NU1102: Unable to find package runtime.linux-x64.Microsoft.NETCore.DotNetHostPolicy with version (>= 2.1.0-preview1-26213-01)
/home/pakrym/razor/razor.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 2.0.5 ]
/home/pakrym/razor/razor.csproj : error NU1102: Unable to find package runtime.linux-x64.Microsoft.NETCore.DotNetHostResolver with version (>= 2.1.0-preview1-26213-01)
/home/pakrym/razor/razor.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 2.0.5 ]
/home/pakrym/razor/razor.csproj : error NU1102: Unable to find package runtime.linux-x64.Microsoft.NETCore.DotNetAppHost with version (>= 2.1.0-preview1-26213-01)
/home/pakrym/razor/razor.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 2.0.5 ]
  Restore failed in 998.11 ms for /home/pakrym/razor/razor.csproj.
  Restore completed in 13.6 ms for /home/pakrym/razor/razor.csproj.
```

/cc @muratg

**Comment by natemcmaster** [comment]
We've discussed before. This is out of scope for the LZMA. See https://github.com/dotnet/cli/issues/7089

**Comment by pakrym** [comment]
Then why do we have other runtime.* package in it? 
```

/home/pakrym/.dotnet/sdk/NuGetFallbackFolder/runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl:
4.3.0

/home/pakrym/.dotnet/sdk/NuGetFallbackFolder/runtime.opensuse.42.1-x64.runtime.native.system.security.cryptography.openssl:
4.3.0

/home/pakrym/.dotnet/sdk/NuGetFallbackFolder/runtime.osx.10.10-x64.runtime.native.system.security.cryptography.apple:
4.3.0

/home/pakrym/.dotnet/sdk/NuGetFallbackFolder/runtime.osx.10.10-x64.runtime.native.system.security.cryptography.openssl:
4.3.0

/home/pakrym/.dotnet/sdk/NuGetFallbackFolder/runtime.rhel.7-x64.runtime.native.system.security.cryptography.openssl:
4.3.0

/home/pakrym/.dotnet/sdk/NuGetFallbackFolder/runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography.openssl:
4.3.0

/home/pakrym/.dotnet/sdk/NuGetFallbackFolder/runtime.ubuntu.16.04-x64.runtime.native.system.security.cryptography.openssl:
4.3.0

/home/pakrym/.dotnet/sdk/NuGetFallbackFolder/runtime.ubuntu.16.10-x64.runtime.native.system.security.cryptography.openssl:
```

**Comment by natemcmaster** [comment]
This looks wrong. I don't know off the top of my head, but it's possible these packages are in the restore graph of a portable (non-RID) restore. @JunTaoLuo any ideas?

**Comment by muratg** [comment]
@glennc @DamianEdwards blocker for preview1 or wait until preview2?  (I'm assuming latter.)

**Comment by natemcmaster** [comment]
I tracked this backward. These runtime.* packages come in as a part of the normal restore graph, even a "portable" restore.
```
Microsoft.AspNetCore.Authentication.JwtBearer
-> Microsoft.IdentityModel.Protocols.OpenIdConnect/5.2.0-preview2-41113220915
-> Microsoft.IdentityModel.Protocols/5.2.0-preview2-41113220915
-> System.Net.Http/4.3.0
  -> runtime.native.System.Security.Cryptography.OpenSsl
     -> runtime.* packages
```

**Comment by natemcmaster** [comment]
@muratg unless the requirements for the LZMA have changed, I don't think is something we need to fix. LZMA is supposed to contain packages required for a portable restore of an aspnetcore app, not a RID-restore.

cc @livarcocc

**Comment by muratg** [comment]
Isn't that RID matching the OS @pakrym is using?  My understanding from the bug is that on RH, standalone publishing is broken, but maybe I misunderstood.

**Comment by pakrym** [comment]
It's broken only in offline scenario which we don't seem to care about.

**Comment by natemcmaster** [comment]
Exactly. The offline package cache does not support standalone publishing. You have to restore from myget.org/nuget.org to get the additional packages.

**Comment by livarcocc** [comment]
Yep. Historically, we have only put in the LZMA the packages for portable applications. If we decide to support RID specific ones, then we would need either to have a bloated lzma with all the supported RIDs or we would need RID specific LZMAs.

I vote to continue supporting portable applications only. One of the main goals of the offline cache is the class scenario where we don't want folks to all hit the web at the same time for hundreds of mbs right after having downloaded the SDK.

**Comment by natemcmaster** [comment]
See https://github.com/aspnet/Universe/pull/889

**Comment by JunTaoLuo** [comment]
It's odd that runtime.* packages are being restored as part of a portable restore but I guess that's fine. There's no issue that needs fixing here.

**Comment by muratg** [comment]
Thanks guys, sounds good.
