### ISSUE TITLE
Package icons do not work

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#898]
The link (https://go.microsoft.com/fwlink/?LinkID=288859) we have for ASP.NET Core package icons doesn't work

https://github.com/aspnet/BuildTools/blob/bb4d0a2b748dcdcc62c5c15427e4c989054ff757/src/Internal.AspNetCore.Sdk/build/Common.props#L21

/cc @Eilon @muratg

**Comment by Eilon** [comment]
Known issue, being resolved by the team that owns it.
