### ISSUE TITLE
Projects with ExperimentalVersionPrefix are missing build number

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#901]
We're missing the build number now for IsFinalBuild=false builds.

![image](https://user-images.githubusercontent.com/2696087/36327496-9ad8db82-1313-11e8-9d03-1edf05a6cbdf.png)

**Comment by ryanbrandenburg** [comment]
Fixes for these should be in now. Will close out once a build has produced the right numbers.

**Comment by Eilon** [comment]
@ryanbrandenburg presumably this can be closed now? Can you confirm?
