### ISSUE TITLE
Dev experience improvement idea:  Install required VS via a script

### ISSUE THREAD

**Issue by muratg** [aspnet/Universe#903]
Opening this up for discussion (over GitHub or in the engineering triage.)

I'm hoping to get to a point where building a random ASP.NET repo (including Universe) on a dev machine becomes "easier".  

One issue I hit today: VS requirement.

We are currently installing the required .NET Core SDK with the build scripts. but VS (for example) is not automatically installed. I don't think we can get rid of VS requirement completely - some repos depend on it.  Currently, if the required version of the VS is not on the machine, builds for these repos (and Universe) fail on that machine. 

VS installations can be side by side these days, and can be automated with some rough edges (@natemcmaster did some experimentation I believe.)  

So I propose the following:

0) Optional: Move to a "CI" suitable SKU of VS. I believe such a thing without the VS UI exists.
1) Write a script to detect the build time requirements of the current repo on a given machine. For example "does this version of VS exist on this machine?"
2) Run this at the beginning of build.cmd/build.sh 
3) Either tell the user that they need to take action (and what) before starting the build, or better, tell install the requirement automatically.

I propose we start with Windows, and my first hope is to improve dev time experience, but if we could do this on all OS/bitness combinations and across all repos, we can start being smarter about agent management on the CI (for example, increasing capacity when there are a lot of builds waiting)

**Comment by natemcmaster** [comment]
For implementation ideas, we talked about doing this, but never got around to implementing it: https://github.com/aspnet/BuildTools/issues/445

**Comment by natemcmaster** [comment]
@jkotalik did this in https://github.com/aspnet/BuildTools/pull/690.
