### ISSUE TITLE
Build fails due to package dependencies not found.

### ISSUE THREAD

**Issue by pkapare** [aspnet/Universe#913]
When I run build.cmd ALL submodules builds successfully without any errors however overall build is failing with following error: (Pasting relevant sections of console log.)
Note : All missing packages mentioned in below log are present in H:\Github\DotNetCore\Universe\artifacts\build folder. Do I need to do any specific settings?

 - Package: Microsoft.Extensions.Logging.Console Version: [2.1.0-preview2-t005e8c3cb]
   - Package: Microsoft.Extensions.Logging.Debug Version: [2.1.0-preview2-t005e8c3cb]
   - Package: Microsoft.Extensions.Logging.EventSource Version: [2.1.0-preview2-t005e8c3cb]
   - Package: Microsoft.Extensions.Logging.TraceSource Version: [2.1.0-preview2-t005e8c3cb]
   - Package: Microsoft.Extensions.ObjectPool Version: [2.1.0-preview2-t005e8c3cb]
   - Package: Microsoft.Extensions.Options Version: [2.1.0-preview2-t005e8c3cb]
   - Package: Microsoft.Extensions.Options.ConfigurationExtensions Version: [2.1.0-preview2-t005e8c3cb]
   - Package: Microsoft.Extensions.Primitives Version: [2.1.0-preview2-t005e8c3cb]
   - Package: Microsoft.Extensions.WebEncoders Version: [2.1.0-preview2-t005e8c3cb]
   - Package: Microsoft.Net.Http.Headers Version: [2.1.0-preview2-t005e8c3cb]
  Restoring packages for H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj...
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102: Unable to find package Microsoft.AspNetCore with version (= 2.1.0-preview2-t005e8c3cb)
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 17 version(s) in NuGet [ Nearest version: 2.0.1 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 1 version(s) in H:\Github\DotNetCore\Universe\artifacts\build\ [ Nearest version: 2.1.0-preview2-t005e8bf69 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\ext\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\mirror\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Antiforgery with version (= 2.1.0-preview2-t005e8c3cb)
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 18 version(s) in NuGet [ Nearest version: 2.0.1 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 3 version(s) in H:\Github\DotNetCore\Universe\artifacts\build\ [ Nearest version: 2.1.0-preview2-t005e8bf69 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\ext\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\mirror\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Authentication with version (= 2.1.0-preview2-t005e8c3cb)
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 17 version(s) in NuGet [ Nearest version: 2.0.1 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 1 version(s) in H:\Github\DotNetCore\Universe\artifacts\build\ [ Nearest version: 2.1.0-preview2-t005e8bf69 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\ext\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\mirror\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Authentication.Abstractions with version (= 2.1.0-preview2-t005e8c3cb)
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 5 version(s) in NuGet [ Nearest version: 2.0.1 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 3 version(s) in H:\Github\DotNetCore\Universe\artifacts\build\ [ Nearest version: 2.1.0-preview2-t005e8bf69 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\ext\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\mirror\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Authentication.Cookies with version (= 2.1.0-preview2-t005e8c3cb)
....
.....
.....

H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 21 version(s) in NuGet [ Nearest version: 2.0.1 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 3 version(s) in H:\Github\DotNetCore\Universe\artifacts\build\ [ Nearest version: 2.1.0-preview2-t005e8bf69 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\ext\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\mirror\
  Generating MSBuild file H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\obj\Microsoft.AspNetCore.App.csproj.nuget.g.props.
  Generating MSBuild file H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\obj\Microsoft.AspNetCore.App.csproj.nuget.g.targets.
  Restore failed in 2.06 sec for H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.App\Microsoft.AspNetCore.App.csproj.
  AllMetapackage will include the following packages
   - Package: Microsoft.AspNetCore Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Antiforgery Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.ApplicationInsights.HostingStartup Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.Cookies Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.Core Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.Facebook Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.Google Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.JwtBearer Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.MicrosoftAccount Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.OAuth Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.OpenIdConnect Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authentication.Twitter Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authorization Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Authorization.Policy Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.AzureAppServices.HostingStartup Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.AzureAppServicesIntegration Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.CookiePolicy Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Cors Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Cryptography.Internal Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Cryptography.KeyDerivation Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.DataProtection Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.DataProtection.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.DataProtection.AzureKeyVault Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.DataProtection.AzureStorage Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.DataProtection.Extensions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Diagnostics Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Diagnostics.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Hosting Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Hosting.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Hosting.Server.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Html.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Http Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Http.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Http.Extensions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Http.Features Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.HttpOverrides Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.HttpsPolicy Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Identity Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Identity.UI Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Identity.EntityFrameworkCore Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.JsonPatch Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Localization Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Localization.Routing Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.MiddlewareAnalysis Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.ApiExplorer Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.Core Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.Cors Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.DataAnnotations Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.Formatters.Json Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.Formatters.Xml Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.Localization Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.Razor Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.Razor.Extensions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.Razor.ViewCompilation Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.RazorPages Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.TagHelpers Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Mvc.ViewFeatures Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.NodeServices Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Owin Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Protocols.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Razor Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Razor.Design Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Razor.Language Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Razor.Runtime Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.ResponseCaching Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.ResponseCaching.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.ResponseCompression Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Rewrite Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Routing Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Routing.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Server.HttpSys Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Server.IISIntegration Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Server.Kestrel Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Server.Kestrel.Core Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Server.Kestrel.Https Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Session Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.SignalR Version: 1.0.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.SignalR.Common Version: 1.0.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.SignalR.Core Version: 1.0.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Sockets Version: 1.0.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Sockets.Abstractions Version: 1.0.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Sockets.Common.Http Version: 1.0.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.Sockets.Http Version: 1.0.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.SignalR.Redis Version: 1.0.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.SpaServices Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.SpaServices.Extensions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.StaticFiles Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.WebSockets Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.AspNetCore.WebUtilities Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.CodeAnalysis.Razor Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Data.Sqlite Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Data.Sqlite.Core Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.EntityFrameworkCore Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.EntityFrameworkCore.Attributes Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.EntityFrameworkCore.Design Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.EntityFrameworkCore.InMemory Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.EntityFrameworkCore.Relational Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.EntityFrameworkCore.Sqlite Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.EntityFrameworkCore.Sqlite.Core Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.EntityFrameworkCore.SqlServer Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.EntityFrameworkCore.Tools Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Caching.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Caching.Memory Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Caching.Redis Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Caching.SqlServer Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.AzureKeyVault Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.Binder Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.CommandLine Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.EnvironmentVariables Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.FileExtensions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.Ini Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.Json Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.UserSecrets Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Configuration.Xml Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.DependencyInjection Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.DependencyInjection.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.DiagnosticAdapter Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.FileProviders.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.FileProviders.Composite Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.FileProviders.Embedded Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.FileProviders.Physical Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.FileSystemGlobbing Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Hosting.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Hosting Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Http Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Identity.Core Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Identity.Stores Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Localization Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Localization.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Logging Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Logging.Abstractions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Logging.AzureAppServices Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Logging.Configuration Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Logging.Console Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Logging.Debug Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Logging.EventSource Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Logging.TraceSource Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.ObjectPool Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Options Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Options.ConfigurationExtensions Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.Primitives Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Extensions.WebEncoders Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.Net.Http.Headers Version: 2.1.0-preview2-t005e8c3d5
   - Package: Microsoft.VisualStudio.Web.BrowserLink Version: 2.1.0-preview2-t005e8c3d5
  Restoring packages for H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj...
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102: Unable to find package Microsoft.AspNetCore with version (>= 2.1.0-preview2-t005e8c3d5)
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 17 version(s) in NuGet [ Nearest version: 2.0.1 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 1 version(s) in H:\Github\DotNetCore\Universe\artifacts\build\ [ Nearest version: 2.1.0-preview2-t005e8bf69 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\ext\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\mirror\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Antiforgery with version (>= 2.1.0-preview2-t005e8c3d5)
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 18 version(s) in NuGet [ Nearest version: 2.0.1 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 3 version(s) in H:\Github\DotNetCore\Universe\artifacts\build\ [ Nearest version: 2.1.0-preview2-t005e8bf69 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\ext\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\mirror\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.ApplicationInsights.HostingStartup with version (>= 2.1.0-preview2-t005e8c3d5)
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 5 version(s) in NuGet [ Nearest version: 2.0.1 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 1 version(s) in H:\Github\DotNetCore\Universe\artifacts\build\ [ Nearest version: 2.1.0-preview2-t005e8bf69 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\ext\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 0 version(s) in H:\Github\DotNetCore\Universe\obj\mirror\
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Authentication with version (>= 2.1.0-preview2-t005e8c3d5)
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 17 version(s) in NuGet [ Nearest version: 2.0.1 ]
H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.All\Microsoft.AspNetCore.All.csproj : error NU1102:   - Found 1 version(s) in H:\Github\DotNetCore\Universe\artifacts\build\ [ Nearest version: 2.1.0-preview2-t005e8bf69 ]
........
........
........

H:\Github\DotNetCore\Universe\.w\Microsoft.AspNetCore.Analyzers\Microsoft.AspNetCore.Analyzers.csproj : error NU1102:   - Found 0 version(s) in NuGet
    0 Warning(s)
    298 Error(s)

Time Elapsed 00:19:08.18
dotnet.exe failed with exit code: 1
At C:\Users\Vedan\.dotnet\buildtools\korebuild\2.1.0-preview2-15710\scripts\common.psm1:11 char:9
+         throw "$cmdName failed with exit code: $exitCode"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit code: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1

**Comment by Eilon** [comment]
Hi @pkapare there are some known issues with building Universe locally, which we are covering in this issue: https://github.com/aspnet/Universe/issues/512
