### ISSUE TITLE
Microsoft.AspNetCore.App is not specifying version ranges for 3rd party dependencies

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#920]
_From @DamianEdwards on February 27, 2018 1:8_

It seems that *Microsoft.AspNetCore.App* is not currently setting version ranges for the 3rd party dependencies in the transitive graph, e.g. *Newtonsoft.Json*.

Do folks think we should instead be locking these versions to the known good version, given the intent is to ensure folks can't be lifted out of the supported state without a warning (direct reference) or error (transitive lifting)? My gut is saying we should be limiting these too.

Thoughts @davidfowl @JunTaoLuo @Eilon ?

_Copied from original issue: aspnet/MetaPackages#259_

**Comment by JunTaoLuo** [comment]
Yes we should, I thought I filed a bug for this in preview2 since we were running out of time for preview1 but I can no longer find it. I'll move this issue to Universe.

**Comment by natemcmaster** [comment]
To be 100% clear, are we talking about adding **maximum** versions to this range, or just a required minimum?

**Comment by DamianEdwards** [comment]
Yes, **exact** versions to be absolutely clear.

**Comment by natemcmaster** [comment]
Have we considered other solutions? I'm concerned exact version limitations will make it harder for library authors to write libraries compatible with multiple platforms, including ASP.NET Core. We don't own re-linq, ix-async, identity model, or JSON.NET and don't align with their release cycles. I'm not convinced benefits of restricting versions outweigh the negative impact on the ecosystem.

**Comment by DamianEdwards** [comment]
We considered many aspects and trade-offs when coming up with the current plan. The fact that we don't own (and thus control) those libraries is exactly the reason why this is more important, as we've had numerous examples of customers being broken by dependencies being lifted without their knowledge, across breaking changes. Despite the best intentions of SemVer, this simply can't be reliably managed using a range that assumes future versions, especially on components we don't control. And in the case of libraries like JSON.NET, the normal cadence involves a few patches before a major version anyway, so using a max version that goes up to but excludes the next major doesn't gain us much anyway.

When using *Microsoft.AspNetCore.App* this is the behavior you get. You can work around it easily enough by hoisting the affected libraries to top-level dependencies, at which point the error turns into a warning and can be suppressed. If folks really don't like this behavior they can continue to use *Microsoft.AspNetCore.All* or go to individual package references. And if we get overwhelming feedback that this still isn't acceptable, we can revisit it.

**Comment by Eilon** [comment]
Exactly what would the caps be? E.g. `Newtonsoft.Json` version `[10.0.1,10.1.0)`? That is, allow patches, but no major/minor updates? Or even lock down on patches?

As long as lifting at the direct-reference layer works, this seems like a minor encumbrance with a decent amount of value.

**Comment by DamianEdwards** [comment]
The current plan has the versions be exact: `[10.0.1,10.0.1]`. i.e. locked down completely. Like I said, given we don't control these components we can't rely on their versioning schemes to accurately reflect what's safe and what isn't. Folks who want to use a later version can do so via direct-reference and then suppressing the warning.

We would commit to reviewing these in each release (patches too) to help customers keep these dependencies current in the default experience. So for example, say we set `Newtonsoft.Json` to version 11 in our 2.1.0 meta-package, then version 11.0.1 is released, in our 2.1.1 we would assess whether moving the dependency to 11.0.1 is safe and if so do it.

**Comment by davidfowl** [comment]
Why do we need to lock these down at all though? If they can't lift the ASP.NET Core dependencies does it matter?

**Comment by DamianEdwards** [comment]
They can still affect (even break) the application after being silently lifted.

**Comment by davidfowl** [comment]
We should be less concerned about that. Lets just start with out dependencies and see how that works out before we lock down things we don't own.

**Comment by DamianEdwards** [comment]
OK thought about this and chatted with @davidfowl offline a bit and I'm OK to leave this as is for now (no version ranges for the 3rd party deps). The chances that a new version of these will break **our** bits is minuscule, and we can react if that ever does happen. If folks choose to lift the version in their projects and it breaks something that they're using directly (rather than snapping our use of it) then that's a different matter and par for the course when taking direct dependencies.
