### ISSUE TITLE
Trim aspnet package referenced individually

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#921]
This needs some design/exploration.

The current trimming mechanism relies on both the property MicrosoftNETPlatformLibrary being set and he package to trim being in the restore graph. This means that all apps referencing individual packages must also reference Microsoft.AspNetCore.App or Microsoft.AspNetCore.All if they want their output trimmed which may defeat the purpose of referencing the individual packages in the first place.

I see two ways around this:
1. We change the trimming mechanism to not rely on the restore graph of the project to figure out which binaries can be trimmed. This will need to be a change in the dotnet sdk, so not sure how feasible this is for 2.1.
2. As suggested by @davidfowl, we could add an implicit reference to the aspnet metapackages and exclude them from compile/build/intellisense, at which point they only exist in the restore graph and is only used for trimming. 

Note that for the second approach, we will need to think about when/where to add the implicit reference. Do we update the SDK to add this reference like they do for NETCore.App? Do we add this reference for all apps or condition this so that the reference is only added when referencing aspnet packages?

cc @DamianEdwards @Eilon @muratg

**Comment by DamianEdwards** [comment]
We didn't talk about this one today either.

**Comment by muratg** [comment]
Do we need another design meeting?

**Comment by DamianEdwards** [comment]
Might not hurt

**Comment by JunTaoLuo** [comment]
Tracking work in https://github.com/aspnet/Universe/issues/967

**Comment by muratg** [comment]
@JunTaoLuo This one's dev branch only, right?

**Comment by JunTaoLuo** [comment]
Right, this will be post 2.1.

**Comment by JunTaoLuo** [comment]
@DamianEdwards @natemcmaster is this something we still want to explore?

**Comment by natemcmaster** [comment]
I think at this point we're not trying to change much about the 2.2 metapackage/sharedfx implementation. We're overhauling this in 3.0 anyways, so it's IMO it's probably not worth investing much in new assembly trimming strategies for 2.2.

**Comment by JunTaoLuo** [comment]
👍 wanted to double check before closing.
