### ISSUE TITLE
Refactor LZMA and installers targets into individual project builds

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Universe#923]
Prototype code:
https://github.com/aspnet/Universe/blob/23de03147dc13dc9655882d77f5e21229f5ea168/src/PackageArchive/PackageArchive.targets
https://github.com/aspnet/Universe/tree/23de03147dc13dc9655882d77f5e21229f5ea168/src/Installers

Refactor the targets for building the LZMA, installers (debian, rpm), and tarballs into individual projects instead of repo.targets

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspNetCore#3653
