### ISSUE TITLE
Make API baseline generation part of the universe builds

### ISSUE THREAD

**Issue by javiercn** [aspnet/Universe#929]
We want to generate baselines automatically as part of Universe.
Initially we will generate baselines in a different configuration (UniverseBaselines).
Once we iron out the kinks, asses its stability we will decide whether or not we move it into universe.

**Comment by Eilon** [comment]
Load balancing to @ryanbrandenburg . Please make sure changes are reviewed by @natemcmaster and @javiercn .

**Comment by ryanbrandenburg** [comment]
UniverseCoherence now generates baselines inside the modules `bin/Release/TFM/`. I'll make them artifacts so they're preserved for future processes to use.

**Comment by Eilon** [comment]
3-Done?
