### ISSUE TITLE
Scaffolding package versions need to match Microsoft.AspNetCore.App package versions

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Universe#935]
Since the `Microsoft.AspNetCore.App` package uses '=' for dependency versions, the scaffolding packages need to match the version of `Microsoft.AspNetCore.App`.

This will be implicitly true till we RTM 2.1, but for later patch builds this needs to be ensured.

cc @natemcmaster, @Eilon, @seancpeters

**Comment by Eilon** [comment]
Will revisit late in the 2.1.0 release cycle so that we can account for this in patch releases.

**Comment by natemcmaster** [comment]
I don't think it was sent in for approval. For the 2.1.1, we incidentally are patching Scaffolding packages as a result of its dependencies updating. 

We may still need to do some work here to ensure VS can use the right package version. @seancpeters what is the best way that we can help you ensure VS uses the right version of Scaffolding packages in 2.1.x?

**Comment by mkArtakMSFT** [comment]
@vijayrkn, will you be taking this to the shiproom for approval?

**Comment by vijayrkn** [comment]
@mkArtakMSFT - sure.

**Comment by natemcmaster** [comment]
Moving this to 2.1.3 as we don't need to solve this in 2.1.1 or 2.1.2.

**Comment by natemcmaster** [comment]
Met yesterday. @vijayrkn, you're sending a request for shiproom approval, right?

**Comment by vijayrkn** [comment]
ya, will do.

**Comment by vijayrkn** [comment]
>Moving this to 2.1.3 as we don't need to solve this in 2.1.1 or 2.1.2.
Do you need the approval for 2.1.2 or 2.1.3?

**Comment by natemcmaster** [comment]
Yes. We would need approval for changes in either patch.

**Comment by natemcmaster** [comment]
@vijayrkn I've moved this issue to a new milestone since we're not addressing it in the 2.1.2 release. 

Currently, xcaffolding will patch in 2.1.3 patch release, but it's currently building Microsoft.VS.CodeGen.* packages as 2.1.2.  AspNetCore.App will be 2.1.3. Have you and @seancpeters figured out what we should do about this? Do we need to have Scaffolding skip a version number to match? Or are we okay with a mismatch?

**Comment by Eilon** [comment]
@vijayrkn / @seancpeters - any updates on this? The clock is ticking for 2.1.3...

**Comment by vijayrkn** [comment]
We have shiproom approval for this change. I think we should make scaffolding skip a version to match. @seancpeters - can you please work with Nate and get this going?

**Comment by natemcmaster** [comment]
The build is already set up to skip from 2.1.1 to 2.1.3. I think the question Eilon was asking about more is do we need to keep doing this for every release? Or, did you make progress on other designs, such as having some other way for VS to determine which scaffolding packages to use?

**Comment by vijayrkn** [comment]
We are working on an improved design. Dont have a timeline since it has to align with VS release.

**Comment by seancpeters** [comment]
We've got some changes in the works for how to decide the scaffolding package versions, but my understanding is that they'd go in for dev16.

**Comment by Eilon** [comment]
Actually my real question was just that this issue is in 2.1.3 and it wasn't clear to me if "someone" did "something" to resolve this issue 😄

**Comment by natemcmaster** [comment]
I double checked, and it looks like my change to jump from 2.1.1 to 2.1.3 was lost somewhere in the massive amounts of rebasing/merging we did to make 2.1.2 work.

This PR should resolve this issue: https://github.com/aspnet/Scaffolding/pull/837

**Comment by natemcmaster** [comment]
Done in https://github.com/aspnet/Scaffolding/pull/837
