### ISSUE TITLE
Versioning policy for references to .App/.All metapackage

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#967]
Need to decide/implement:

1) Do we update the version number of the .App/.All metapackage reference in templates at 2.1.0? The patch roll forward behaviour of the host should mean that we do not need to update the version of the package reference.
  a) How does standalone publish work in this case?
2) What do we need to do to ensure that VS does not offer package upgrades for .App/.All and keeps the reference at 2.1.0?
3) File an issue for the Web SDK to ensure the .App and .All are marked with attributes marking them as SDK depedencies in VS
4) Explore .App having an explicit dependency on Microsoft.NETCore.App.

cc @davidfowl @natemcmaster

**Comment by JunTaoLuo** [comment]
The work that remains in this item and https://github.com/aspnet/Universe/issues/921 are now highly related. I'll post an update to our plans for these features but it looks like we should push this out to rc. cc @muratg

**Comment by muratg** [comment]
@JunTaoLuo Do we need more decisions from @DamianEdwards on this one?

**Comment by JunTaoLuo** [comment]
No we need to just try out the current proposal now and see if it works well.

**Comment by Eilon** [comment]
@JunTaoLuo - where is the current proposal located?

**Comment by JunTaoLuo** [comment]
The current design is to remove the version but retain the reference to Microsoft.AspNetCore.App inside the project templates. In the web sdk, we will implicitly set the version to the major/minor based on the tfm. Roll forward will be used to run on the latest installed framework and a separate mechanism will be introduced for self contained apps. 

We are also exploring adding an implicit reference to Microsoft.AspNetCore.App via the web sdk for apps targeting netcoreapp2.1 (and higher) to enable publish trimming when only individual aspnet packages are used.

**Comment by muratg** [comment]
@JunTaoLuo I think this will require a shiproom mail as well.

**Comment by JunTaoLuo** [comment]
Updated POR:

We will be removing the explicit version number of the Microsoft.AspNetCore.App package reference from the templates and inject an implicit version via the Microsoft.NET.Web.Sdk. We will also be marking the package reference with IsImplicitlyDefined="true" to prevent the NuGet package manager from offering updates in VS. The implicit version number will be determined based on the TFM and we will rely on roll-forward to run on the latest installed shared framework for portable apps. We will also be using the TargetLatestRuntimePatch switch to determining which patch version (latest vs default) to use as the implicit version for self contained apps.

Changes required:
Dotnet SDK: update implicit version checks to operate on a list of packages instead of a single Microsoft.NETCore.App package
Aspnet Templating: Remove explicit version numbers for Microsoft.AspNetCore.App references
Web SDK: Logic for determining and setting the implicit version of Microsoft.AspNetCore.App
Dotnet CLI: Integration testing and bundled version for Microsoft.AspNetCore.App

Testing:
Unit tests in Dotnet SDK
Unit tests in AspNet Templating
Integration tests in Dotnet CLI

**Comment by muratg** [comment]
@JunTaoLuo This is approved for checkin to RC1.

**Comment by muratg** [comment]
Reminder: ask mode ends today.

**Comment by JunTaoLuo** [comment]
Yes the only item left is the integration tests and bundled versions in CLI. I'll make sure this goes in today.

**Comment by JunTaoLuo** [comment]
All PRs have been merged, I'll mark this as done but I'll keep an eye out for any issues.

**Comment by muratg** [comment]
Thanks!
