### ISSUE TITLE
Fix build.cmd to handle paths containing special chars

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Universe#99]
`build.cmd` is currently unable to work with paths containing special characters. Consider fixing it.

Repro: create a Windows account containing a space and try running `build.cmd`

``` bat
@echo off
cd %~dp0

SETLOCAL
SET CACHED_NUGET=%LocalAppData%\NuGet\NuGet.exe

IF EXIST %CACHED_NUGET% goto copynuget
echo Downloading latest version of NuGet.exe...
IF NOT EXIST %LocalAppData%\NuGet md %LocalAppData%\NuGet
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "$ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest 'https://www.nuget.org/nuget.exe' -OutFile '%CACHED_NUGET%'"

:copynuget
IF EXIST .nuget\nuget.exe goto build
md .nuget
copy %CACHED_NUGET% .nuget\nuget.exe > nul

:build
.nuget\nuget.exe install Sake -version 0.2 -o packages
packages\Sake.0.2\tools\Sake.exe -I build -f makefile.shade %*
```

**Comment by PinpointTownes** [comment]
@muratg AFAIK, this change has not been ported to the other repositories. There are still weird issues with paths containing spaces.

**Comment by muratg** [comment]
@PinpointTownes oh, I see. Reopening and putting it in backlog.

**Comment by PinpointTownes** [comment]
FYI, this bug is still present in the CLI flavor of `build.cmd`. It might be a good thing to fix it soon, no? :smile:

**Comment by muratg** [comment]
Isn't there a bug in CLI repo tracking this?
