### ISSUE TITLE
Add Update repos build configuration for 2.1 branch

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#991]
/cc @ryanbrandenburg @natemcmaster @pranavkm

**Comment by Eilon** [comment]
Yeah sure. @ryanbrandenburg / @natemcmaster / @pranavkm - can you guys fight over who can do this the fastest?

**Comment by natemcmaster** [comment]
I'll just run the update script from my box. IMO no need to make a CI config to run this since we should be locking in 2 days, right?

**Comment by natemcmaster** [comment]
Script passed successfully. All repos should be on 2.1.0-preview2-30478 now.

**Comment by ryanbrandenburg** [comment]
I created this config for 2.1.0 releases after preview2. We haven't run it since we don't want to make commits for release/2.1 right now, but it's just a copy of the existing one so I think we're good.
